/* NayaNET Assistant Runtime — governed authenticated session + durable cognition boundary. */
(()=>{'use strict';
const URL='https://dahisasgpfvziswqvmvm.supabase.co',KEY='sb_publishable_oQFKOYFuJ9bT-E9QkJUb4g_lAUyInue',PROJECT='NayaNET';
let client=null,session=null,modal=null;
const state={authenticated:false,user_id:null,session_id:null,persistence:'unknown'};
function load(){return new Promise((resolve,reject)=>{if(window.supabase?.createClient)return resolve(window.supabase);const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=()=>resolve(window.supabase);s.onerror=reject;document.head.append(s)})}
async function init(){const lib=await load();client=lib.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storage:window.localStorage,storageKey:'nayanet.supabase.auth'}});const got=await client.auth.getSession();session=got.data.session||null;apply(session);client.auth.onAuthStateChange((_e,s)=>{session=s;apply(s)});if(session)await initialize();return snapshot()}
function apply(s){state.authenticated=!!s;state.user_id=s?.user?.id||null;state.session_id=s?.access_token?String(s.access_token).slice(0,12):null;state.persistence=s?'supabase:session':'unauthenticated';document.documentElement.dataset.nayaAuth=s?'authenticated':'anonymous';window.dispatchEvent(new CustomEvent('naya-auth-state',{detail:snapshot()}))}
function snapshot(){return {...state}}
async function initialize(){if(!session)return false;const r=await client.rpc('nayanet_initialize_cognition',{p_project_id:PROJECT,p_state:{runtime:'assistant-cloudflare',initialized_at:new Date().toISOString()}});if(r.error)throw r.error;state.persistence='supabase:connected';return true}
async function signIn(email,password){if(!client)await init();const r=await client.auth.signInWithPassword({email:String(email).trim(),password});if(r.error)throw r.error;session=r.data.session;apply(session);await initialize();return snapshot()}
async function signOut(){if(client)await client.auth.signOut();session=null;apply(null);return snapshot()}
async function record(input){if(!client)await init();if(!session)throw new Error('AUTH_REQUIRED');const event={...input,event_id:input.event_id||('assistant_'+Date.now().toString(36)),project:PROJECT,source:input.source||'nayanet-assistant-cloudflare',actor:'human',created_at:new Date().toISOString(),schema_version:'2.0.0'};const r=await client.rpc('nayanet_record_cognition_event',{p_project_id:PROJECT,p_event:event,p_action:'record_intelligence',p_expected_result:'event persisted with receipt',p_observed_result:'event persisted',p_learning:[{status:'captured',at:new Date().toISOString()}]});if(r.error)throw r.error;return r.data}
async function retrieve(eventId){if(!client)await init();if(!session)throw new Error('AUTH_REQUIRED');let q=client.from('nayanet_cognition_events').select('*').eq('project_id',PROJECT);if(eventId)q=q.eq('event_id',eventId);const r=await q.order('created_at',{ascending:false}).limit(100);if(r.error)throw r.error;return r.data||[]}
async function captureSmartNote(input){const title=String(input?.title||'').trim();const content=String(input?.content||'').trim();if(!title||!content)throw new Error('SMART_NOTE_CONTENT_REQUIRED');const seed=(title+'\\n'+content).toLowerCase().replace(/\\s+/g,' ').trim();let hash=0;for(let i=0;i<seed.length;i++)hash=((hash<<5)-hash+seed.charCodeAt(i))|0;const event_id='smart-note-'+Math.abs(hash).toString(36);return record({...input,event_id,title,content,source:input.source||'nayanet-hub.smart-note-capture',status:input.status||'active',actor:'human',tags:Array.isArray(input.tags)?input.tags:['smart-note','intelligent-hub','captured']})}
async function dreamReplay(input={}){if(!client)await init();if(!session)throw new Error('AUTH_REQUIRED');const key=input.idempotency_key||('dream-'+Date.now().toString(36));const r=await fetch(URL+'/functions/v1/naya-dream-replay',{method:'POST',headers:{'Authorization':'Bearer '+session.access_token,'apikey':KEY,'Content-Type':'application/json','x-idempotency-key':key},body:JSON.stringify({project_id:PROJECT,event_id:input.event_id||null,idempotency_key:key})});const data=await r.json().catch(()=>({}));if(!r.ok||!data.ok)throw new Error((data.error||'DREAM_REPLAY_FAILED')+(data.detail?' :: '+data.detail:''));return data.replay}
async function recordLearningEvidence(input){if(!client)await init();if(!session)throw new Error('AUTH_REQUIRED');const claim=String(input?.claim||'').trim();if(!claim)throw new Error('LEARNING_CLAIM_REQUIRED');const r=await client.from('learning_evidence').insert({member_id:session.user.id,target_id:String(input?.target_id||'nayanet-smart-note'),level:String(input?.level||'E1_UNDERSTANDS'),provenance:String(input?.provenance||'OBSERVATION'),status:'ACTIVE',claim,observed_value:input?.observed_value??{},verification_method:String(input?.verification_method||'authenticated Smart Note lifecycle'),source_event_id:input?.source_event_id||null}).select('*').single();if(r.error)throw r.error;return r.data}
async function applyLearning(input={}){if(!client)await init();if(!session)throw new Error('AUTH_REQUIRED');const r=await fetch(URL+'/functions/v1/naya-learning-apply',{method:'POST',headers:{'Authorization':'Bearer '+session.access_token,'apikey':KEY,'Content-Type':'application/json'},body:JSON.stringify({evidence_id:input.evidence_id||null,replay_id:input.replay_id||null})});const data=await r.json().catch(()=>({}));if(!r.ok||!data.ok)throw new Error((data.error||'LEARNING_APPLY_FAILED')+(data.detail?' :: '+data.detail:''));return data}
async function recordNayaDecision(input={}){if(!client)await init();if(!session)throw new Error('AUTH_REQUIRED');return record({...input,actor:'naya',source:input.source||'naya-decision-context'})}
async function decisionContext(input={}){if(!client)await init();if(!session)throw new Error('AUTH_REQUIRED');const r=await fetch(URL+'/functions/v1/naya-decision-context',{method:'POST',headers:{'Authorization':'Bearer '+session.access_token,'apikey':KEY,'Content-Type':'application/json'},body:JSON.stringify({target_id:String(input.target_id||'')})});const data=await r.json().catch(()=>({}));if(!r.ok||!data.ok)throw new Error(data.error||'DECISION_CONTEXT_FAILED');return data}
async function listLearningEvidence(){if(!client)await init();if(!session)throw new Error('AUTH_REQUIRED');const r=await client.from('learning_evidence').select('*').eq('member_id',session.user.id).order('created_at',{ascending:false}).limit(50);if(r.error)throw r.error;return r.data||[]}
async function listDreamReplays(){if(!client)await init();if(!session)throw new Error('AUTH_REQUIRED');const r=await client.from('nayanet_dream_replays').select('*').eq('user_id',session.user.id).eq('project_id',PROJECT).order('created_at',{ascending:false}).limit(50);if(r.error)throw r.error;return r.data||[]}
async function listSpaces(){if(!client)await init();if(!session)throw new Error('AUTH_REQUIRED');const r=await client.from('nayanet_spaces').select('*').eq('owner_member_id',session.user.id).order('created_at',{ascending:false}).limit(50);if(r.error)throw r.error;return r.data||[]}
async function listSmartLedger(){if(!client)await init();if(!session)throw new Error('AUTH_REQUIRED');const r=await client.from('nayanet_smart_ledger').select('ledger_event_id,event_type,event_at,created_at,source_table,source_id,parent_ledger_event_id,event_hash,privacy_classification,status,evidence_refs,verification,value,outcome,learning_refs,metadata,chain_seq').eq('owner_id',session.user.id).order('created_at',{ascending:false}).limit(50);if(r.error)throw r.error;return r.data||[]}
async function createSpace(input){if(!client)await init();if(!session)throw new Error('AUTH_REQUIRED');const name=String(input?.name||'').trim(),purpose=String(input?.purpose||'').trim();if(!name||!purpose)throw new Error('SPACE_NAME_AND_PURPOSE_REQUIRED');const r=await client.from('nayanet_spaces').insert({owner_member_id:session.user.id,name,purpose,visibility:input?.visibility==='shared'?'shared':'private'}).select('*').single();if(r.error)throw r.error;return r.data}
async function listMailThreads(){if(!client)await init();if(!session)throw new Error('AUTH_REQUIRED');const r=await client.from('v7_mail_threads').select('id,created_by,kind,subject,created_at').eq('created_by',session.user.id).order('created_at',{ascending:false}).limit(50);if(r.error)throw r.error;return r.data||[]}
window.NayaAssistantRuntime={init,signIn,signOut,record,retrieve,snapshot,captureSmartNote,dreamReplay,recordLearningEvidence,applyLearning,decisionContext,recordNayaDecision,listLearningEvidence,listDreamReplays,listSpaces,listSmartLedger,createSpace,listMailThreads};
function ui(){if(document.getElementById('naya-assistant-auth'))return;const style=document.createElement('style');style.textContent='#naya-assistant-auth{position:fixed;inset:0;z-index:1000;display:none;place-items:center;background:#000d;backdrop-filter:blur(18px);padding:18px}#naya-assistant-auth.open{display:grid}#naya-assistant-auth .box{width:min(460px,100%);padding:24px;border:2px solid #9d75ff88;border-radius:22px;background:linear-gradient(145deg,#17111f,#08080d);box-shadow:0 35px 90px #000f}#naya-assistant-auth h2{margin:0 0 6px;font-size:25px}#naya-assistant-auth p{color:#aaa4b1;font-size:10px;line-height:1.6}#naya-assistant-auth input{width:100%;margin:6px 0;padding:13px;border:2px solid #ffffff22;border-radius:11px;background:#07070a;color:#fff}#naya-assistant-auth button{min-height:40px;margin:8px 6px 0 0;padding:0 14px;border:2px solid #8b63ff66;border-radius:11px;background:#0b0a10;color:#fff;font-weight:900}#naya-assistant-auth .state{margin-top:10px;color:#9ff2bb;font-size:9px}';document.head.append(style);const m=document.createElement('div');m.id='naya-assistant-auth';m.innerHTML='<div class="box"><h2>NayaNET Member Access</h2><p>Real Supabase authentication. Authenticated sessions unlock the governed persistent intelligence boundary. No preview identity is promoted.</p><input id="naya-auth-email" type="email" autocomplete="email" placeholder="Email"><input id="naya-auth-password" type="password" autocomplete="current-password" placeholder="Password"><button id="naya-auth-signin">SIGN IN</button><button id="naya-auth-close">CLOSE</button><div class="state" id="naya-auth-state"></div></div>';document.body.append(m);modal=m;const close=()=>modal?.classList.remove('open');document.getElementById('naya-auth-close').onclick=close;document.getElementById('naya-auth-signin').onclick=async()=>{const st=document.getElementById('naya-auth-state');st.textContent='Signing in…';try{await signIn(document.getElementById('naya-auth-email').value,document.getElementById('naya-auth-password').value);st.textContent='AUTHENTICATED · SUPABASE SESSION ACTIVE';close();window.dispatchEvent(new CustomEvent('naya-auth-ready',{detail:snapshot()}))}catch(e){st.textContent='SIGN IN FAILED · '+(e?.message||'AUTH_ERROR')}};window.NayaAssistantRuntime.openAuth=()=>modal?.classList.add('open')}
ui();
window.addEventListener('load',async()=>{try{await init()}catch(e){state.persistence='error';document.documentElement.dataset.nayaAuthError='1'}window.dispatchEvent(new CustomEvent('naya-auth-state',{detail:snapshot()}))});
})();
/* NAYA HUB APPLICATION BRIDGE V1
   Preserves the canonical Hub presentation and connects its existing Personal feed
   to the authenticated cognition boundary. No replacement UI is created. */
(()=>{
  'use strict';
  const esc=(v)=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
  const textOf=(e)=>String(e?.summary||e?.content||e?.meaning||e?.title||'').trim();
  const liveId=(e)=>'naya-live-'+String(e?.event_id||e?.id||'event').replace(/[^a-zA-Z0-9_-]/g,'-');
  function liveCard(e){const title=String(e?.title||e?.event?.title||'Preserved Intelligence').trim();const summary=textOf(e).slice(0,1800);const id=liveId(e);return `<article class="block naya509-board naya-runtime-live" id="${id}" data-naya-runtime-event="${esc(e?.event_id||e?.id||'')}" style="--tone:#55e39a"><div class="blockInner"><div class="blockTop"><div class="identity"><div class="glyph" aria-hidden="true">◈</div><div><h3>${esc(title)}</h3><div class="meta"><span>PERSONAL INTELLIGENCE</span><span>RUNTIME RETRIEVED</span><span>${esc(e?.created_at||'')}</span></div></div></div><div class="truth">AUTHENTICATED · PERSISTED</div></div><div class="nutshell"><b>IN A NUTSHELL</b><p>${esc(summary||'Preserved intelligence retrieved from the authenticated cognition store.')}</p></div><div class="layers"><section class="layer" style="--layer:#55e39a"><div class="layerHead"><i class="dot"></i><b>NAYA NOTE</b><span class="state">PERSISTED</span></div><div class="layerBody">${esc(summary||'No interpretation stored.')}</div></section><section class="layer" style="--layer:#55b9ee"><div class="layerHead"><i class="dot"></i><b>MACHINE NOTE</b><span class="state">PROVENANCE</span></div><div class="layerBody">Event ID: <strong>${esc(e?.event_id||e?.id||'unknown')}</strong></div></section></div><div class="blockFoot"><span>NAYA POWER RUNTIME</span><span>LIVE RETRIEVAL · SOURCE PRESERVED</span></div></div></article>`}
  function ensureCaptureControl(){if(!window.NayaAssistantRuntime?.snapshot?.().authenticated)return;const nav=document.querySelector('.feedNav');if(!nav||document.getElementById('naya-runtime-capture'))return;if(!document.getElementById('naya-runtime-capture-style')){const s=document.createElement('style');s.id='naya-runtime-capture-style';s.textContent='.naya-runtime-capture{margin:0 22px 15px;min-height:42px;padding:0 15px;border:2px solid #9d75ff88;border-radius:12px;background:linear-gradient(145deg,#181021,#09080d);color:#fff;font-size:8px;font-weight:1000;letter-spacing:.08em;box-shadow:inset 0 1px #fff4,0 12px 25px #0008,0 0 24px #9d75ff18}.naya-runtime-capture:hover{border-color:#d86cff;transform:translateY(-1px)}#naya-runtime-capture-modal{position:fixed;inset:0;z-index:1100;display:none;place-items:center;background:#000d;backdrop-filter:blur(18px);padding:18px}#naya-runtime-capture-modal.open{display:grid}#naya-runtime-capture-modal .box{width:min(680px,100%);padding:24px;border:2px solid #9d75ff88;border-radius:22px;background:linear-gradient(145deg,#17111f,#08080d);box-shadow:0 35px 90px #000f}#naya-runtime-capture-modal input,#naya-runtime-capture-modal textarea{width:100%;margin:7px 0;padding:13px;border:2px solid #ffffff22;border-radius:11px;background:#07070a;color:#fff}#naya-runtime-capture-modal textarea{min-height:180px;resize:vertical}#naya-runtime-capture-modal .actions{display:flex;gap:8px;margin-top:8px}#naya-runtime-capture-modal button{min-height:42px;padding:0 15px;border:2px solid #8b63ff66;border-radius:11px;background:#0b0a10;color:#fff;font-weight:900}#naya-runtime-capture-modal .state{margin-top:10px;color:#9ff2bb;font-size:9px;min-height:14px}';document.head.append(s)}const b=document.createElement('button');b.id='naya-runtime-capture';b.className='naya-runtime-capture';b.type='button';b.textContent='＋ CAPTURE SMART NOTE';b.onclick=openCaptureModal;nav.after(b)}
  function openCaptureModal(){if(!window.NayaAssistantRuntime?.snapshot?.().authenticated){window.NayaAssistantRuntime?.openAuth?.();return}let m=document.getElementById('naya-runtime-capture-modal');if(!m){m=document.createElement('div');m.id='naya-runtime-capture-modal';m.innerHTML='<div class="box"><h2 style="margin:0 0 5px">CAPTURE SMART NOTE</h2><p style="color:#aaa4b1;font-size:10px;line-height:1.6">Turn this meaningful intelligence into durable Personal Intelligence. The capture is authenticated, persisted, receipt-backed, and idempotent by content.</p><input id="naya-runtime-note-title" placeholder="Title"><textarea id="naya-runtime-note-content" placeholder="What should Naya remember, connect, learn, and reuse?"></textarea><div class="actions"><button id="naya-runtime-note-save">CAPTURE & PERSIST</button><button id="naya-runtime-note-close">CLOSE</button></div><div class="state" id="naya-runtime-note-state"></div></div>';document.body.append(m);m.querySelector('#naya-runtime-note-close').onclick=()=>m.classList.remove('open');m.querySelector('#naya-runtime-note-save').onclick=async()=>{const st=m.querySelector('#naya-runtime-note-state'),title=m.querySelector('#naya-runtime-note-title').value.trim(),content=m.querySelector('#naya-runtime-note-content').value.trim();if(!title||!content){st.textContent='TITLE AND CONTENT REQUIRED';return}st.textContent='Persisting…';try{const r=await window.NayaAssistantRuntime.captureSmartNote({title,content,metadata:{capture_surface:'NayaNET Intelligent Hub',continuity:'conversation-to-compounding-intelligence'}});st.textContent='✓ CAPTURED · PERSISTED · RECEIPT '+String(r?.receipt?.id||r?.receipt_id||'RECORDED');m.querySelector('#naya-runtime-note-title').value='';m.querySelector('#naya-runtime-note-content').value='';await loadPersonal()}catch(e){st.textContent='CAPTURE FAILED · '+(e?.message||'RUNTIME_ERROR')}}}m.classList.add('open');m.querySelector('#naya-runtime-note-title').focus()}
  async function loadPersonal(){try{if(!window.NayaAssistantRuntime?.snapshot||!window.NayaAssistantRuntime?.retrieve)return;const snap=window.NayaAssistantRuntime.snapshot();if(!snap.authenticated)return;const events=await window.NayaAssistantRuntime.retrieve();const blocks=document.getElementById('blocks');if(!blocks)return;blocks.querySelectorAll('.naya-runtime-live').forEach(x=>x.remove());const relevant=(events||[]).filter(e=>String(e?.project_id||e?.project||'NayaNET')==='NayaNET').slice(0,20);if(relevant.length)blocks.insertAdjacentHTML('afterbegin',relevant.map(liveCard).join(''));const count=document.getElementById('feedCount');if(count)count.textContent=(relevant.length||0)+' LIVE + CANONICAL INTELLIGENCE';const title=document.getElementById('feedTitle');if(title)title.textContent='Personal Intelligence';const desc=document.getElementById('feedDesc');if(desc)desc.textContent='Authenticated intelligence retrieved from the governed NayaNET cognition boundary.'}catch(err){document.documentElement.dataset.nayaRuntimeFeedError='1'}}
  window.NayaAssistantRuntime&&(window.NayaAssistantRuntime.loadPersonalIntelligence=loadPersonal);
  function wire(){document.addEventListener('click',(event)=>{const feed=event.target.closest('[data-feed="personal"]');if(feed)setTimeout(()=>{ensureCaptureControl();loadPersonal()},0)},true);window.addEventListener('naya-auth-state',(event)=>{if(event.detail?.authenticated)setTimeout(loadPersonal,50)});window.addEventListener('naya-auth-ready',()=>setTimeout(()=>{ensureCaptureControl();loadPersonal()},50));if(document.documentElement.dataset.nayaAuth==='authenticated')setTimeout(loadPersonal,50)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire,{once:true});else wire();
})();
/* NAYANET NAME-FIRST AUTH OVERRIDE — one canonical adapter, no email/password UI. */
(()=>{
  'use strict';
  const loadAdapter=()=>new Promise((resolve,reject)=>{if(window.NayaNETNameFirstAuth)return resolve();const existing=document.querySelector('script[data-nayanet-name-first]');if(existing){existing.addEventListener('load',resolve,{once:true});existing.addEventListener('error',reject,{once:true});return}const s=document.createElement('script');s.src='/NAYANET/name-first-auth-adapter.js';s.dataset.nayanetNameFirst='true';s.onload=resolve;s.onerror=()=>reject(new Error('IDENTITY_ADAPTER_NOT_LOADED'));document.head.append(s)});
  const apply=async()=>{const rt=window.NayaAssistantRuntime;if(!rt)return;rt.signIn=async()=>{throw new Error('EMAIL_PASSWORD_AUTH_DISABLED')};rt.openAuth=()=>{location.assign('/identity.html')};document.getElementById('naya-assistant-auth')?.remove();const snap=await rt.init();if(!snap?.authenticated){location.replace('https://welcome.nayanet.app');return;}};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>apply().catch(()=>{}),{once:true});else apply().catch(()=>{});
})();


/* NAYA POWER RECEIVER READINESS V1 — canonical event-chain projections.
   Uses the existing authenticated nayanet_cognition_events boundary only.
   No parallel identity, persistence, ledger, or cognition store is created.
   Dream is deterministic replay/synthesis of preserved verified intelligence;
   it does not claim model-weight self-improvement. */
(()=>{
 'use strict';
 const R=()=>window.NayaAssistantRuntime;
 const now=()=>new Date().toISOString();
 const safe=(v)=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
 const uid=(p)=>p+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7);
 async function ensure(){if(!R())throw Error('RUNTIME_UNAVAILABLE');const s=await R().init();if(!s?.authenticated)throw Error('AUTH_REQUIRED');return s}
 async function events(){await ensure();return R().retrieve()}
 async function write(stage,source,content,meta={}){
   const id=uid('naya-'+stage.toLowerCase());
   return R().record({event_id:id,title:'Naya Power '+stage,content,source:'nayanet-receiver-readiness',status:'active',tags:['naya-power','receiver-readiness',stage.toLowerCase()],metadata:{stage,source,created_at:now(),...meta},verification:{state:stage==='VERIFY'?'VERIFIED':'PENDING'}});
 }
 async function learn(note){
   const text=String(note?.content||note?.summary||note?.title||'').trim();
   if(!text)throw Error('LEARNING_SOURCE_REQUIRED');
   const sourceId=note.event_id||note.id||'smart-note';
   const evidence=await R().recordLearningEvidence({target_id:sourceId,level:'E1_UNDERSTANDS',provenance:'OBSERVATION',claim:'Preserved Smart Note is available as reusable learning evidence.',observed_value:{title:note.title||null,content:text.slice(0,1200)},verification_method:'authenticated Smart Note persistence and retrieval',source_event_id:sourceId});
   const event=await write('LEARN',sourceId,`Learned from preserved Smart Note: ${text.slice(0,1800)}`,{source_event_id:sourceId,learning_state:'OBSERVED',evidence_state:'RUNTIME-PROVEN',learning_evidence_id:evidence.id});
   return {event,evidence};
 }
 async function dream(){await ensure();const replay=await R().dreamReplay({});return replay}
 async function apply(sourceId){
   const all=await events();const source=sourceId?all.find(e=>e.event_id===sourceId):all.find(e=>!['LEARN','DREAM','APPLY','VERIFY'].includes(String(e?.metadata?.stage||'').toUpperCase()));
   if(!source)throw Error('APPLICATION_SOURCE_REQUIRED');
   return write('APPLY',source.event_id,`Application recorded for preserved intelligence: ${source.title||source.event_id}.\n${String(source.content||'').slice(0,1200)}`,{source_event_id:source.event_id,application_state:'REQUESTED'});
 }
 async function verify(sourceId){
   const all=await events();const candidates=all.filter(e=>String(e?.metadata?.stage||'').toUpperCase()==='APPLY' || e.event_id===sourceId);
   if(!candidates.length)throw Error('NO_APPLICATION_TO_VERIFY');
   const source=candidates[0];
   return write('VERIFY',source.event_id,`Verification checkpoint recorded for application ${source.event_id}. The event is persisted in the canonical cognition boundary; downstream success must be established by observed evidence before being promoted beyond this checkpoint.`,{source_event_id:source.event_id,verification_state:'VERIFIED',evidence_state:'RUNTIME-PROVEN'});
 }
 function style(){
   if(document.getElementById('naya-receiver-module-style'))return;
   const s=document.createElement('style');s.id='naya-receiver-module-style';s.textContent='.naya-receiver-panel{margin:0 22px 20px;padding:20px;border:2px solid #8b63ff55;border-radius:18px;background:linear-gradient(145deg,#14101b,#08080d);box-shadow:inset 0 1px #fff3,0 18px 38px #0009}.naya-receiver-panel h2{margin:0 0 5px;font-size:25px}.naya-receiver-panel p{color:#aaa4b1;font-size:10px;line-height:1.6}.naya-receiver-actions{display:flex;flex-wrap:wrap;gap:8px;margin:14px 0}.naya-receiver-actions button{min-height:40px;padding:0 14px;border:2px solid #8b63ff66;border-radius:11px;background:linear-gradient(145deg,#17111f,#08080d);color:#fff;font-size:8px;font-weight:1000;letter-spacing:.06em}.naya-receiver-state{padding:12px;border:1px solid #ffffff15;border-radius:12px;color:#cfc9d6;font-size:9px;white-space:pre-wrap;line-height:1.55}.naya-score{display:inline-flex;margin-left:8px;padding:4px 7px;border-radius:999px;border:1px solid #55e39a55;color:#bfffd8;font-size:7px;font-weight:1000}.naya-module-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:12px}.naya-module-card{padding:14px;border:1px solid #ffffff16;border-radius:13px;background:#09090d}.naya-module-card b{font-size:9px}.naya-module-card span{display:block;margin-top:5px;color:#9f98a7;font-size:8px;line-height:1.5}@media(max-width:700px){.naya-module-grid{grid-template-columns:1fr}}';document.head.append(s)
 }
 function panel(title,desc){
   style();let p=document.getElementById('naya-receiver-panel');if(!p){p=document.createElement('section');p.id='naya-receiver-panel';p.className='naya-receiver-panel';const hero=document.querySelector('.hero');(hero?.parentElement||document.body).insertBefore(p,document.getElementById('searchSection')||hero?.nextSibling||null)}p.innerHTML='<h2>'+safe(title)+'</h2><p>'+safe(desc)+'</p><div class="naya-receiver-actions"></div><div class="naya-module-grid"></div><div class="naya-receiver-state">Ready to operate on the canonical authenticated cognition boundary.</div>';return p
 }
 function button(parent,label,fn){const b=document.createElement('button');b.textContent=label;b.onclick=async()=>{const st=parent.querySelector('.naya-receiver-state');st.textContent='Working…';try{const r=await fn();st.textContent='PASS · '+JSON.stringify(r?.event_id?{event_id:r.event_id}:r,null,2)}catch(e){st.textContent='BLOCKED/FAILED · '+(e?.message||e)} };parent.querySelector('.naya-receiver-actions').append(b)}
 async function showToday(){const p=panel('Intelligence Today','Authenticated projection of today’s preserved intelligence.');const all=await events();const day=new Date().toISOString().slice(0,10);const rows=all.filter(e=>String(e.created_at||'').slice(0,10)===day).slice(0,20);p.querySelector('.naya-receiver-state').textContent=rows.length?rows.map(e=>'- '+(e.title||'Intelligence')+': '+String(e.content||'').slice(0,220)).join('\n'):'No preserved intelligence has been recorded today.'}
 async function showLedger(){const p=panel('Smart Ledger','Live evidence/integrity projection from the canonical Smart Ledger. This is not a second event store.');const rows=await R().listSmartLedger();const g=p.querySelector('.naya-module-grid');[['BACKEND','nayanet_smart_ledger'],['OWNER','Authenticated member'],['EVENTS',String(rows.length)],['BOUNDARY','Owner-scoped · read projection']].forEach(x=>{const d=document.createElement('div');d.className='naya-module-card';d.innerHTML='<b>'+safe(x[0])+'</b><span>'+safe(x[1])+'</span>';g.append(d)});p.querySelector('.naya-receiver-state').textContent=rows.length?rows.map((x,i)=>{const v=x.verification||{},val=x.value||{},out=x.outcome||{};return (i+1)+'. '+(x.event_type||'event')+' · '+(x.status||'UNKNOWN')+' · '+(x.event_at||x.created_at||'')+'\\n   source: '+(x.source_table||'unknown')+':'+(x.source_id||'unknown')+'\\n   verification: '+(v.status||'not-qualified')+' · value: '+(val.value_score??val.score??'not-calculated')+' · outcome: '+(out.status||out.state||'not-recorded')+'\\n   evidence: '+JSON.stringify(x.evidence_refs||[]) }).join('\\n\\n'):'Smart Ledger is connected; no ledger events exist for this member yet.'} async function showMail(){const p=panel('Smart Mail','Live projection of the existing NayaNET mail contract.');const rows=await R().listMailThreads();const g=p.querySelector('.naya-module-grid');[['BACKEND','v7_mail_threads + v7_mail_messages'],['OWNER','Authenticated member'],['THREADS',String(rows.length)],['STATE',rows.length?'LIVE DATA':'READY · NO THREADS YET']].forEach(x=>{const d=document.createElement('div');d.className='naya-module-card';d.innerHTML='<b>'+safe(x[0])+'</b><span>'+safe(x[1])+'</span>';g.append(d)});p.querySelector('.naya-receiver-state').textContent=rows.length?rows.map(x=>'• '+(x.subject||'Untitled')+' · '+x.kind+' · '+x.created_at).join('\\n'):'Mail backend is connected; no threads exist for this member yet.';}
 async function showSpaces(){const p=panel('Smart Spaces','Live projection of the existing permissioned NayaNET Smart Space backend.');const rows=await R().listSpaces();button(p,'CREATE PRIVATE SPACE',async()=>{const name=prompt('Space name');const purpose=prompt('What is this space for?');return R().createSpace({name,purpose,visibility:'private'})});const g=p.querySelector('.naya-module-grid');[['BACKEND','nayanet_spaces'],['OWNER','Authenticated member'],['SPACES',String(rows.length)],['DEFAULT VISIBILITY','PRIVATE']].forEach(x=>{const d=document.createElement('div');d.className='naya-module-card';d.innerHTML='<b>'+safe(x[0])+'</b><span>'+safe(x[1])+'</span>';g.append(d)});p.querySelector('.naya-receiver-state').textContent=rows.length?rows.map(x=>'• '+x.name+' · '+x.visibility+' · '+x.purpose).join('\\n'):'Smart Spaces backend is connected; no spaces exist for this member yet.';}
 async function showIntelligence(){const p=panel('Intelligence','Canonical intelligence retrieved from the authenticated cognition boundary.');const all=await events();p.querySelector('.naya-receiver-state').textContent=all.slice(0,20).map(e=>'• '+(e.title||'Intelligence')+' · '+String(e.content||'').slice(0,260)).join('\n')||'No intelligence yet.'}
 async function showActivity(){const p=panel('Activity','Activity projection derived from canonical cognition events.');const all=await events();p.querySelector('.naya-receiver-state').textContent=all.slice(0,30).map(e=>'• '+(e.created_at||'')+' · '+(e.title||e.event_id||'event')+' · '+(e.status||'')).join('\n')||'No activity yet.'}
 async function showFlow(){const p=panel('Learn → Dream → Apply → Verify','Receiver-ready intelligence loop over the canonical event store.');button(p,'LEARN LATEST',async()=>{const all=await events();const n=all.find(e=>!['LEARN','DREAM','APPLY','VERIFY'].includes(String(e?.metadata?.stage||'').toUpperCase()));if(!n)throw Error('NO_SMART_NOTE');return learn(n)});button(p,'DREAM REPLAY',dream);button(p,'APPLY LATEST',()=>apply());button(p,'VERIFY APPLICATION',()=>verify());const g=p.querySelector('.naya-module-grid');[['SOURCE','Smart Note / canonical event'],['LEARN','Durable learning event'],['DREAM','Deterministic replay of preserved intelligence'],['APPLY','Authorized application intent'],['VERIFY','Observed-evidence checkpoint']].forEach(x=>{const d=document.createElement('div');d.className='naya-module-card';d.innerHTML='<b>'+safe(x[0])+'</b><span>'+safe(x[1])+'</span>';g.append(d)})}
 function wire(){
   document.addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(!b)return;const page=b.dataset.page;const map={home:showToday,notes:async()=>showFlow(),reports:showToday,intelligence:showIntelligence,collective:showActivity,evidence:showLedger,connections:showSpaces,mail:showMail,settings:async()=>{panel('Settings','Runtime configuration and truthful connection state.')}};if(map[page]){e.preventDefault();Promise.resolve(map[page]()).catch(err=>{const p=document.getElementById('naya-receiver-panel');if(p)p.querySelector('.naya-receiver-state').textContent='BLOCKED/FAILED · '+(err?.message||err)})}},true);
   window.NayaReceiverReadiness={learn,dream,apply,verify,showToday,showLedger,showMail,showSpaces,showIntelligence,showActivity,showFlow};
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire,{once:true});else wire();
})();
