(()=>{'use strict';
const css=()=>{if(document.getElementById('naya-smart-tabs-style'))return;const s=document.createElement('style');s.id='naya-smart-tabs-style';s.textContent=`
#naya-smart-tabs{margin:0 22px 18px;padding:14px;border:1px solid #ffffff16;border-radius:18px;background:#08080c;box-shadow:inset 0 1px #fff3,0 18px 40px #0009}
#naya-smart-tabs .st-head{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:10px}
#naya-smart-tabs .st-head b{font-size:8px;letter-spacing:.16em}.st-head span{font-size:7px;color:#8f8798}
#naya-smart-tabs .st-list{display:flex;gap:7px;flex-wrap:wrap;align-items:center}
#naya-smart-tabs .st-tab{display:flex;align-items:center;gap:4px;padding:3px;border:1px solid #ffffff12;border-radius:13px;background:#0b0a10;box-shadow:0 8px 18px #0008}
#naya-smart-tabs button{min-height:32px;padding:0 9px;border:1px solid #8b63ff55;border-radius:9px;background:linear-gradient(145deg,#15111d,#08080c);color:#eeeaf2;font-size:8px;font-weight:1000;letter-spacing:.04em;box-shadow:inset 0 1px #fff3}
#naya-smart-tabs button:hover{transform:translateY(-1px);border-color:#d86cff}.fav{border-color:#e8c76688!important}.st-actions{display:flex;gap:3px}.st-actions button{min-width:28px;padding:0 6px;font-size:10px}
.st-empty{color:#8f8798;font-size:8px;padding:7px 0}.st-add{border-color:#55e39a77!important}.st-state{margin-top:8px;color:#9f98a7;font-size:7px;min-height:12px}
@media(max-width:700px){#naya-smart-tabs{margin:0 14px 14px}.st-list{overflow:auto;flex-wrap:nowrap!important;padding-bottom:3px}.st-tab{flex:0 0 auto}}
`;document.head.append(s)};
const state={root:null,tabs:[]};
async function load(){css();if(!window.NayaAssistantRuntime)return;const snap=await window.NayaAssistantRuntime.init();let root=document.getElementById('naya-smart-tabs');if(!root){root=document.createElement('section');root.id='naya-smart-tabs';const anchor=document.querySelector('.ecosystem');if(anchor?.parentElement)anchor.parentElement.insertBefore(root,anchor.nextSibling);else document.body.prepend(root)}state.root=root;root.innerHTML='<div class="st-head"><b>SMART TABS · YOUR NAVIGATION</b><span id="st-auth">CHECKING AUTHORITY…</span></div><div class="st-list" id="st-list"></div><div class="st-state" id="st-state"></div>';if(!snap.authenticated){root.querySelector('#st-auth').textContent='AUTHENTICATION REQUIRED';root.querySelector('#st-state').textContent='Private navigation is not exposed without an authenticated session.';return}root.querySelector('#st-auth').textContent='AUTHENTICATED · PRIVATE';await render()}
async function render(){const list=state.root.querySelector('#st-list'),out=state.root.querySelector('#st-state');try{const r=await window.NayaAssistantRuntime.listSmartTabs();state.tabs=r.tabs||[];list.innerHTML='';if(!state.tabs.length)list.innerHTML='<span class="st-empty">No Smart Tabs yet. Add one to persist a private destination.</span>';state.tabs.forEach(t=>{const wrap=document.createElement('div');wrap.className='st-tab';const b=document.createElement('button');b.className=t.favorite?'fav':'';b.textContent=(t.favorite?'★ ':'')+t.label;b.title=t.target;b.onclick=()=>resolve(t);wrap.append(b);const a=document.createElement('div');a.className='st-actions';[['↑',()=>move(t,-1)],['↓',()=>move(t,1)],['✎',()=>edit(t)],['☆',()=>toggleFavorite(t)],['×',()=>remove(t)]].forEach(([label,fn])=>{const x=document.createElement('button');x.textContent=label;x.title=label==='✎'?'Edit':label==='×'?'Delete':label==='☆'?'Favorite':label==='↑'?'Move up':'Move down';x.onclick=fn;a.append(x)});wrap.append(a);list.append(wrap)});const add=document.createElement('button');add.className='st-add';add.textContent='＋ ADD TAB';add.onclick=addTab;list.append(add);out.textContent=state.tabs.length?state.tabs.length+' PRIVATE TAB'+(state.tabs.length===1?'':'S')+' · OWNER-SCOPED · PERSISTENT':'Ready · no tabs'}catch(e){out.textContent='SMART TABS FAILED · '+(e?.message||e)}}
function setState(v){state.root.querySelector('#st-state').textContent=v}
async function addTab(){const label=prompt('Tab label');if(!label)return;const target=prompt('Target route or URL','/feed');if(!target)return;setState('Persisting…');try{await window.NayaAssistantRuntime.createSmartTab({label,target,target_type:/^https?:\/\//i.test(target)?'url':'route',position:state.tabs.length});setState('TAB CREATED · PERSISTED · RELOADING');await render()}catch(e){setState('CREATE FAILED · '+(e?.message||e))}}
async function edit(t){const label=prompt('Tab label',t.label);if(!label)return;const target=prompt('Target route or URL',t.target);if(!target)return;setState('Updating…');try{await window.NayaAssistantRuntime.updateSmartTab({id:t.id,label,target,target_type:/^https?:\/\//i.test(target)?'url':t.target_type});setState('TAB UPDATED · PERSISTED · RELOADING');await render()}catch(e){setState('UPDATE FAILED · '+(e?.message||e))}}
async function toggleFavorite(t){setState('Saving favorite…');try{await window.NayaAssistantRuntime.updateSmartTab({id:t.id,favorite:!t.favorite});setState('FAVORITE '+(!t.favorite?'ON':'OFF')+' · PERSISTED');await render()}catch(e){setState('FAVORITE FAILED · '+(e?.message||e))}}
async function move(t,d){const i=state.tabs.findIndex(x=>x.id===t.id),j=i+d;if(i<0||j<0||j>=state.tabs.length)return;setState('Reordering…');try{await Promise.all([window.NayaAssistantRuntime.updateSmartTab({id:state.tabs[i].id,position:j}),window.NayaAssistantRuntime.updateSmartTab({id:state.tabs[j].id,position:i})]);setState('ORDER PERSISTED · RELOADING');await render()}catch(e){setState('REORDER FAILED · '+(e?.message||e))}}
async function remove(t){if(!confirm('Delete Smart Tab “'+t.label+'”? This does not delete intelligence.'))return;setState('Deleting tab only…');try{await window.NayaAssistantRuntime.deleteSmartTab(t.id);setState('TAB DELETED · INTELLIGENCE UNCHANGED · RELOADING');await render()}catch(e){setState('DELETE FAILED · '+(e?.message||e))}}
function resolve(t){if(t.target_type==='url')location.assign(t.target);else if(t.target.startsWith('/'))location.assign(t.target);else if(t.target.startsWith('#'))location.hash=t.target.slice(1);else location.assign('/'+t.target.replace(/^\//,''))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>load().catch(()=>{}),{once:true});else load().catch(()=>{});window.addEventListener('naya-auth-ready',()=>load().catch(()=>{}));
})();