import { useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import { useIdentity } from '../identity/session';
import { routes } from './routes';

type ShellProps={children:(path:string)=>ReactNode};
const groups:[string,[string,string,string][]][]=[['CORE',[['Home',routes.home,'⌂'],['Smart Feed',routes.feed,'✦'],['Smart Notes',routes.notes,'◈'],['Today',routes.today,'◷']]],['INTELLIGENCE',[['Reports',routes.reports,'▤'],['Library',routes.library,'▦'],['Collective',routes.collective,'◎'],['Evidence',routes.evidence,'◉'],['Connections',routes.connections,'↔']]],['CONNECT',[['Smart Mail',routes.mail,'✉'],['Smart Space',routes.space,'◌']]]];
const normalize=(p:string)=>p.length>1&&p.endsWith('/')?p.slice(0,-1):p||'/';
export function AppShellV3({children}:ShellProps){const id=useIdentity();const[path,setPath]=useState(()=>normalize(window.location.pathname));const[query,setQuery]=useState('');useEffect(()=>{const f=()=>setPath(normalize(window.location.pathname));addEventListener('popstate',f);return()=>removeEventListener('popstate',f)},[]);const go=(p:string)=>{if(p===path)return;history.pushState({},'',p);setPath(p)};const submit=()=>{if(!query.trim())return;go(routes.feed);dispatchEvent(new CustomEvent('nayanet:search',{detail:{query:query.trim()}}))};const current=groups.flatMap(g=>g[1]).find(x=>x[1]===path);const label=current?.[0]||(path===routes.settings?'Settings':'NayaNET');return <div className="app" data-shell-owner="AppShellV3" data-route={path} data-runtime-marker="NAYANET-HUB-REACT-CANONICAL"><aside className="sidebar"><button className="brand" onClick={()=>go(routes.home)}><span className="logo"><span>✦</span></span><span className="brand-copy"><b>NayaNET</b><small>INTELLIGENT HUB</small></span></button><div className="side-context"><span className="online-dot"/><span><b>NAYA IS READY</b><small>Private intelligence workspace</small></span></div>{groups.map(([title,items])=><div className="nav-section" key={title}><span>{title}</span>{items.map(([name,route,icon])=><button key={route} className={`nav-item ${path===route?'active':''}`} onClick={()=>go(route)}><span className="nav-icon">{icon}</span><span className="nav-name">{name}</span>{path===route&&<i className="nav-active-dot"/>}</button>)}</div>)}<div className="sidebar-spacer"/><div className="side-metrics"><div><strong>∞</strong><span>Continuity</span></div><div><strong>100%</strong><span>Private</span></div></div><button className={`settings-link ${path===routes.settings?'active':''}`} onClick={()=>go(routes.settings)}><span className="nav-icon">⚙</span><span>Settings</span></button></aside><main className="main"><header className="topbar"><div className="top-context"><span className="top-eyebrow">NAYANET</span><span className="top-divider"/><strong>{label}</strong></div><div className="universal-search"><span className="search-icon">⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')submit()}} placeholder="Search anything — or talk to Naya…" aria-label="Search or talk to Naya"/><span className="search-hint">⌘ K</span><button className="talk-button" onClick={submit}>✦ TALK TO NAYA</button></div><div className="top-actions"><button className="top-action" onClick={()=>go(routes.notes)}>＋ <span>New Note</span></button><button className="identity-chip" onClick={()=>go(routes.settings)}><span className="identity-avatar">{(id.smart_name||'N').slice(0,1).toUpperCase()}</span><span className="identity-copy"><b>{id.smart_name}</b><small>@{id.smart_alias}</small></span></button></div></header><section className="home">{children(path)}</section></main></div>}
