import { useEffect, useState } from 'react';
import { useIdentity } from '../identity/session';

type Connection={id:string;connected_member_id:string;status:string;source_type?:string;source_space_id?:string;created_at:string;updated_at:string};

export function ConnectionsSurface(){
 const identity=useIdentity(); const [rows,setRows]=useState<Connection[]>([]); const [busy,setBusy]=useState(true); const [acting,setActing]=useState(''); const [status,setStatus]=useState('');
 const load=async()=>{setBusy(true);setStatus('');try{const rt=window.NayaAssistantRuntime;if(!rt)throw new Error('ASSISTANT_RUNTIME_UNAVAILABLE');if(!rt.snapshot()?.authenticated)throw new Error('AUTH_REQUIRED');setRows((await rt.listConnections()) as Connection[])}catch(e){setRows([]);setStatus(e instanceof Error?e.message:'CONNECTIONS_LOAD_FAILED')}finally{setBusy(false)}};
 useEffect(()=>{if(!identity.is_authenticated){setRows([]);setBusy(false);return}void load()},[identity.is_authenticated]);
 const revoke=async(row:Connection)=>{setActing(row.id);setStatus('REVOKING THROUGH CANONICAL RELATIONSHIP BOUNDARY…');try{const rt=window.NayaAssistantRuntime;if(!rt)throw new Error('ASSISTANT_RUNTIME_UNAVAILABLE');await rt.revokeConnection(row.connected_member_id);setStatus('CONNECTION REVOKED · '+row.connected_member_id);await load()}catch(e){setStatus('CONNECTION REVOKE BLOCKED · '+(e instanceof Error?e.message:'REVOKE_FAILED'))}finally{setActing('')}};
 if(!identity.is_authenticated)return <section className="feature-surface" data-surface="connections"><div className="feature-hero"><div><div className="eyebrow">NAYANET · PEOPLE · RELATIONSHIPS · TRUST</div><h1>Your Connections</h1><p>Permissioned relationships available to this identity.</p></div></div><div className="feature-empty"><b>AUTHENTICATION REQUIRED</b><span>Connections are private to the authenticated member.</span></div></section>;
 return <section className="feature-surface" data-surface="connections"><div className="feature-hero"><div><div className="eyebrow">NAYANET · PEOPLE · RELATIONSHIPS · TRUST</div><h1>Your Connections</h1><p>See, inspect, and deliberately revoke the relationships this identity has created.</p></div><div className="feature-state">AUTHENTICATED · {rows.length} CONNECTIONS</div></div><div className="feature-toolbar"><button onClick={()=>void load()} disabled={busy||!!acting}>↻ REFRESH</button><span>{rows.length} CANONICAL RELATIONSHIPS</span></div>{status&&<div className="feature-status" role="status">{status}</div>}{busy?<div className="feature-empty"><b>READING CANONICAL CONNECTIONS…</b><span>Loading the authenticated relationship boundary.</span></div>:rows.length?<div className="connection-room-grid">{rows.map(row=><article className="connection-room-card" key={row.id}><div><span className="feature-card-kicker">CONNECTION · {row.status.toUpperCase()}</span><h2>{row.connected_member_id}</h2><p>Source: {row.source_type||'canonical relationship'}{row.source_space_id?' · Space '+row.source_space_id:''}</p></div><div className="connection-room-meta"><span>CREATED · {new Date(row.created_at).toLocaleString()}</span><span>UPDATED · {new Date(row.updated_at).toLocaleString()}</span></div><button onClick={()=>void revoke(row)} disabled={!!acting}>{acting===row.id?'REVOKING…':'REVOKE CONNECTION'}</button></article>)}</div>:<div className="feature-empty"><b>NO ACTIVE CONNECTIONS</b><span>Create a relationship from a consented shared Space when one is available.</span></div>}<div className="feature-foot"><span>AUTHORITY</span><b>CONNECTION ≠ PERMISSION</b><span>•</span><span>PRIVATE BY DEFAULT · SHARED BY CHOICE</span></div></section>;
}
