import { useState } from 'react';
import { useIdentity } from '../identity/session';

export function SmartNoteSurface(){
 const identity=useIdentity();const[title,setTitle]=useState('');const[content,setContent]=useState('');const[busy,setBusy]=useState(false);const[status,setStatus]=useState('');
 const capture=async()=>{if(!title.trim()||!content.trim())return;setBusy(true);setStatus('CAPTURING THROUGH THE CANONICAL SMART NOTE PIPELINE…');try{const rt=window.NayaAssistantRuntime;if(!rt?.captureSmartNote)throw new Error('SMART_NOTE_RUNTIME_UNAVAILABLE');if(!rt.snapshot()?.authenticated)throw new Error('AUTH_REQUIRED');const result=await rt.captureSmartNote({title:title.trim(),content:content.trim(),source:'nayanet-hub.smart-note'});if(result?.ok!==true||result?.error||!['completed','replayed'].includes(String(result?.pipeline||'')))throw new Error('SMART_NOTE_RECEIVER_PIPELINE_FAILED');const learning=result?.transaction?.learning_evidence,checkpoint=result?.transaction?.intelligence_checkpoint;if(result?.pipeline==='completed'&&(!learning?.id||checkpoint?.status!=='CHECKPOINT_VERIFIED'))throw new Error('SMART_NOTE_LEARNING_CHECKPOINT_INCOMPLETE');const eventId=String(result?.event?.event_id||result?.transaction?.evidence?.event_id||'');const receiptId=String(result?.receipt?.receipt_id||result?.receipt?.id||result?.transaction?.evidence?.receipt_id||'');if(!eventId||!receiptId)throw new Error('SMART_NOTE_CANONICAL_RECEIPT_INCOMPLETE');const retrieved=await rt.retrieve(eventId);const found=Array.isArray(retrieved)&&retrieved.some(event=>event.event_id===eventId);if(!found)throw new Error('SMART_NOTE_RETRIEVAL_VERIFICATION_FAILED');setStatus('CAPTURED · PERSISTED · RETRIEVED · VERIFIED · EVENT '+eventId+' · RECEIPT '+receiptId);setTitle('');setContent('')}catch(e){setStatus('SMART NOTE BLOCKED · '+(e instanceof Error?e.message:'SMART_NOTE_FAILED'))}finally{setBusy(false)}};
 if(!identity.is_authenticated)return <section className="feature-surface" data-surface="smart-note"><div className="feature-hero"><div><div className="eyebrow">NAYANET · CAPTURE · CANONICALIZE · COMPOUND</div><h1>Smart Note</h1><p>Capture an experience or insight so the intelligence engine can preserve and compound it.</p></div></div><div className="feature-empty"><b>AUTHENTICATION REQUIRED</b><span>Smart Notes enter the private intelligence boundary only from an authenticated identity.</span></div></section>;
 return <section className="feature-surface" data-surface="smart-note"><div className="feature-hero"><div><div className="eyebrow">NAYANET · CAPTURE · CANONICALIZE · COMPOUND</div><h1>Smart Note</h1><p>Think once. Capture it. Let Naya turn the experience into durable intelligence.</p></div><div className="feature-state">AUTHENTICATED · CANONICAL PIPELINE</div></div><div className="smart-note-compose"><label>TITLE<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="What did you learn?" maxLength={240}/></label><label>INTELLIGENCE<textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="Capture the experience, discovery, mistake, insight, or lesson…" rows={12}/></label><div className="smart-note-law">CAPTURE → CANONICALIZE → STRUCTURE → LEARN → PRESERVE → RETRIEVE → APPLY → VERIFY → COMPOUND</div><button onClick={()=>void capture()} disabled={busy||!title.trim()||!content.trim()}>{busy?'CAPTURING + VERIFYING…':'✦ CAPTURE SMART NOTE'}</button></div>{status&&<div className="feature-status" role="status">{status}</div>}<div className="feature-foot"><span>TRUTH</span><b>A NOTE EXISTING DOES NOT PROVE LEARNING</b><span>•</span><span>RETRIEVAL IS VERIFIED BEFORE CLAIMING SUCCESS</span></div></section>;
}
