import { useEffect, useState } from 'react';
import { SUPABASE_URL } from '../config/supabase';
import { supabase, useIdentity } from '../identity/session';

type Row = Record<string, unknown>;
const endpoint = `${SUPABASE_URL}/functions/v1/nayanet-smart-mail`;
const short = (v: unknown) => { const s=String(v||''); return s.length>18 ? `${s.slice(0,8)}…${s.slice(-6)}` : s; };

export function SmartMailSurface(){
 const id=useIdentity(); const [messages,setMessages]=useState<Row[]>([]); const [threads,setThreads]=useState<Row[]>([]); const [recipients,setRecipients]=useState<Row[]>([]); const [grants,setGrants]=useState<Row[]>([]); const [recipient,setRecipient]=useState(''); const [grant,setGrant]=useState(''); const [subject,setSubject]=useState('NayaNET communication'); const [body,setBody]=useState(''); const [status,setStatus]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
 const load=async()=>{ if(!id.is_authenticated){setMessages([]);setThreads([]);setRecipients([]);setGrants([]);return;} setError('');
  const mem=await supabase.from('v7_mail_members').select('thread_id').eq('user_id',id.user_id); if(mem.error)throw new Error(mem.error.message); const tids=[...new Set((mem.data||[]).map((x:Row)=>String(x.thread_id)))];
  if(tids.length){const [m,t]=await Promise.all([supabase.from('v7_mail_messages').select('*').in('thread_id',tids).order('created_at',{ascending:false}).limit(100),supabase.from('v7_mail_threads').select('*').in('id',tids).order('created_at',{ascending:false})]); if(m.error)throw new Error(m.error.message);if(t.error)throw new Error(t.error.message);setMessages((m.data||[]) as Row[]);setThreads((t.data||[]) as Row[]);} else {setMessages([]);setThreads([]);}
  const con=await supabase.from('nayanet_connections').select('connected_member_id').eq('owner_member_id',id.user_id).eq('status','active'); if(!con.error){const mids=[...new Set((con.data||[]).map((x:Row)=>String(x.connected_member_id)))];if(mids.length){const m=await supabase.from('members').select('id,display_name').in('id',mids);if(!m.error)setRecipients((m.data||[]) as Row[]);}}
  const ag=await supabase.from('nayanet_authority_grants').select('grant_id,actions,status,expires_at').eq('subject_id',id.user_id).eq('status','ACTIVE').order('created_at',{ascending:false}).limit(50); if(!ag.error)setGrants((ag.data||[]).filter((g:Row)=>JSON.stringify(g.actions||'').includes('smart_mail_send')) as Row[]);
 };
 useEffect(()=>{setBusy(true);load().catch(e=>setError(e instanceof Error?e.message:'SMART_MAIL_LOAD_FAILED')).finally(()=>setBusy(false));},[id.is_authenticated,id.user_id]);
 const send=async()=>{if(!recipient||!grant||!body.trim()||busy)return;setBusy(true);setError('');setStatus('EXECUTING THROUGH NAYAPOWER…');try{const s=await supabase.auth.getSession();const token=s.data.session?.access_token;if(!token)throw new Error('AUTHENTICATION_REQUIRED');const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({operation:'send',recipient_user_id:recipient,subject:subject.trim()||'NayaNET communication',body:body.trim(),kind:'direct',idempotency_key:crypto.randomUUID(),project_id:'NayaNET',authority_grant_id:grant})});const data=await r.json().catch(()=>({}));if(!r.ok||data?.ok===false)throw new Error(String(data?.error||`SMART_MAIL_HTTP_${r.status}`));setStatus(`✓ SENT · RECEIPT ${short(data.execution_receipt_id)}`);setBody('');await load();}catch(e){setError(e instanceof Error?e.message:'SMART_MAIL_SEND_FAILED');setStatus('')}finally{setBusy(false)}};
 const verify=async(messageId:string)=>{if(busy)return;setBusy(true);setError('');setStatus('VERIFYING RECEIVER OUTCOME…');try{const s=await supabase.auth.getSession();const token=s.data.session?.access_token;if(!token)throw new Error('AUTHENTICATION_REQUIRED');const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({operation:'verify',message_id:messageId})});const data=await r.json().catch(()=>({}));if(!r.ok||data?.ok===false)throw new Error(String(data?.error||`SMART_MAIL_VERIFY_HTTP_${r.status}`));setStatus(`✓ RECEIVER VERIFIED · VALUE ${String(data?.outcome?.verified_value??'recorded')}`);await load();}catch(e){setError(e instanceof Error?e.message:'SMART_MAIL_VERIFY_FAILED');setStatus('')}finally{setBusy(false)}};
 if(!id.is_authenticated)return <section className="naya-mail-page"><div className="hero"><div className="eyebrow">NAYANET · COMMUNICATION</div><h1>Smart Mail</h1><p>Private, governed communication through the NayaNET intelligence engine.</p></div><div className="naya-mail-card"><b>AUTHENTICATION REQUIRED</b><p>Sign in through the NayaNET identity surface to use Smart Mail. No browser session is fabricated.</p></div></section>;
 const latest=threads[0]; const current=latest?messages.filter(m=>String(m.thread_id)===String(latest.id)):messages;
 return <section className="naya-mail-page"><div className="hero"><div className="eyebrow">NAYANET · SMART MAIL</div><h1>Smart Mail</h1><p>Real communication through the same governed engine that protects every consequential NayaPOWER action.</p></div><div className="naya-mail-layout"><aside className="naya-mail-panel"><div className="naya-mail-label">NEW MESSAGE</div><label>CONNECTED PERSON<select value={recipient} onChange={e=>setRecipient(e.target.value)}><option value="">Choose recipient…</option>{recipients.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.display_name||'NayaNET Member')}</option>)}</select></label><label>AUTHORITY<select value={grant} onChange={e=>setGrant(e.target.value)}><option value="">Choose active Smart Mail authority…</option>{grants.map(g=><option key={String(g.grant_id)} value={String(g.grant_id)}>{short(g.grant_id)} · {String(g.expires_at||'no expiry')}</option>)}</select></label><label>SUBJECT<input value={subject} onChange={e=>setSubject(e.target.value)}/></label><label>MESSAGE<textarea value={body} onChange={e=>setBody(e.target.value)} rows={8} placeholder="Write what NayaPOWER is authorized to send…"/></label><button className="powerBtn" disabled={!recipient||!grant||!body.trim()||busy} onClick={()=>void send()}>{busy?'EXECUTING…':'✦ SEND THROUGH NAYAPOWER'}</button>{status&&<div className="naya-mail-status">{status}</div>}{error&&<div className="naya-mail-error"><b>EXECUTION STOPPED</b><span>{error}</span></div>}</aside><main className="naya-mail-panel"><div className="naya-mail-label">MAIL · LIVE RECORDS</div><h2>{latest?String(latest.subject||'Current thread'):'Your Smart Mail'}</h2>{current.length?current.map(m=>{const mine=String(m.sender_id)===String(id.user_id);const meta=(m.metadata||{}) as Row;const receipt=meta.execution_receipt_id;const verified=meta.receiver_verified_at;return <article className="naya-mail-message" key={String(m.id)}><div><b>{mine?'YOU':'CONNECTED MEMBER'}</b><time>{new Date(String(m.created_at)).toLocaleString()}</time></div><p>{String(m.body||'')}</p><footer><span>RECEIPT · {receipt?short(receipt):'NOT LINKED'}</span>{verified?<em>RECEIVER VERIFIED</em>:!mine&&<button onClick={()=>void verify(String(m.id))} disabled={busy}>VERIFY OUTCOME</button>}</footer></article>;}):<div className="naya-mail-empty"><b>NO MESSAGES YET</b><span>Smart Mail is connected to the canonical Mail tables and the live execution boundary.</span></div>}</main></div></section>;
}
