import { chromium } from 'playwright';
import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
const runtime=(process.env.NAYA_RUNTIME_URL||'https://sparkling-shape-7ae5.smartnetpodcast.workers.dev').replace(/\/$/,'');
const sidebar=['Your Intelligence Today','Your Report','Intelligent Library','Smart Share','Smart Ledger','Your Connections','Smart Lists','Smart Spaces','Smart Mail','Settings'];
const forbiddenSidebar=['Collective','Evidence','Smart Start','Smart Ledgers','Peer Connections','Smart Mail New'];
const boardLabels=['IN A NUTSHELL','HUMAN NOTE','CHILD NOTE','GRANDMA NOTE','NAYA NOTE','MACHINE NOTE','ADAPTER LEARNING','WHAT IT MEANS','WHAT CAN I DO?',"WHAT'S IN IT FOR YOU",'TRUST · PROVENANCE · PRIVACY','RELATED INTELLIGENCE','ASK NAYA','CREATE SMART SPACE'];
const viewports=[['desktop',{width:1440,height:900}],['tablet',{width:1024,height:900}],['mobile',{width:390,height:844}]];
function assert(ok,message){if(!ok)throw new Error(message)}
function sha256(buffer){return createHash('sha256').update(buffer).digest('hex')}
async function visibleText(page,selector){return page.locator(selector).evaluateAll(nodes=>nodes.filter(n=>{const s=getComputedStyle(n),r=n.getBoundingClientRect();return s.visibility!=='hidden'&&s.display!=='none'&&r.width>0&&r.height>0}).map(n=>n.textContent.replace(/\s+/g,' ').trim()))}
try{
 const localIndex=await readFile('dist/index.html');const indexText=localIndex.toString('utf8');const assetMatch=indexText.match(/src="(\/assets\/[^\"]+\.js)"/);assert(assetMatch,'source binding: built index.html has no hashed JS asset');const assetPath=assetMatch[1];
 const runtimeIndexResponse=await fetch(`${runtime}/index.html?source-bind=${Date.now()}`,{cache:'no-store'});assert(runtimeIndexResponse.ok,`source binding: runtime index HTTP ${runtimeIndexResponse.status}`);const runtimeIndex=Buffer.from(await runtimeIndexResponse.arrayBuffer());assert(sha256(runtimeIndex)===sha256(localIndex),'source binding: deployed index.html hash differs from current build');
 const localAsset=await readFile(`dist${assetPath}`);const runtimeAssetResponse=await fetch(`${runtime}${assetPath}?source-bind=${Date.now()}`,{cache:'no-store'});assert(runtimeAssetResponse.ok,`source binding: runtime JS HTTP ${runtimeAssetResponse.status}`);const runtimeAsset=Buffer.from(await runtimeAssetResponse.arrayBuffer());assert(sha256(runtimeAsset)===sha256(localAsset),'source binding: deployed hashed JS asset differs from current build');console.log(`SOURCE_BINDING_PASS: index.html sha256=${sha256(localIndex)}`);console.log(`SOURCE_BINDING_PASS: ${assetPath} sha256=${sha256(localAsset)}`);
 const browser=await chromium.launch({headless:true});try{for(const[name,viewport]of viewports){const page=await browser.newPage({viewport});const response=await page.goto(`${runtime}/index.html?runtime-accept=${Date.now()}`,{waitUntil:'networkidle',timeout:30000});assert(response?.ok(),`${name}: index HTTP response failed`);await page.waitForTimeout(500);const navTexts=await visibleText(page,'.nav-item');for(const label of sidebar)assert(navTexts.some(text=>text===label),`${name}: missing sidebar "${label}"`);for(const legacy of forbiddenSidebar)assert(!navTexts.some(text=>text===legacy),`${name}: forbidden sidebar label visible: "${legacy}"`);assert(await page.locator('.app[data-shell-owner="AppShellV3"]').count()===1,`${name}: canonical AppShellV3 missing`);assert(await page.locator('.hub-home-restored').count()===1,`${name}: restored Hub home surface missing`);assert(await page.getByText('Your Intelligence Today',{exact:true}).count()===1,`${name}: Hub headline missing`);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+2),`${name}: horizontal overflow detected`);if(name==='desktop'){const smartMail=page.locator('.nav-item').filter({hasText:'Smart Mail'});await smartMail.click();assert(await smartMail.evaluate(el=>el.classList.contains('active')),'desktop: Smart Mail did not become active');await page.locator('.nav-item').filter({hasText:'Your Intelligence Today'}).click();const firstCard=page.locator('.intel-card').first();if(await firstCard.count()){await firstCard.click();await page.waitForTimeout(200);const firstBoard=page.locator('.smart-feed-board').first();assert(await firstBoard.count()===1,'desktop: SmartFeedBoard did not open from Hub intelligence');const boardText=(await firstBoard.innerText()).toUpperCase();for(const label of boardLabels)assert(boardText.includes(label),`desktop: SmartFeedBoard missing semantic layer "${label}"`);assert(await page.locator('.sfb-header-actions').count()===1,'desktop: SmartFeedBoard actions missing');assert(await page.locator('.sfb-header-actions .sfb-icon-button').count()===2,'desktop: Favorite/Save controls missing');assert(await page.locator('.sfb-btn.primary').count()>=1,'desktop: Create Space control missing');for(const legacy of ['Source separated','Providence','Truth','Protection','Smart Mail — New'])assert(!boardText.includes(legacy.toUpperCase()),`desktop: forbidden legacy text visible: "${legacy}"`)}else console.log('RUNTIME_NOTE: no intelligence objects available; shell acceptance passed, board interaction deferred');}console.log(`RUNTIME_ACCEPTANCE_PASS: ${name} ${viewport.width}x${viewport.height}`);await page.close()}console.log(`RUNTIME_ACCEPTANCE_PASS: ${runtime}`)}finally{await browser.close()}}catch(error){console.error(`RUNTIME_ACCEPTANCE_FAIL: ${error.message}`);process.exitCode=1}