import { useEffect, useState } from 'react';
import { useIdentity } from '../../../identity/session';

type Verification={valid:boolean;events:number;receipts:number;indexed:boolean;persistence?:{mode:string;status:string;last_sync_at?:string;last_write_at?:string;last_error?:string}};
export function SettingsSurface(){
 const identity=useIdentity();const[verification,setVerification]=useState<Verification|null>(null);const[status,setStatus]=useState('');const[busy,setBusy]=useState(false);
 const verify=()=>{try{const rt=window.NayaAssistantRuntime;if(!rt?.verify)throw new Error('RUNTIME_VERIFY_UNAVAILABLE');const result=rt.verify() as Verification;setVerification(result);setStatus(result.valid?'RUNTIME VERIFIED · '+result.events+' EVENTS · '+result.receipts+' RECEIPTS':'RUNTIME VERIFICATION FAILED')}catch(e){setStatus(e instanceof Error?e.message:'RUNTIME_VERIFY_FAILED')}};
 useEffect(()=>{if(identity.is_authenticated)verify()},[identity.is_authenticated]);
 const signOut=async()=>{setBusy(true);setStatus('SIGNING OUT…');try{const rt=window.NayaAssistantRuntime;if(rt?.signOut)await rt.signOut();else throw new Error('RUNTIME_SIGNOUT_UNAVAILABLE');setStatus('SIGNED OUT · SESSION CLOSED')}catch(e){setStatus('SIGN OUT FAILED · '+(e instanceof Error?e.message:'SIGNOUT_FAILED'))}finally{setBusy(false)}};
 if(!identity.is_authenticated)return <section className="feature-surface" data-surface="settings"><div className="feature-hero"><div><div className="eyebrow">NAYANET · SETTINGS · IDENTITY · CONTROL</div><h1>Settings</h1><p>Identity, session, and governed runtime controls.</p></div></div><div className="feature-empty"><b>AUTHENTICATION REQUIRED</b><span>Settings that inspect private runtime state are available after identity establishment.</span></div></section>;
 return <section className="feature-surface" data-surface="settings"><div className="feature-hero"><div><div className="eyebrow">NAYANET · SETTINGS · IDENTITY · CONTROL</div><h1>Settings</h1><p>Know who you are, what runtime is active, and whether the persistence boundary verifies.</p></div><div className="feature-state">AUTHENTICATED · {identity.smart_name||'NAYA MEMBER'}</div></div><div className="settings-grid"><article className="settings-card"><span className="feature-card-kicker">IDENTITY</span><h2>{identity.smart_name||'NayaNET Member'}</h2><p>Address: {identity.smart_alias||'—'}</p><p>Member ID: {identity.user_id||'—'}</p><button onClick={()=>void signOut()} disabled={busy}>{busy?'CLOSING…':'SIGN OUT'}</button></article><article className="settings-card"><span className="feature-card-kicker">RUNTIME HEALTH</span><h2>{verification?.valid?'VERIFIED':'CHECK REQUIRED'}</h2><div className="settings-metrics"><span>EVENTS <b>{verification?.events??'—'}</b></span><span>RECEIPTS <b>{verification?.receipts??'—'}</b></span><span>INDEXED <b>{verification?.indexed?'YES':'NO'}</b></span></div><p>Persistence: {verification?.persistence?.mode||'unknown'} · {verification?.persistence?.status||'not checked'}</p><button onClick={verify} disabled={busy}>↻ VERIFY RUNTIME</button></article></div>{status&&<div className="feature-status" role="status">{status}</div>}<div className="settings-laws"><b>GOVERNANCE</b><span>CAPABILITY DOES NOT CREATE AUTHORITY</span><span>PRIVATE BY DEFAULT · SHARED BY CHOICE</span><span>UNKNOWN ≠ SUCCESS · BLOCKED ≠ PASS</span></div><div className="feature-foot"><span>CONTROL</span><b>HUMAN DIRECTOR · GOVERNED ENGINE</b><span>•</span><span>TRUTH OVER AGREEMENT</span></div></section>;
}
