-- NayaNET Smart Ledger Foundation V1
-- Canonical evidence/integrity layer. References existing truth stores; does not replace them.

create table if not exists public.nayanet_smart_ledger (
  ledger_event_id uuid primary key default gen_random_uuid(),
  schema_version text not null default '1.0.0',
  owner_id uuid not null references auth.users(id),
  actor_id uuid null references auth.users(id),
  event_type text not null,
  event_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  source_table text not null,
  source_id text not null,
  parent_ledger_event_id uuid null references public.nayanet_smart_ledger(ledger_event_id),
  chain_seq bigint generated by default as identity,
  previous_chain_hash text null,
  event_hash text not null,
  privacy_classification text not null default 'PRIVATE',
  status text not null default 'RECORDED',
  evidence_refs jsonb not null default '[]'::jsonb,
  verification jsonb not null default '{}'::jsonb,
  value jsonb not null default '{}'::jsonb,
  outcome jsonb not null default '{}'::jsonb,
  learning_refs jsonb not null default '[]'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  supersedes_ledger_event_id uuid null references public.nayanet_smart_ledger(ledger_event_id),
  qualified_by_ledger_event_id uuid null references public.nayanet_smart_ledger(ledger_event_id),
  constraint nayanet_smart_ledger_source_unique unique(owner_id,source_table,source_id),
  constraint nayanet_smart_ledger_privacy_check check (privacy_classification in ('PRIVATE','SHARED','COLLECTIVE','PUBLIC')),
  constraint nayanet_smart_ledger_status_check check (status in ('RECORDED','VERIFIED','QUALIFIED','SUPERSEDED','BLOCKED','FAILED')),
  constraint nayanet_smart_ledger_evidence_array check (jsonb_typeof(evidence_refs)='array'),
  constraint nayanet_smart_ledger_learning_array check (jsonb_typeof(learning_refs)='array')
);

create unique index if not exists nayanet_smart_ledger_owner_chain_seq_uq on public.nayanet_smart_ledger(owner_id,chain_seq);
create index if not exists nayanet_smart_ledger_owner_time_idx on public.nayanet_smart_ledger(owner_id,event_at desc);
create index if not exists nayanet_smart_ledger_source_idx on public.nayanet_smart_ledger(source_table,source_id);
create index if not exists nayanet_smart_ledger_parent_idx on public.nayanet_smart_ledger(parent_ledger_event_id);

alter table public.nayanet_smart_ledger enable row level security;
drop policy if exists nayanet_smart_ledger_select_own on public.nayanet_smart_ledger;
create policy nayanet_smart_ledger_select_own on public.nayanet_smart_ledger for select to authenticated using (owner_id=auth.uid());
revoke insert,update,delete on public.nayanet_smart_ledger from anon,authenticated;

create or replace function public.nayanet_smart_ledger_hash(
 p_owner_id uuid,p_event_type text,p_event_at timestamptz,p_source_table text,p_source_id text,
 p_parent_ledger_event_id uuid,p_previous_chain_hash text,p_evidence_refs jsonb,p_metadata jsonb
) returns text language sql immutable set search_path=public,extensions as $$
 select encode(extensions.digest(
  coalesce(p_owner_id::text,'')||'|'||coalesce(p_event_type,'')||'|'||coalesce(p_event_at::text,'')||'|'||
  coalesce(p_source_table,'')||'|'||coalesce(p_source_id,'')||'|'||coalesce(p_parent_ledger_event_id::text,'')||'|'||
  coalesce(p_previous_chain_hash,''),'sha256'),'hex');
$$;

create or replace function public.nayanet_record_ledger_event(
 p_owner_id uuid,p_event_type text,p_source_table text,p_source_id text,p_event_at timestamptz default now(),
 p_actor_id uuid default null,p_privacy_classification text default 'PRIVATE',p_status text default 'RECORDED',
 p_evidence_refs jsonb default '[]'::jsonb,p_verification jsonb default '{}'::jsonb,p_value jsonb default '{}'::jsonb,
 p_outcome jsonb default '{}'::jsonb,p_learning_refs jsonb default '[]'::jsonb,p_metadata jsonb default '{}'::jsonb,
 p_parent_ledger_event_id uuid default null
) returns public.nayanet_smart_ledger language plpgsql security definer set search_path=public,extensions as $$
declare v_existing public.nayanet_smart_ledger; v_previous text; v_id uuid:=gen_random_uuid(); v_hash text;
begin
 if p_owner_id is null or nullif(trim(p_event_type),'') is null or nullif(trim(p_source_table),'') is null or nullif(trim(p_source_id),'') is null then raise exception 'LEDGER_REQUIRED_FIELDS'; end if;
 select * into v_existing from public.nayanet_smart_ledger where owner_id=p_owner_id and source_table=p_source_table and source_id=p_source_id limit 1;
 if found then return v_existing; end if;
 if p_parent_ledger_event_id is not null then
   select event_hash into v_previous from public.nayanet_smart_ledger where ledger_event_id=p_parent_ledger_event_id and owner_id=p_owner_id;
   if not found then raise exception 'LEDGER_PARENT_NOT_FOUND'; end if;
 else
   select event_hash into v_previous from public.nayanet_smart_ledger where owner_id=p_owner_id order by chain_seq desc limit 1;
 end if;
 v_hash:=public.nayanet_smart_ledger_hash(p_owner_id,p_event_type,p_event_at,p_source_table,p_source_id,p_parent_ledger_event_id,v_previous,coalesce(p_evidence_refs,'[]'::jsonb),coalesce(p_metadata,'{}'::jsonb));
 insert into public.nayanet_smart_ledger(ledger_event_id,schema_version,owner_id,actor_id,event_type,event_at,source_table,source_id,parent_ledger_event_id,previous_chain_hash,event_hash,privacy_classification,status,evidence_refs,verification,value,outcome,learning_refs,metadata)
 values(v_id,'1.0.0',p_owner_id,p_actor_id,p_event_type,p_event_at,p_source_table,p_source_id,p_parent_ledger_event_id,v_previous,v_hash,p_privacy_classification,p_status,coalesce(p_evidence_refs,'[]'::jsonb),coalesce(p_verification,'{}'::jsonb),coalesce(p_value,'{}'::jsonb),coalesce(p_outcome,'{}'::jsonb),coalesce(p_learning_refs,'[]'::jsonb),coalesce(p_metadata,'{}'::jsonb))
 returning * into v_existing;
 return v_existing;
exception when unique_violation then
 select * into v_existing from public.nayanet_smart_ledger where owner_id=p_owner_id and source_table=p_source_table and source_id=p_source_id limit 1;
 if found then return v_existing; end if; raise;
end; $$;

revoke execute on function public.nayanet_record_ledger_event(uuid,text,text,text,timestamptz,uuid,text,text,jsonb,jsonb,jsonb,jsonb,jsonb,jsonb,uuid) from public,anon,authenticated;

create or replace function public.nayanet_smart_note_to_ledger() returns trigger language plpgsql security definer set search_path=public,extensions as $$
begin
 perform public.nayanet_record_ledger_event(
  new.member_id,'SMART_NOTE_CREATED','smart_note_events',new.id::text,new.created_at,new.member_id,
  case when new.privacy_state='SHARED' then 'SHARED' else 'PRIVATE' end,
  case when new.status='VERIFIED' then 'VERIFIED' else 'RECORDED' end,
  jsonb_build_array(jsonb_build_object('source_table','smart_note_events','source_id',new.id::text)),
  case when new.status='VERIFIED' then jsonb_build_object('status','VERIFIED','verified_at',new.verified_at) else '{}'::jsonb end,
  jsonb_build_object('assessed',false,'base_points',5,'value_engine','NayaNET_V1_STARTING_MODEL'),
  '{}'::jsonb,'[]'::jsonb,
  jsonb_build_object('smart_note_event_id',new.id,'subject',new.subject,'event_type',new.event_type,'privacy_state',new.privacy_state,'source_context',new.source_context,'created_at',new.created_at)
 );
 return new;
end; $$;

drop trigger if exists nayanet_smart_note_event_to_smart_ledger on public.smart_note_events;
create trigger nayanet_smart_note_event_to_smart_ledger after insert on public.smart_note_events for each row execute function public.nayanet_smart_note_to_ledger();

create or replace function public.nayanet_smart_note_receipt_to_ledger() returns trigger language plpgsql security definer set search_path=public,extensions as $$
begin
 update public.nayanet_smart_ledger l set
  status=case when new.status='VERIFIED' then 'VERIFIED' else l.status end,
  verification=coalesce(new.verification,'{}'::jsonb)||jsonb_build_object('smart_note_receipt_id',new.id,'receipt_status',new.status)
 where l.owner_id=(select e.member_id from public.smart_note_events e where e.id=new.event_id)
   and l.source_table='smart_note_events' and l.source_id=new.event_id::text;
 return new;
end; $$;

drop trigger if exists nayanet_smart_note_receipt_to_smart_ledger on public.smart_note_receipts;
create trigger nayanet_smart_note_receipt_to_smart_ledger after insert or update on public.smart_note_receipts for each row execute function public.nayanet_smart_note_receipt_to_ledger();

create or replace function public.nayanet_execution_receipt_to_ledger() returns trigger language plpgsql security definer set search_path=public,extensions as $$
declare v_evidence jsonb;
begin
 v_evidence:=case when jsonb_typeof(coalesce(new.evidence,'{}'::jsonb))='array' then coalesce(new.evidence,'[]'::jsonb) else jsonb_build_array(coalesce(new.evidence,'{}'::jsonb)) end;
 perform public.nayanet_record_ledger_event(
  new.user_id,'EXECUTION_RECEIPT','nayanet_execution_receipts',new.id::text,new.created_at,null,'PRIVATE',
  case when new.status='SUCCESS' then 'VERIFIED' when new.status='BLOCKED' then 'BLOCKED' when new.status='FAILED' then 'FAILED' else 'RECORDED' end,
  v_evidence,jsonb_build_object('receipt_status',new.status,'authority_grant_id',new.authority_grant_id,'policy_id',new.policy_id),
  coalesce(new.value,'{}'::jsonb),jsonb_build_object('observed_result',new.observed_result),
  case when jsonb_typeof(coalesce(new.learning,'[]'::jsonb))='array' then coalesce(new.learning,'[]'::jsonb) else jsonb_build_array(new.learning) end,
  jsonb_build_object('action',new.action,'project_id',new.project_id,'revision',new.revision)
 );
 return new;
end; $$;
drop trigger if exists nayanet_execution_receipt_to_smart_ledger on public.nayanet_execution_receipts;
create trigger nayanet_execution_receipt_to_smart_ledger after insert on public.nayanet_execution_receipts for each row execute function public.nayanet_execution_receipt_to_ledger();

create or replace function public.nayanet_cognition_event_to_ledger() returns trigger language plpgsql security definer set search_path=public,extensions as $$
begin
 perform public.nayanet_record_ledger_event(new.user_id,'COGNITION_EVENT','nayanet_cognition_events',new.id::text,new.created_at,new.user_id,'PRIVATE','RECORDED',
  jsonb_build_array(jsonb_build_object('source_table','nayanet_cognition_events','source_id',new.id::text)),
  jsonb_build_object('status',new.status,'confidence',new.confidence,'receipt_id',new.receipt_id),'{}'::jsonb,'{}'::jsonb,'[]'::jsonb,
  jsonb_build_object('event_id',new.event_id,'type',new.type,'classification',new.classification,'project_id',new.project_id,'parent_event_id',new.parent_event_id));
 return new;
end; $$;
drop trigger if exists nayanet_cognition_event_to_smart_ledger on public.nayanet_cognition_events;
create trigger nayanet_cognition_event_to_smart_ledger after insert on public.nayanet_cognition_events for each row execute function public.nayanet_cognition_event_to_ledger();

create or replace function public.nayanet_report_to_ledger() returns trigger language plpgsql security definer set search_path=public,extensions as $$
begin
 perform public.nayanet_record_ledger_event(new.user_id,'INTELLIGENCE_REPORT','v7_intelligence_reports',new.id::text,new.created_at,new.user_id,'PRIVATE','RECORDED','[]'::jsonb,
  jsonb_build_object('status',new.status),'{}'::jsonb,'{}'::jsonb,'[]'::jsonb,jsonb_build_object('period_type',new.period_type,'period_start',new.period_start,'period_end',new.period_end));
 return new;
end; $$;
drop trigger if exists nayanet_report_to_smart_ledger on public.v7_intelligence_reports;
create trigger nayanet_report_to_smart_ledger after insert on public.v7_intelligence_reports for each row execute function public.nayanet_report_to_ledger();

create or replace function public.nayanet_learning_evidence_to_ledger() returns trigger language plpgsql security definer set search_path=public,extensions as $$
begin
 perform public.nayanet_record_ledger_event(new.member_id,'LEARNING_EVIDENCE','learning_evidence',new.id::text,new.created_at,new.member_id,'PRIVATE',
  case when lower(new.status) in ('active') then 'VERIFIED' else 'RECORDED' end,
  jsonb_build_array(jsonb_build_object('source_table','learning_evidence','source_id',new.id::text)),
  jsonb_build_object('status',new.status,'verification_method',new.verification_method,'provenance',new.provenance),'{}'::jsonb,'{}'::jsonb,'[]'::jsonb,
  jsonb_build_object('target_id',new.target_id,'level',new.level,'claim',new.claim,'source_event_id',new.source_event_id));
 return new;
end; $$;
drop trigger if exists nayanet_learning_evidence_to_smart_ledger on public.learning_evidence;
create trigger nayanet_learning_evidence_to_smart_ledger after insert on public.learning_evidence for each row execute function public.nayanet_learning_evidence_to_ledger();

create or replace function public.nayanet_space_to_ledger() returns trigger language plpgsql security definer set search_path=public,extensions as $$
begin
 perform public.nayanet_record_ledger_event(new.owner_member_id,'SMART_SPACE_CREATED','nayanet_spaces',new.id::text,new.created_at,new.owner_member_id,
  case when lower(new.visibility)='shared' then 'SHARED' else 'PRIVATE' end,'RECORDED','[]'::jsonb,'{}'::jsonb,
  jsonb_build_object('assessed',false,'base_points',10,'value_engine','NayaNET_V1_STARTING_MODEL'),'{}'::jsonb,'[]'::jsonb,
  jsonb_build_object('name',new.name,'purpose',new.purpose,'visibility',new.visibility));
 return new;
end; $$;
drop trigger if exists nayanet_space_to_smart_ledger on public.nayanet_spaces;
create trigger nayanet_space_to_smart_ledger after insert on public.nayanet_spaces for each row execute function public.nayanet_space_to_ledger();

create or replace function public.nayanet_smart_ledger_to_intelligence_index() returns trigger language plpgsql security definer set search_path=public,extensions as $$
begin
 insert into public.nayanet_intelligence_index(owner_id,source_table,source_id,object_type,title,event_time,created_at,updated_at,status,project_id,revision,metadata)
 values(new.owner_id,'nayanet_smart_ledger',new.ledger_event_id,'REFERENCE',new.event_type,new.event_at,new.created_at,new.created_at,new.status,null,null,
  jsonb_build_object('source_table',new.source_table,'source_id',new.source_id,'verification',new.verification,'privacy_classification',new.privacy_classification))
 on conflict(owner_id,source_table,source_id) do update set object_type=excluded.object_type,title=excluded.title,event_time=excluded.event_time,updated_at=excluded.updated_at,status=excluded.status,metadata=excluded.metadata;
 return new;
end; $$;
drop trigger if exists nayanet_smart_ledger_to_intelligence_index on public.nayanet_smart_ledger;
create trigger nayanet_smart_ledger_to_intelligence_index after insert on public.nayanet_smart_ledger for each row execute function public.nayanet_smart_ledger_to_intelligence_index();

drop trigger if exists nayanet_report_to_intelligence_index on public.v7_intelligence_reports;
create trigger nayanet_report_to_intelligence_index after insert on public.v7_intelligence_reports for each row execute function public.nayanet_index_intelligence_row();
drop trigger if exists nayanet_learning_to_intelligence_index on public.learning_evidence;
create trigger nayanet_learning_to_intelligence_index after insert on public.learning_evidence for each row execute function public.nayanet_index_intelligence_row();

comment on table public.nayanet_smart_ledger is 'Canonical Smart Ledger evidence/integrity layer. References existing event, receipt, note, report, learning, space, and cognition truth stores; it is not a duplicate truth store.';
