#!/usr/bin/env python3
"""Deterministic NayaPOWER system-health/master-node acceptance contract."""
from __future__ import annotations
import argparse, json, os, shutil, subprocess, tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
ROOT=Path(__file__).resolve().parents[2]
MANIFEST=ROOT/'.naya/naya-context-manifest.json'; START=ROOT/'SUPERBRAIN/AI-BOOT/START-HERE.md'; BOOT=ROOT/'.naya/NAYA-CONTEXT-BOOT-PROTOCOL.md'; POLICY=ROOT/'.naya/codex/HUMAN-CAPABILITY-AND-MASTERY-OPERATING-PROTOCOL.md'; MEMORY_BOOT=ROOT/'.naya/memory/BOOTSTRAP.md'; COLD_START=ROOT/'.naya/runtime/cold_start_activation.py'; COLD_CONTRACT=ROOT/'.naya/runtime/COLD-START-ACTIVATION-ACCEPTANCE.md'; CONTINUITY=ROOT/'.naya/runtime/continuity_enforcement.py'; EVIDENCE=ROOT/'.naya/runtime/evidence_runtime.py'; ACTIVATION_CONTRACT=ROOT/'.naya/runtime/activation_contract.py'; EVENT_INDEX=ROOT/'.naya/memory/events/INDEX.json'; CODE_OF_HONOR=ROOT/'SUPERBRAIN/MASTER-NOTES/SN-20260827-NAYA-CODE-OF-HONOR.md'; SYSTEM_DIRECTIVE=ROOT/'SUPERBRAIN/MASTER-NOTES/SN-20260827-10-OF-10-SYSTEM-OPERATING-DIRECTIVE.md'; MASTER_NOTE=ROOT/'SUPERBRAIN/MASTER-NOTES/SN-20260827-CONTINUOUS-BLOCK-EXECUTION-AND-ONE-NET.md'
REQUIRED_FILES={'governance':ROOT/'.naya/codex/11-RUNTIME-CONSTITUTION.md','context_manifest':MANIFEST,'boot_entry':START,'context_boot':BOOT,'human_capability_policy':POLICY,'code_of_honor':CODE_OF_HONOR,'system_directive':SYSTEM_DIRECTIVE,'memory_boot':MEMORY_BOOT,'cold_start_acceptance':COLD_START,'cold_start_contract':COLD_CONTRACT,'continuity_runtime':CONTINUITY,'evidence_runtime':EVIDENCE,'activation_contract':ACTIVATION_CONTRACT,'event_index':EVENT_INDEX,'master_note':MASTER_NOTE}
def load(path:Path)->str:
    if not path.is_file(): raise RuntimeError(f'missing canonical artifact: {path.relative_to(ROOT)}')
    return path.read_text(encoding='utf-8')
def check(results:list[dict[str,Any]],name:str,ok:bool,evidence:str,detail:str='')->None: results.append({'name':name,'status':'PASS' if ok else 'FAIL','evidence':evidence,'detail':detail})
def run_contract(results:list[dict[str,Any]],name:str,command:list[str])->None:
    p=subprocess.run(command,cwd=ROOT,text=True,capture_output=True); out=(p.stdout+('\n'+p.stderr if p.stderr else '')).strip(); check(results,name,p.returncode==0,out[-4000:],f'exit_code={p.returncode}')
def check_derived_index(results:list[dict[str,Any]])->None:
    if not EVENT_INDEX.is_file(): check(results,'derived event/index integrity',False,'INDEX.json missing'); return
    with tempfile.NamedTemporaryFile(prefix='naya-index-',suffix='.json',delete=False) as tmp: backup=Path(tmp.name)
    try:
        shutil.copyfile(EVENT_INDEX,backup); p=subprocess.run(['python','.naya/memory/smart_notes_v3.py','index'],cwd=ROOT,text=True,capture_output=True); generated=EVENT_INDEX.read_bytes() if EVENT_INDEX.exists() else b''; expected=backup.read_bytes(); out=(p.stdout+('\n'+p.stderr if p.stderr else '')).strip(); check(results,'derived event/index integrity',p.returncode==0 and generated==expected,out[-4000:] or 'byte-for-byte comparison',f'exit_code={p.returncode}')
    finally: shutil.copyfile(backup,EVENT_INDEX); backup.unlink(missing_ok=True)
def git_head()->str:
    return os.environ.get('GITHUB_SHA') or subprocess.run(['git','rev-parse','HEAD'],cwd=ROOT,text=True,capture_output=True,check=True).stdout.strip()
def main()->int:
    ap=argparse.ArgumentParser(); ap.add_argument('--receipt',default=''); args=ap.parse_args(); started=datetime.now(timezone.utc).isoformat(); results=[]
    manifest=json.loads(load(MANIFEST)); start=load(START); boot=load(BOOT); policy=load(POLICY); honor=load(CODE_OF_HONOR); directive=load(SYSTEM_DIRECTIVE); memory_boot=load(MEMORY_BOOT); cold_contract=load(COLD_CONTRACT); master_note=load(MASTER_NOTE)
    policy_lower=policy.lower(); honor_lower=honor.lower(); directive_lower=directive.lower(); boot_lower=boot.lower(); memory_lower=memory_boot.lower(); start_lower=start.lower(); boot_order={str(x).lower() for x in manifest.get('boot_order',[])}
    check(results,'canonical artifacts documented',all(p.is_file() for p in REQUIRED_FILES.values()),', '.join(str(p.relative_to(ROOT)) for p in REQUIRED_FILES.values()))
    check(results,'canonical repository',manifest.get('repository')=='SoulSchoolAcademy/NayaPOWER',str(manifest.get('repository')))
    check(results,'canonical governance',manifest.get('governance_branch')=='main' and manifest.get('status')=='CANONICAL',f"branch={manifest.get('governance_branch')} status={manifest.get('status')}")
    check(results,'canonical boot','.naya/codex/human-capability-and-mastery-operating-protocol.md' in start_lower and '.naya/naya-context-boot-protocol.md' in boot_order,'START-HERE + manifest boot_order')
    registered_ok=manifest.get('subjects',{}).get('human_capability_and_mastery',{}).get('canonical')=='.naya/codex/HUMAN-CAPABILITY-AND-MASTERY-OPERATING-PROTOCOL.md' and all('human_capability_and_mastery' in route for route in manifest.get('task_routes',{}).values()); check(results,'human capability policy registered',registered_ok,'manifest subject owner + all task routes')
    check(results,'Code of Honor inherited',CODE_OF_HONOR.is_file() and CODE_OF_HONOR.relative_to(ROOT).as_posix().lower() in start_lower and 'create the most human value possible with every meaningful action.' in honor_lower and 'zoom out → zoom in → connect → prioritize → optimize → execute → verify → learn → compound' in honor_lower,'Code of Honor artifact + boot inheritance + value method')
    check(results,'10/10 system directive active',SYSTEM_DIRECTIVE.is_file() and SYSTEM_DIRECTIVE.relative_to(ROOT).as_posix().lower() in start_lower and all(x in directive for x in ('SOURCE OF TRUTH','STATE','EXECUTION','VERIFICATION','RUNTIME','QUALITY','CONTINUITY','LEARNING','HANDOFF')),'10/10 directive artifact + boot path + nine domains')
    check(results,'operating method','execute → verify → oscar → score → integrate → capture → check network → identify next block' in policy_lower and 'continuous block execution' in start_lower,'policy + START-HERE')
    completion_ok=('a block is complete only when' in policy_lower and 'unknown is never success' in start_lower) or ('complete requires the defined success criteria' in start_lower and 'unknown is never success' in start_lower); check(results,'block completion evidence',completion_ok,'completion/evidence contract')
    check(results,'unfinished-block continuity','ready-to-run **next execution**' in policy_lower and ('next naya' in start_lower or 'ready-to-run continuation → next execution' in start_lower),'policy + torch-pass contract')
    check(results,'master scorecard','after every 1–3 substantive blocks' in policy_lower and 'why is this not a 10?' in policy_lower,'review cadence')
    check(results,'next execution','every substantive output must therefore end with a **torch pass / next naya handoff**' in policy_lower and 'ready-to-run continuation → next execution' in start_lower,'policy + START-HERE')
    check(results,'one-network',('one governed naya network' in start_lower and 'every naya is a governed node in one intelligence system' in start_lower) or 'one network → one naya law → one source of truth' in start_lower,'One-Network law')
    check(results,'authority','does not override platform/safety constraints' in boot_lower and 'human safety & agency → truth & evidence → governing law' in policy_lower,'conduct precedence')
    check(results,'provenance','provenance-aware' in policy_lower and 'authority' in boot_lower,'policy provenance + context authority model')
    check(results,'human control','the human may' in policy_lower and 'stop the interaction' in policy_lower,'agency + explicit stop boundary')
    check(results,'future handoff','next naya' in policy_lower and 'next execution' in start_lower,'continuity/handoff language')
    specialized_ok=all(token.lower() in policy_lower for token in ('Naya:','NayaPOWER:','MAXIS:','MAXESS:','Oscar:')) and 'competing governance' in policy_lower; check(results,'specialized node boundaries',specialized_ok,'system role boundary')
    memory_owner=manifest.get('subjects',{}).get('memory',{}).get('canonical',''); memory_registered=memory_owner.lower()=='.naya/memory/bootstrap.md' and '.naya/memory/bootstrap.md' in boot_order; cis_present='compounding intelligence system' in memory_lower; reality_present='repository reality' in memory_lower; memory_ok=memory_registered and cis_present and reality_present; check(results,'memory/CIS',memory_ok,f"manifest memory owner + memory boot order; owner={memory_owner!r}; boot_order_contains={'.naya/memory/bootstrap.md' in boot_order}",f'memory_registered={memory_registered}; cis_present={cis_present}; reality_present={reality_present}')
    check(results,'canonical event/index',EVENT_INDEX.is_file() and 'derived indexes must be rebuildable' in memory_lower,str(EVENT_INDEX.relative_to(ROOT))); check_derived_index(results)
    check(results,'cold-start contract present',COLD_START.is_file() and 'unknown is never success' in cold_contract.lower(),'cold-start runtime + acceptance contract'); check(results,'verification mechanisms',all(p.is_file() for p in (EVIDENCE,CONTINUITY,ACTIVATION_CONTRACT)),'evidence + continuity + activation contracts')
    run_contract(results,'cold-start activation',['python',str(COLD_START.relative_to(ROOT))]); run_contract(results,'continuity self-test',['python',str(CONTINUITY.relative_to(ROOT)),'self-test']); run_contract(results,'Smart Brain validation',['python','.naya/memory/smart_notes_v3.py','validate']); run_contract(results,'Smart Brain tests',['python','.naya/memory/test_smart_brain_v3.py','-v'])
    by={x['name']:x['status']=='PASS' for x in results}; all_ok=all(by.values()); activation_ok=by.get('cold-start activation',False); context_ok=all(by.get(n,False) for n in ('canonical repository','canonical governance','canonical boot','human capability policy registered','Code of Honor inherited','10/10 system directive active','authority','provenance','human control')); method_ok=all(by.get(n,False) for n in ('operating method','block completion evidence','unfinished-block continuity','master scorecard','next execution','future handoff')); verification_ok=all(by.get(n,False) for n in ('derived event/index integrity','verification mechanisms','continuity self-test','Smart Brain validation','Smart Brain tests')); network_ok=all(by.get(n,False) for n in ('one-network','specialized node boundaries','provenance','human control'))
    receipt={'schema':'naya/system-health-receipt/v2','status':'HEALTHY' if all_ok else 'DEGRADED','generated_at':started,'repository':manifest.get('repository'),'head':git_head(),'governance_branch':manifest.get('governance_branch'),'states':{'documented':'PASS' if by.get('canonical artifacts documented',False) else 'FAIL','registered':'PASS' if all(by.get(n,False) for n in ('canonical repository','canonical governance','human capability policy registered')) else 'PARTIAL','activated':'PASS' if activation_ok else 'FAIL','context_established':'PASS' if context_ok else 'PARTIAL','operating_method_established':'PASS' if method_ok else 'PARTIAL','verified':'PASS' if verification_ok and all_ok else ('PARTIAL' if verification_ok else 'FAIL'),'network_connected':'PASS' if network_ok else 'PARTIAL','healthy':'HEALTHY' if all_ok else 'DEGRADED'},'checks':results,'network':{'model':'one governed Naya network','substrate':'NayaPOWER','specialized_nodes':['Naya','MAXIS','MAXESS','Oscar'],'privacy_boundary':'private memory is not merged merely because another Naya exists','live_federation':'NOT_PROVEN_BY_THIS_CONTRACT'},'limitations':['This is a current repository/system contract, not a live external LLM execution proof.','Network-connected means governed architectural integration is verified; live federation is not claimed.','Deployment/Vercel health is intentionally separate from Smart Brain/system health.'],'evidence':{'canonical_artifacts':[str(p.relative_to(ROOT)) for p in REQUIRED_FILES.values()],'runtime_commands':['python .naya/runtime/cold_start_activation.py','python .naya/runtime/continuity_enforcement.py self-test','python .naya/memory/smart_notes_v3.py validate','python .naya/memory/test_smart_brain_v3.py -v']}}
    if args.receipt: path=(ROOT/args.receipt).resolve() if not Path(args.receipt).is_absolute() else Path(args.receipt); path.parent.mkdir(parents=True,exist_ok=True); path.write_text(json.dumps(receipt,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
    print(json.dumps(receipt,indent=2,ensure_ascii=False)); return 0 if all_ok else 1
if __name__=='__main__': raise SystemExit(main())
