import{useEffect,useMemo,useState}from'react';
import type{CSSProperties,ReactNode}from'react';
import type{IntelligentEvent,Lens,Perspective as EventPerspective}from'./types';
import{persistSmartFeedAction,retrieveSmartFeedActions}from'./cognition';

type BoardProps={event:IntelligentEvent};type ActionKey='favorite'|'save'|'like'|'love';type Persisted={favorite:boolean;save:boolean;like:boolean;love:boolean;rating:number;comments:string[];links:string[];space?:{id:string;name:string;purpose:string;visibility:string;created_at:string}};const emptyState=():Persisted=>({favorite:false,save:false,like:false,love:false,rating:0,comments:[],links:[]});const[status,setStatus]=useState('');const[spaceName,setSpaceName]=useState('');const[spacePurpose,setSpacePurpose]=useState('Turn this intelligence into a place to learn and act together.');const[visibility,setVisibility]=useState('private');const[state,setState]=useState<Persisted>(emptyState);const[hydrated,setHydrated]=useState(false);const[comment,setComment]=useState('');
useEffect(()=>{let cancelled=false;(async()=>{try{const actions=await retrieveSmartFeedActions(event.event_id);const latest=[...actions].reverse().find(x=>x.metadata?.state);if(!cancelled&&latest?.metadata?.state){setState(latest.metadata.state as Persisted);setStatus('DURABLE STATE RESTORED · '+String(latest.event_id))}else if(!cancelled)setStatus('NO DURABLE ACTIONS RECORDED');}catch(error){if(!cancelled)setStatus('ACTION RETRIEVAL BLOCKED · '+(error instanceof Error?error.message:'RUNTIME_ERROR'));}finally{if(!cancelled)setHydrated(true)}})();return()=>{cancelled=true}},[event.event_id]);
const persistState=async(next:Persisted,action:string,value:unknown)=>{const previous=state;setState(next);setStatus('PERSISTING '+action.toUpperCase()+'…');try{const receipt=await persistSmartFeedAction({sourceEventId:event.event_id,action,value,state:next as Record<string,unknown>});setStatus('ACTION PERSISTED · EVENT '+receipt.eventId);return receipt}catch(error){setState(previous);setStatus('ACTION BLOCKED · '+(error instanceof Error?error.message:'PERSISTENCE_FAILED'));throw error}};
const toggle=(key:ActionKey)=>{const next={...state,[key]:!state[key]};void persistState(next,key,next[key])};const rate=(n:number)=>{const next={...state,rating:n};void persistState(next,'rating',n)};const addComment=()=>{if(!comment.trim())return;const value=comment.trim();const next={...state,comments:[...state.comments,value]};void persistState(next,'comments',value).then(()=>setComment('')).catch(()=>undefined)};const connect=(id:string)=>{if(state.links.includes(id))return;const next={...state,links:[...state.links,id]};void persistState(next,'links',id)};const createSpace=()=>{const name=spaceName.trim()||event.context.topic||'Smart Intelligence Space';const space={id:`space-${Date.now()}`,name,purpose:spacePurpose.trim(),visibility,created_at:new Date().toISOString()};const next={...state,space};void persistState(next,'space',space).then(()=>setSpaceOpen(false)).catch(()=>undefined)};

