import{useMemo,useState}from'react';
import type{CSSProperties,ReactNode}from'react';
import type{IntelligentEvent,Lens,Perspective as EventPerspective}from'./types';

type BoardProps={event:IntelligentEvent};type ActionKey='favorite'|'save'|'like'|'love';type Persisted={favorite:boolean;save:boolean;like:boolean;love:boolean;rating:number;comments:string[];links:string[];space?:{id:string;name:string;purpose:string;visibility:string;created_at:string}};
const STORE='nayanet:smart-feed-board:v4';const emptyState=():Persisted=>({favorite:false,save:false,like:false,love:false,rating:0,comments:[],links:[]});const load=(key:string):Persisted=>{try{return JSON.parse(localStorage.getItem(key)||'null')||emptyState()}catch{return emptyState()}};const persist=(key:string,s:Persisted)=>{try{localStorage.setItem(key,JSON.stringify(s))}catch{}};
const lensCopy:Record<Lens,string>={collective:'Shared intelligence that has crossed its consent boundary and is ready to compound.',personal:'Your private intelligence view — what matters to you, what you learned, and what you can use.',activity:'What happened, when it happened, and how the intelligence changed.'};
const related=[{id:'runtime-truth',title:'Source Intent Is Not Runtime Truth',summary:'Verify source → artifact → deployment → exact runtime → independent observation.'},{id:'surgical-evolution',title:'Adaptive Reconstruction + Surgical Evolution',summary:'Improve the existing system without destroying the system that already works.'},{id:'authority-boundary',title:'Intelligence ≠ Authority',summary:'Capability, confidence, persistence, and optimization do not create permission.'}];
function Button({children,onClick,active=false,kind='normal',disabled=false}:{children:ReactNode;onClick?:()=>void;active?:boolean;kind?:'normal'|'primary'|'gold';disabled?:boolean}){return <button className={`sfb-btn ${kind} ${active?'active':''}`} onClick={onClick} disabled={disabled}>{children}</button>}
const icons:Record<string,string>={HUMAN:'◉',CHILD:'◌',GRANDMA:'◈',NAYA:'✦',MACHINE:'⬡',WEAVER:'◇',WISDOM:'◆'};
const tones:Record<string,string>={HUMAN:'#ff2fa4',CHILD:'#8b42ff',GRANDMA:'#3d58ff',NAYA:'#16a6ff',MACHINE:'#26c875',WEAVER:'#ffd11a',WISDOM:'#d86cff'};
function Perspective({label,body,tone}:{label:string;body:string;tone:string}){return <section className={`sfb-perspective sfb-${label.toLowerCase()}`} style={{'--tone':tone}as CSSProperties}><div className="sfb-perspective-head"><span className="sfb-icon-orb">{icons[label]||'•'}</span><div><b>{label} NOTE</b><small>{label==='HUMAN'?'Lived experience':label==='CHILD'?'Simple truth':label==='GRANDMA'?'Enduring wisdom':label==='NAYA'?'AI interpretation':label==='MACHINE'?'Operational intelligence':label==='WISDOM'?'Durable perspective':'Integrated synthesis'}</small></div></div><p>{body}</p></section>}
function availablePerspectives(event:IntelligentEvent):EventPerspective[]{return event.perspectives.filter(p=>p.body.trim())}
export function SmartFeedBoard({event}:BoardProps){const[lens,setLens]=useState<Lens>('collective');const[query,setQuery]=useState('');const[askOpen,setAskOpen]=useState(false);const[ask,setAsk]=useState('');const[connectOpen,setConnectOpen]=useState(false);const[spaceOpen,setSpaceOpen]=useState(false);const[status,setStatus]=useState('');const[spaceName,setSpaceName]=useState('');const[spacePurpose,setSpacePurpose]=useState('Turn this intelligence into a place to learn and act together.');const[visibility,setVisibility]=useState('private');const storageKey=`${STORE}:${event.event_id}`;const[state,setState]=useState<Persisted>(()=>load(storageKey));const[comment,setComment]=useState('');
const saveState=(next:Persisted)=>{setState(next);persist(storageKey,next)};const searchable=useMemo(()=>[event.source.label,event.human_input.raw,event.context.topic||'',...(event.context.tags||[]),event.naya_interpretation.observation||'',event.naya_interpretation.interpretation||'',event.naya_interpretation.recommendation||'',event.weaver_synthesis.summary||'',event.lesson.text||'',event.meaning.text||'',event.action.text||'',event.whats_in_it_for_you||'',...event.perspectives.map(p=>p.body)].join(' ').toLowerCase(),[event]);const matches=query.trim()===''||searchable.includes(query.trim().toLowerCase());const nayaAnswer=useMemo(()=>{const q=ask.trim().toLowerCase();if(!q)return'Ask about the intelligence, evidence, meaning, or next action.';if(q.includes('why')||q.includes('matter'))return event.meaning.text||event.meaning.significance||'Meaning has not been recorded for this intelligence yet.';if(q.includes('next')||q.includes('action')||q.includes('apply')||q.includes('use'))return event.action.text||'No next action has been recorded for this intelligence yet.';if(q.includes('trust')||q.includes('proof')||q.includes('source'))return`Trust: ${event.trust.level}. Verification: ${event.machine_evidence.verification_state}. Uncertainty: ${event.naya_interpretation.uncertainty||'Not stated.'}`;if(q.includes('connect')||q.includes('related'))return related.map(x=>x.title).join(' · ');return event.weaver_synthesis.summary||'No synthesis recorded.'},[ask,event]);const toggle=(key:ActionKey)=>saveState({...state,[key]:!state[key]});const rate=(n:number)=>saveState({...state,rating:n});const addComment=()=>{if(!comment.trim())return;saveState({...state,comments:[...state.comments,comment.trim()]});setComment('');setStatus('COMMENT SAVED TO THIS DEVICE')};const connect=(id:string)=>{if(state.links.includes(id))return;saveState({...state,links:[...state.links,id]});setStatus('INTELLIGENCE LINK SAVED TO THIS DEVICE')};const createSpace=()=>{const name=spaceName.trim()||event.context.topic||'Smart Intelligence Space';saveState({...state,space:{id:`space-${Date.now()}`,name,purpose:spacePurpose.trim(),visibility,created_at:new Date().toISOString()}});setSpaceOpen(false);setStatus(`SMART SPACE DRAFT SAVED · ${name}`)};const share=async()=>{const text=`${event.source.label}\n\n${event.human_input.raw}\n\nNayaNET Intelligent Block`;try{if(navigator.share)await navigator.share({title:event.source.label,text});else await navigator.clipboard.writeText(text);setStatus('SHARE READY')}catch{setStatus('SHARE CANCELLED')}};const perspectives=availablePerspectives(event);
return <article className="smart-feed-board" data-event-id={event.event_id} data-spectrum="0"><header className="sfb-header"><div className="sfb-title-group"><div className="sfb-eyebrow"><span className="sfb-led"/>INTELLIGENT BLOCK · {lens.toUpperCase()}</div><h2>{event.source.label}</h2><div className="sfb-meta"><span>{new Date(event.created_at).toLocaleDateString()}</span><span>·</span><span>{event.status}</span><span>·</span><span>{event.privacy.visibility}</span></div></div><div className="sfb-header-actions"><Button onClick={()=>setSpaceOpen(true)} kind="primary">＋ CREATE SPACE</Button><button className={`sfb-icon-button ${state.favorite?'on':''}`}aria-label="Favorite intelligence"onClick={()=>toggle('favorite')}>{state.favorite?'★':'☆'}</button><button className={`sfb-icon-button ${state.save?'on':''}`}aria-label="Save intelligence"onClick={()=>toggle('save')}>{state.save?'▣':'□'}</button></div></header>
<nav className="sfb-lenses" role="tablist" aria-label="Intelligence views">{(['activity','collective','personal']as Lens[]).map(x=><button key={x} role="tab" aria-selected={lens===x} className={lens===x?'selected':''} onClick={()=>setLens(x)}><span>{x==='activity'?'◷':x==='collective'?'◎':'◉'}</span>{x==='personal'?'PERSONAL INTELLIGENCE':x==='collective'?'COLLECTIVE INTELLIGENCE':'ACTIVITY FEED'}</button>)}</nav><div className={`sfb-lens-note lens-${lens}`}><strong>{lens==='activity'?'ACTIVITY':lens==='collective'?'INTELLIGENCE':'PERSONAL'}</strong><span>{lensCopy[lens]}</span></div>
<div className="sfb-search"><span className="search-glyph">⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search this intelligence" placeholder="Search inside this intelligence…"/><span className="sfb-search-state">{matches?'READY':'NO MATCH'}</span></div>
{!matches?<div className="sfb-empty">No matching intelligence inside this event.</div>:<><section className="sfb-nutshell"><div className="nutshell-mark">✦</div><div className="nutshell-copy"><div className="sfb-label">IN A NUTSHELL</div><h3>{event.weaver_synthesis.summary||event.source.label}</h3><p>{event.naya_interpretation.observation||event.human_input.raw}</p></div><Button onClick={()=>setAskOpen(true)} kind="primary">✦ ASK NAYA</Button></section>
<section className="sfb-perspectives">{perspectives.map((p,index)=><Perspective key={`${p.label}-${index}`} label={p.label} body={p.body} tone={tones[p.label]||'#875CFF'}/>)}{event.naya_interpretation.interpretation&&<Perspective label="NAYA" body={event.naya_interpretation.interpretation} tone={tones.NAYA}/>}<Perspective label="MACHINE" body={event.machine_evidence.items.length?event.machine_evidence.items.join(' · '):'Machine evidence has not been recorded.'} tone={tones.MACHINE}/></section>
<section className="sfb-meaning"><div className="meaning-learn"><span>ADAPTER LEARNING</span><h3>{event.lesson.text?'What was learned.':'Learning not yet recorded.'}</h3><p>{event.lesson.text||'No adapter learning has been recorded for this intelligence event.'}</p></div><div className="meaning-means"><span>WHAT IT MEANS</span><h3>{event.meaning.significance||'Meaning not yet recorded.'}</h3><p>{event.meaning.text||'The significance of this intelligence has not yet been recorded.'}</p></div></section>
<section className="sfb-action"><div><span>WHAT CAN I DO?</span><h3>{event.action.status||'Next action'}</h3></div><p>{event.action.text||'No next action has been recorded for this intelligence yet.'}</p></section>
<section className="sfb-apply" aria-label="How to apply or use this intelligence"><div className="sfb-apply-icon">↳</div><div><span>HOW TO APPLY / HOW TO USE</span><h3>Turn understanding into action.</h3><p>{event.action.text||'Application guidance has not been recorded for this intelligence yet. Naya will not invent a use case.'}</p></div><Button kind="gold" onClick={()=>setStatus(event.action.text?'APPLICATION GUIDANCE READY':'APPLICATION GUIDANCE NOT RECORDED')} disabled={!event.action.text}>APPLY / USE</Button></section>
<section className="sfb-value"><div><span>WHAT'S IN IT FOR YOU</span><h3>{event.whats_in_it_for_you?'Human value is recorded.':'Human value not yet recorded.'}</h3></div><p>{event.whats_in_it_for_you||'The system will not invent a benefit. A human-value translation must be recorded before one is presented as intelligence.'}</p></section>
<section className="sfb-trust"><div className="sfb-trust-head"><div><div className="sfb-label">TRUST · PROVENANCE · PRIVACY</div><h3>{event.trust.level.toUpperCase()} · {event.machine_evidence.verification_state.toUpperCase()}</h3></div><span className="trust-badge">◉ EVIDENCE BOUND</span></div><div className="sfb-trust-grid"><div><b>SOURCE</b><span>{event.source.label}</span></div><div><b>EVIDENCE</b><span>{event.machine_evidence.items.length?event.machine_evidence.items.join(' · '):'No evidence recorded.'}</span></div><div><b>UNCERTAINTY</b><span>{event.naya_interpretation.uncertainty||'Not stated.'}</span></div><div><b>PRIVACY</b><span>{event.privacy.visibility} · {event.privacy.consent_state}</span></div></div></section>
<section className="sfb-related"><div className="sfb-related-head"><div><div className="sfb-label">RELATED INTELLIGENCE</div><h3>Connect what matters.</h3></div><Button onClick={()=>setConnectOpen(!connectOpen)} active={connectOpen}>↔ {state.links.length?`${state.links.length} LINKED`:'CONNECT'}</Button></div>{connectOpen&&<div className="sfb-related-list">{related.map(r=><button key={r.id} className={state.links.includes(r.id)?'linked':''} onClick={()=>connect(r.id)}><b>{state.links.includes(r.id)?'✓ ':''}{r.title}</b><span>{r.summary}</span></button>)}</div>}</section>
<section className="sfb-actions"><Button onClick={()=>toggle('love')}active={state.love}>♥ LOVE</Button><Button onClick={()=>toggle('like')}active={state.like}>♥ LIKE</Button><div className="sfb-rating"><span>RATE / RANK</span>{[1,2,3,4,5].map(n=><button key={n} className={state.rating>=n?'rated':''} onClick={()=>rate(n)}>★</button>)}</div><Button onClick={share}>＋ SHARE</Button></section><section className="sfb-comment"><div><div className="sfb-label">COMMENT</div><p>{state.comments.length?`${state.comments.length} comment${state.comments.length===1?'':'s'}.`:'Add a thought without leaving the intelligence.'}</p></div><div className="sfb-comment-row"><input value={comment} onChange={e=>setComment(e.target.value)} placeholder="Add a contextual comment…"/><Button onClick={addComment} disabled={!comment.trim()} kind="primary">POST</Button></div></section></>}
{status&&<div className="sfb-status"role="status">{status}</div>}{askOpen&&<div className="sfb-modal"role="dialog"aria-modal="true"><div className="sfb-dialog"><div className="sfb-label">ASK NAYA</div><h3>Question this intelligence.</h3><textarea value={ask} onChange={e=>setAsk(e.target.value)} placeholder="Why does this matter? What is the evidence? What should happen next?"/><div className="sfb-answer"><b>NAYA · CONTEXTUAL ANSWER</b><p>{nayaAnswer}</p></div><div className="sfb-modal-actions"><Button onClick={()=>setAskOpen(false)}>CLOSE</Button><Button onClick={()=>setAsk('Why does this matter?')}kind="primary">ASK WHY</Button><Button onClick={()=>setAsk('What is the proof?')}>ASK PROOF</Button><Button onClick={()=>setAsk('What should happen next?')}>ASK NEXT</Button></div></div></div>}{spaceOpen&&<div className="sfb-modal"role="dialog"aria-modal="true"><div className="sfb-dialog"><div className="sfb-label">CREATE SMART SPACE</div><h3>Turn this intelligence into a Smart Space.</h3><label>SPACE NAME<input value={spaceName}onChange={e=>setSpaceName(e.target.value)}placeholder="Name this Smart Space"/></label><label>PURPOSE<textarea value={spacePurpose}onChange={e=>setSpacePurpose(e.target.value)}/></label><label>VISIBILITY<select value={visibility}onChange={e=>setVisibility(e.target.value)}><option value="private">Private</option><option value="invited">Invite only</option><option value="collective">Collective · requires consent</option></select></label><div className="sfb-modal-actions"><Button onClick={()=>setSpaceOpen(false)}>CANCEL</Button><Button onClick={createSpace}kind="primary">SAVE SPACE DRAFT</Button></div></div></div>}</article>}
