import { useEffect, useState } from 'react';
import { useIdentity } from '../../../identity/session';

type Space={id:string;name:string;purpose:string;visibility:string;created_at:string;owner_member_id?:string};
export function SmartSpacesSurface(){
 const identity=useIdentity();const[spaces,setSpaces]=useState<Space[]>([]);const[name,setName]=useState('');const[purpose,setPurpose]=useState('');const[visibility,setVisibility]=useState<'private'|'shared'>('private');const[busy,setBusy]=useState(true);const[acting,setActing]=useState('');const[status,setStatus]=useState('');
 const load=async()=>{setBusy(true);setStatus('');try{const rt=window.NayaAssistantRuntime;if(!rt)throw new Error('ASSISTANT_RUNTIME_UNAVAILABLE');if(!rt.snapshot()?.authenticated)throw new Error('AUTH_REQUIRED');setSpaces((await rt.listSpaces()) as Space[])}catch(e){setSpaces([]);setStatus(e instanceof Error?e.message:'SMART_SPACES_LOAD_FAILED')}finally{setBusy(false)}};
 useEffect(()=>{if(!identity.is_authenticated){setBusy(false);return}void load()},[identity.is_authenticated]);
 const create=async()=>{if(!name.trim()||!purpose.trim())return;setActing('create');setStatus('CREATING SPACE THROUGH CANONICAL BOUNDARY…');try{const rt=window.NayaAssistantRuntime;if(!rt)throw new Error('ASSISTANT_RUNTIME_UNAVAILABLE');const out=await rt.createSpace({name:name.trim(),purpose:purpose.trim(),visibility});if(!out?.id)throw new Error('CANONICAL_SPACE_ID_NOT_RETURNED');setName('');setPurpose('');setStatus('SPACE CREATED · '+out.id);await load()}catch(e){setStatus('SPACE CREATE BLOCKED · '+(e instanceof Error?e.message:'CREATE_FAILED'))}finally{setActing('')}};
 const join=async(space:Space)=>{setActing(space.id);setStatus('JOINING '+space.name+'…');try{const rt=window.NayaAssistantRuntime;if(!rt)throw new Error('ASSISTANT_RUNTIME_UNAVAILABLE');await rt.joinSpace(space.id);setStatus('SPACE JOINED · '+space.name);await load()}catch(e){setStatus('SPACE JOIN BLOCKED · '+(e instanceof Error?e.message:'JOIN_FAILED'))}finally{setActing('')}};
 const leave=async(space:Space)=>{setActing(space.id);setStatus('LEAVING '+space.name+'…');try{const rt=window.NayaAssistantRuntime;if(!rt)throw new Error('ASSISTANT_RUNTIME_UNAVAILABLE');await rt.leaveSpace(space.id);setStatus('SPACE LEFT · '+space.name);await load()}catch(e){setStatus('SPACE LEAVE BLOCKED · '+(e instanceof Error?e.message:'LEAVE_FAILED'))}finally{setActing('')}};
 if(!identity.is_authenticated)return <section className="feature-surface" data-surface="spaces"><div className="feature-hero"><div><div className="eyebrow">NAYANET · CONTEXT · CONSENT · COLLABORATION</div><h1>Smart Spaces</h1><p>Permissioned places where intelligence can be shared and compounded.</p></div></div><div className="feature-empty"><b>AUTHENTICATION REQUIRED</b><span>Spaces are governed by the authenticated member boundary.</span></div></section>;
 return <section className="feature-surface" data-surface="spaces"><div className="feature-hero"><div><div className="eyebrow">NAYANET · CONTEXT · CONSENT · COLLABORATION</div><h1>Smart Spaces</h1><p>Create a private or shared Space, join when permitted, and leave deliberately.</p></div><div className="feature-state">AUTHENTICATED · {spaces.length} SPACES</div></div><div className="space-create"><label>SPACE NAME<input value={name} onChange={e=>setName(e.target.value)} placeholder="Name your Space"/></label><label>PURPOSE<input value={purpose} onChange={e=>setPurpose(e.target.value)} placeholder="What is this Space for?"/></label><label>VISIBILITY<select value={visibility} onChange={e=>setVisibility(e.target.value as 'private'|'shared')}><option value="private">PRIVATE</option><option value="shared">SHARED</option></select></label><button onClick={()=>void create()} disabled={!!acting||!name.trim()||!purpose.trim()}>{acting==='create'?'CREATING…':'CREATE SPACE'}</button></div>{status&&<div className="feature-status" role="status">{status}</div>}{busy?<div className="feature-empty"><b>READING CANONICAL SPACES…</b><span>Loading permissioned Spaces from the governed runtime.</span></div>:spaces.length?<div className="space-grid">{spaces.map(space=><article className="space-card" key={space.id}><div><span className="feature-card-kicker">SMART SPACE · {space.visibility.toUpperCase()}</span><h2>{space.name}</h2><p>{space.purpose}</p></div><div className="space-meta"><span>CREATED · {new Date(space.created_at).toLocaleString()}</span><span>SPACE · {space.id}</span></div><div className="space-actions"><button onClick={()=>void join(space)} disabled={!!acting}>JOIN</button><button onClick={()=>void leave(space)} disabled={!!acting}>LEAVE</button></div></article>)}</div>:<div className="feature-empty"><b>NO SMART SPACES</b><span>Create the first Space above.</span></div>}<div className="feature-foot"><span>GOVERNED PATH</span><b>SPACE → MEMBERSHIP → INTELLIGENCE</b><span>•</span><span>CONNECTION ≠ PERMISSION</span></div></section>;
}
