export const CANONICAL_EXPERIENCE_MARKERS = [
  'NayaNET','Intelligent Hub','IDENTITY','ACTIVITY FEED','PERSONAL INTELLIGENCE','COLLECTIVE INTELLIGENCE',
  'Ask Naya','Create Smart Space','NUTSHELL','HUMAN','CHILD','GRANDMA','NAYA','MACHINE','WEAVER','LESSON',
  'MEANING','ACTION','TRUST','RELATED INTELLIGENCE','Favorite intelligence','Save intelligence','RATE / RANK',
  'COMMENT','SHARE','CONNECT','NAYANET-HUB-REACT-CANONICAL',
  'SMART FEED','COLLECTIVE','PERSONAL','ACTIVITY','HUMAN NOTE','CHILD VIEW','GRANDMA VIEW','NAYA NOTE',
  'MACHINE NOTE','ADAPTER LEARNING','WHAT IT MEANS',"WHAT'S IN IT FOR YOU",'SEARCH INTELLIGENCE','SMART SPACES',
  'INTELLIGENT LIBRARY','NAYANET-HUB-509-CANONICAL'
] as const;
