import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { createRemoteJWKSet, jwtVerify } from "npm:jose@6";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-idempotency-key","Access-Control-Allow-Methods":"POST, OPTIONS"};
const OWNER="SoulSchoolAcademy"; const REPO="NayaPOWER"; const BRANCH="main"; const PROJECT="NayaPOWER"; const DEPLOY_WORKFLOW="assistant-cloudflare-hub-release.yml"; const DEPLOY_ACTION="deploy_nayanet_hub_canonical"; const PROJECTION_WORKFLOW="project-canonical-smart-note.yml"; const PROJECTION_ACTION="smart_note_github_projection";
const REPO_API=`https://api.github.com/repos/${OWNER}/${REPO}`;
const CANONICAL_ISSUER="https://dahisasgpfvziswqvmvm.supabase.co/auth/v1";
const OBSERVED_ISSUER="https://alt.supabase.io/auth/v1";
const ALLOWED_ISSUERS=new Set([CANONICAL_ISSUER,OBSERVED_ISSUER]);
const JWKS=new Map<string,ReturnType<typeof createRemoteJWKSet>>();
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}})}
function sha40(s:string){return /^[0-9a-f]{40}$/i.test(s)}
function slug(value:string,limit=64){return String(value||'').replace(/[^a-zA-Z0-9]+/g,'-').replace(/^-+|-+$/g,'').toLowerCase().slice(0,limit)||'smart-note'}
function topicSlug(value:string){return slug(value).split('-').filter(Boolean).slice(0,3).join('-')||'smart-note'}
async function waitForProjectionWorkflow(token:string,transactionId:string,startedAt:string,timeoutMs=120000){
  const runName=`Project Canonical Smart Note - ${transactionId}`;
  const deadline=Date.now()+timeoutMs;
  let last:any=null;
  while(Date.now()<deadline){
    const runs=await github(`/actions/workflows/${encodeURIComponent(PROJECTION_WORKFLOW)}/runs?branch=${encodeURIComponent(BRANCH)}&event=workflow_dispatch&per_page=20`,{method:'GET'},token);
    if(!runs.ok)throw new Error(`GITHUB_PROJECTION_RUN_LOOKUP_FAILED:${runs.status}`);
    const candidates=Array.isArray(runs.data?.workflow_runs)?runs.data.workflow_runs:[];
    const match=candidates.filter((r:any)=>String(r?.display_title||'')===runName || String(r?.name||'')===runName)
      .sort((a:any,b:any)=>new Date(String(b.created_at||0)).getTime()-new Date(String(a.created_at||0)).getTime())[0];
    if(match){
      last=match;
      if(match.status==='completed'){
        if(match.conclusion!=='success')throw new Error(`SMART_NOTE_GITHUB_PROJECTION_FAILED:${match.conclusion||'unknown'}:${match.id}`);
        return {status:'PROJECTION_VERIFIED',run_id:match.id,run_url:match.html_url,started_at:startedAt,completed_at:match.updated_at};
      }
    }
    await new Promise(r=>setTimeout(r,2000));
  }
  throw new Error(`SMART_NOTE_GITHUB_PROJECTION_TIMEOUT:${last?.id||'RUN_NOT_FOUND'}`);
}
async function canonicalSmartLink(sb:any,transactionId:string){
  const {data,error}=await sb.from('v7_smart_note_transactions').select('id,created_at,intelligent_block').eq('id',transactionId).maybeSingle();
  if(error)throw error;
  if(!data)throw new Error('CANONICAL_TRANSACTION_NOT_FOUND_AFTER_PROJECTION');
  const block=data.intelligent_block||{}, identity=block.identity||{}, meta=block.metadata||{};
  const ib=String(identity.intelligent_block_id||'').trim();
  if(!/^IB-\d{6}$/.test(ib))throw new Error('RECEIVER_ISSUED_IB_ID_MISSING_AFTER_PROJECTION');
  const occurred=String(block?.time?.occurred_at||data.created_at||'');
  const d=new Date(occurred);
  if(Number.isNaN(d.getTime()))throw new Error('CANONICAL_TRANSACTION_TIMESTAMP_INVALID');
  const category=slug(String(meta.projection_category||'system'));
  const topic=topicSlug(String(meta.projection_topic||block?.meaning?.subject||'smart-note'));
  const path=`.naya/memory/smart-notes/${d.getUTCFullYear()}/${String(d.getUTCMonth()+1).padStart(2,'0')}/${String(d.getUTCDate()).padStart(2,'0')}/${category}/${topic}/${ib}/smart-note.md`;
  return `https://github.com/${OWNER}/${REPO}/blob/${BRANCH}/${path}`;
}
async function github(path:string,init:RequestInit,token:string){const r=await fetch(`${REPO_API}${path}`,{...init,headers:{"Accept":"application/vnd.github+json","Authorization":`Bearer ${token}`,"X-GitHub-Api-Version":"2022-11-28","User-Agent":"NayaPOWER-Execution-Bridge",...(init.headers||{})}});const text=await r.text();let data:unknown;try{data=text?JSON.parse(text):null}catch{data=text}return {ok:r.ok,status:r.status,data}}
function jwtMeta(token:string){try{const parts=token.split(".");if(parts.length!==3)return {jwt_shape:false};const b64=parts[1].replace(/-/g,"+").replace(/_/g,"/");const payload=JSON.parse(atob(b64.padEnd(Math.ceil(b64.length/4)*4,"=")));return {jwt_shape:true,issuer:typeof payload?.iss==="string"?payload.iss:null,audience:typeof payload?.aud==="string"?payload.aud:null,expires_at:typeof payload?.exp==="number"?payload.exp:null,expired:typeof payload?.exp==="number"?payload.exp<=Math.floor(Date.now()/1000):null};}catch{return {jwt_shape:false}}}
function jwksFor(issuer:string){let value=JWKS.get(issuer);if(!value){value=createRemoteJWKSet(new URL(`${issuer}/.well-known/jwks.json`));JWKS.set(issuer,value)}return value}
async function getUser(req:Request){const auth=req.headers.get("Authorization");if(!auth)return {user:null,diagnostic:{header_present:false}};const match=auth.match(/^Bearer\s+(.+)$/i);const token=match?.[1]?.trim();if(!token)return {user:null,diagnostic:{header_present:true,bearer_format:false}};const meta=jwtMeta(token);if(!meta.jwt_shape)return {user:null,diagnostic:{...meta,auth_error:true,auth_error_name:"JWT_SHAPE_ERROR",auth_error_message:"Authorization bearer value is not a three-segment JWT.",auth_error_status:400}};const issuer=meta.issuer;if(typeof issuer!=="string"||!ALLOWED_ISSUERS.has(issuer))return {user:null,diagnostic:{...meta,auth_error:true,auth_error_name:"JWT_ISSUER_NOT_ALLOWED",auth_error_message:"JWT issuer is not an approved NayaPOWER Supabase Auth issuer.",auth_error_status:403}};try{const verified=await jwtVerify(token,jwksFor(issuer),{issuer,audience:"authenticated"});const sub=typeof verified.payload.sub==="string"?verified.payload.sub:"";if(!sub)return {user:null,diagnostic:{...meta,auth_error:true,auth_error_name:"JWT_SUBJECT_REQUIRED",auth_error_message:"Verified JWT does not contain a subject.",auth_error_status:403}};return {user:{id:sub},diagnostic:{...meta,auth_error:false,signature_verified:true,verified_issuer:issuer}}}catch(error){return {user:null,diagnostic:{...meta,auth_error:true,signature_verified:false,auth_error_name:error instanceof Error?error.name:"JWT_VERIFY_ERROR",auth_error_message:error instanceof Error?error.message:String(error),auth_error_status:403}}}}
async function receiptClient(){const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)throw new Error("SUPABASE_SERVICE_ROLE_NOT_CONFIGURED");return createClient(url,key)}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({ok:false,error:"METHOD_NOT_ALLOWED"},405);const requestId=crypto.randomUUID();try{const auth=await getUser(req);if(!auth.user)return json({ok:false,error:"AUTHENTICATED_USER_REQUIRED",request_id:requestId,auth_diagnostic:auth.diagnostic},401);const user=auth.user;const body=await req.json().catch(()=>({}));const commit_sha=typeof body?.commit_sha==="string"?body.commit_sha.trim().toLowerCase():"";const approval=typeof body?.approval==="string"?body.approval.trim():"";const reason=typeof body?.reason==="string"?body.reason.trim():"";const authority_grant_id=typeof body?.authority_grant_id==="string"?body.authority_grant_id.trim():""; const operation=typeof body?.operation==="string"?body.operation.trim():"deploy"; const transaction_id=typeof body?.transaction_id==="string"?body.transaction_id.trim():"";const idem=typeof body?.idempotency_key==="string"&&body.idempotency_key.trim()?body.idempotency_key.trim():req.headers.get("x-idempotency-key")||requestId;const isProjection=operation==="project_smart_note";if(!isProjection&&!sha40(commit_sha))return json({ok:false,error:"EXACT_40_CHAR_COMMIT_SHA_REQUIRED",request_id:requestId},400);if(approval!=="EXPLICIT_APPROVAL_GRANTED")return json({ok:false,error:"EXPLICIT_APPROVAL_REQUIRED",request_id:requestId},403);if(!authority_grant_id)return json({ok:false,error:"AUTHORITY_GRANT_ID_REQUIRED",request_id:requestId},403);if(!isProjection&&!reason)return json({ok:false,error:"DEPLOYMENT_REASON_REQUIRED",request_id:requestId},400);
const ACTION=isProjection?PROJECTION_ACTION:DEPLOY_ACTION;
const WORKFLOW=isProjection?PROJECTION_WORKFLOW:DEPLOY_WORKFLOW;
if(isProjection&&!transaction_id)return json({ok:false,error:"TRANSACTION_ID_REQUIRED",request_id:requestId},400);const userClient=createClient(Deno.env.get("SUPABASE_URL")||"",Deno.env.get("SUPABASE_ANON_KEY")||"",{global:{headers:{Authorization:req.headers.get("Authorization")||""}}});const{data:validated,error:validationError}=await userClient.rpc("nayanet_validate_authority_grant",{p_grant_id:authority_grant_id,p_action:ACTION,p_target:isProjection?transaction_id:commit_sha});if(validationError||validated?.status!=="AUTHORIZED")return json({ok:false,error:"AUTHORITY_GRANT_VALIDATION_FAILED",request_id:requestId,detail:validationError?.message??validated},403);const sb=await receiptClient();const {data:existing}=await sb.from("nayanet_execution_receipts").select("id,status,evidence,observed_result,created_at").eq("project_id",PROJECT).contains("evidence",[{idempotency_key:idem}]).limit(1).maybeSingle();if(existing){
  if(isProjection){
    const projectionEvidence=Array.isArray(existing?.evidence)?existing.evidence.find((e:any)=>e?.stage==="projection"):null;
    const smartLink=typeof projectionEvidence?.smart_link==="string"?projectionEvidence.smart_link:await canonicalSmartLink(sb,transaction_id);
    if(!/^https:\/\/github\.com\/SoulSchoolAcademy\/NayaPOWER\/blob\/main\/.+\/IB-\d{6}\/smart-note\.md$/.test(smartLink))throw new Error("IDEMPOTENT_SMART_LINK_INVALID");
    return json({ok:true,idempotent:true,pipeline:"PROJECTION_VERIFIED",smart_link:smartLink,projection_verification:{status:"PROJECTION_VERIFIED",run_id:projectionEvidence?.run_id||null,run_url:projectionEvidence?.run_url||null,verified_at:projectionEvidence?.verified_at||existing?.created_at||null},receipt:existing,request_id:requestId});
  }
  return json({ok:true,idempotent:true,receipt:existing,request_id:requestId});
}const token=Deno.env.get("GITHUB_TOKEN")||Deno.env.get("GITHUB_ACTIONS_TOKEN");if(!token){const evidence=[{request_id:requestId,idempotency_key:idem,stage:"credential",status:"NOT_OBSERVABLE",reason:"No supported server-side GitHub dispatch credential is configured for this execution boundary."},{stage:"authorization",user_id:user.id,approval,reason}];await sb.from("nayanet_execution_receipts").insert({user_id:user.id,project_id:PROJECT,revision:0,action:ACTION,expected_result:"Canonical workflow dispatch must be authorized and accepted by GitHub.",observed_result:"GitHub dispatch credential is not observable/configured.",status:"BLOCKED",evidence,learning:["Execution boundary exists; credential boundary remains external."]});return json({ok:false,error:"GITHUB_DISPATCH_CREDENTIAL_NOT_OBSERVABLE",status:"BLOCKED_EXTERNAL_CREDENTIAL",request_id:requestId},503)}const refCheck=await github(`/git/ref/heads/${BRANCH}`,{method:"GET"},token);if(!refCheck.ok)return json({ok:false,error:"GITHUB_REF_LOOKUP_FAILED",status:refCheck.status,request_id:requestId},502);const mainSha=typeof refCheck.data?.object?.sha==="string"?refCheck.data.object.sha.toLowerCase():"";if(!sha40(mainSha))return json({ok:false,error:"CURRENT_MAIN_SHA_NOT_OBSERVABLE",request_id:requestId},502);if(!isProjection&&commit_sha!==mainSha){const evidence=[{request_id:requestId,idempotency_key:idem,stage:"source_binding",status:"FAILED",requested_sha:commit_sha,current_main_sha:mainSha,reason:"Requested deployment SHA is not the exact current main branch tip."},{stage:"authorization",user_id:user.id,approval,reason}];await sb.from("nayanet_execution_receipts").insert({user_id:user.id,project_id:PROJECT,revision:0,action:ACTION,expected_result:"Requested SHA must equal the exact current main branch tip before public deployment dispatch.",observed_result:`Requested ${commit_sha}; current main is ${mainSha}.`,status:"FAILED",evidence,learning:["Exact-source deployment is fail-closed when the requested SHA is not current main."]});return json({ok:false,error:"REQUESTED_SHA_NOT_CURRENT_MAIN",requested_sha:commit_sha,current_main_sha:mainSha,request_id:requestId},409)}if(!isProjection){const commitCheck=await github(`/commits/${commit_sha}`,{method:"GET"},token);if(!commitCheck.ok)return json({ok:false,error:"REQUESTED_COMMIT_NOT_OBSERVABLE",status:commitCheck.status,request_id:requestId},400)}const dispatchStartedAt=new Date().toISOString();
const dispatch=await github(`/actions/workflows/${WORKFLOW}/dispatches`,{method:"POST",body:JSON.stringify({ref:BRANCH,inputs:isProjection?{transaction_id,approval:approval==="EXPLICIT_APPROVAL_GRANTED"?"EXPLICIT_PROJECTION_APPROVAL_GRANTED":approval}:{commit_sha,approval,reason}})},token);if(!dispatch.ok){const evidence=[{request_id:requestId,idempotency_key:idem,stage:"dispatch",status:"FAILED",http_status:dispatch.status},{stage:"authorization",user_id:user.id,approval,reason},{stage:"source",commit_sha,ref:BRANCH,workflow:WORKFLOW}];await sb.from("nayanet_execution_receipts").insert({user_id:user.id,project_id:PROJECT,revision:0,action:ACTION,expected_result:"GitHub accepts workflow_dispatch for the exact requested SHA.",observed_result:`GitHub rejected dispatch with HTTP ${dispatch.status}.`,status:"FAILED",evidence,learning:["Dispatch credential exists but workflow dispatch was rejected."]});return json({ok:false,error:"GITHUB_WORKFLOW_DISPATCH_FAILED",http_status:dispatch.status,request_id:requestId},502)}let projectionVerification:any=null;let smartLink:string|null=null;if(isProjection){projectionVerification=await waitForProjectionWorkflow(token,transaction_id,dispatchStartedAt);smartLink=await canonicalSmartLink(sb,transaction_id);}
const evidence=[{request_id:requestId,idempotency_key:idem,stage:"authorization",status:"PASS",user_id:user.id,approval,reason},{stage:"source",status:"PASS",commit_sha,ref:BRANCH,current_main_sha:mainSha},{stage:"dispatch",status:"PASS",workflow:WORKFLOW,github_http_status:204,dispatched_at:dispatchStartedAt},...(isProjection?[{stage:"projection",status:"PASS",run_id:projectionVerification.run_id,run_url:projectionVerification.run_url,verified_at:projectionVerification.completed_at,smart_link:smartLink}]:[])];const {data:receipt,error:receiptError}=await sb.from("nayanet_execution_receipts").insert({user_id:user.id,project_id:PROJECT,revision:0,action:ACTION,expected_result:isProjection?"Canonical projection workflow fetches the receiver transaction, deterministically renders the Smart Note, commits only the exact projection, and verifies byte identity from main.":"Canonical workflow executes exact SHA, deploys Cloudflare, and independently verifies public runtime.",observed_result:isProjection?"Canonical Smart Note projection completed successfully and the direct GitHub Smart Link was verified from the receiver transaction.":"GitHub accepted workflow_dispatch; downstream workflow execution is now authoritative for build/deploy/verification.",status:isProjection?"SUCCESS":"PARTIAL",evidence,learning:[isProjection?"Smart Note capture now closes the receiver-to-GitHub evidence boundary before reporting completion.":"Direct execution bridge successfully handed the exact current main SHA deployment request to the canonical GitHub workflow."],authority_grant_id:authority_grant_id,authority_issuer_id:validated.issuer_id,authority_scope:validated.scope,authority_actions:validated.actions,authority_constraints:validated.constraints,authority_status_at_execution:validated.grant_status,authority_source_event_id:validated.source_event_id,authority_validated_at:new Date().toISOString()}).select().single();if(receiptError)throw receiptError;return json({ok:true,pipeline:isProjection?"PROJECTION_VERIFIED":"DISPATCH_ACCEPTED",request_id:requestId,workflow:WORKFLOW,commit_sha,ref:BRANCH,current_main_sha:mainSha,authority_grant_id,projection_verification:projectionVerification,smart_link:smartLink,receipt});}catch(error){console.error("NAYANET_GITHUB_DISPATCH_ERROR",String(error));return json({ok:false,error:"EXECUTION_BRIDGE_FAILED",detail:String(error),request_id:requestId},500)}});
