import {useEffect,useState} from 'react';
import {useIdentity} from '../identity/session';

export function DreamSurface(){
 const identity=useIdentity(); const [events,setEvents]=useState<any[]>([]); const [replays,setReplays]=useState<any[]>([]); const [selected,setSelected]=useState(''); const [status,setStatus]=useState(''); const [busy,setBusy]=useState(false);
 useEffect(()=>{let live=true;(async()=>{if(!identity.is_authenticated)return;try{const rt=window.NayaAssistantRuntime;if(!rt)throw new Error('DREAM_RUNTIME_UNAVAILABLE');const [e,r]=await Promise.all([rt.retrieve(),rt.listDreamReplays()]);if(live){setEvents(Array.isArray(e)?e:[]);setReplays(Array.isArray(r)?r:[]);setSelected(e?.[0]?.event_id||'')}}catch(err){if(live)setStatus(err instanceof Error?err.message:'DREAM_LOAD_FAILED')}})();return()=>{live=false}},[identity.is_authenticated]);
 const dream=async()=>{if(!selected)return;setBusy(true);setStatus('DREAM REPLAY RUNNING…');try{const rt=window.NayaAssistantRuntime;if(!rt?.dreamReplay)throw new Error('DREAM_RUNTIME_UNAVAILABLE');const replay=await rt.dreamReplay({event_id:selected,idempotency_key:'hub-dream-'+selected});setReplays(prev=>[replay,...prev.filter(x=>x.id!==replay.id)]);setStatus('DREAM REPLAY VERIFIED · '+String(replay.id||'REPLAY'))}catch(e){setStatus(e instanceof Error?e.message:'DREAM_REPLAY_FAILED')}finally{setBusy(false)}};
 return <section className="feature-surface" data-surface="dream"><div className="feature-hero"><div><div className="eyebrow">NAYANET · DREAM · REPLAY · SYNTHESIS</div><h1>Dream</h1><p>Replay preserved intelligence into a governed learning candidate without changing authority.</p></div><div className="feature-state">{identity.is_authenticated?'AUTHENTICATED':'AUTHENTICATION REQUIRED'} · {replays.length} REPLAYS</div></div>
 {!identity.is_authenticated?<div className="feature-empty"><b>AUTHENTICATION REQUIRED</b><span>Dream operates only inside the authenticated intelligence boundary.</span></div>:<><div className="feature-toolbar"><label><span>⌕</span><select value={selected} onChange={e=>setSelected(e.target.value)} aria-label="Dream source">{events.map(e=><option key={e.event_id} value={e.event_id}>{e.title||e.event_id}</option>)}</select></label><button onClick={()=>void dream()} disabled={busy||!selected}>{busy?'DREAMING…':'✦ DREAM REPLAY'}</button><span>{events.length} SOURCES</span></div>{status&&<div className="feature-status" role="status">{status}</div>}{replays.length?<div className="feature-cards">{replays.map((r,i)=><article className="feature-card" key={r.id||i}><div className="feature-card-head"><div><span className="feature-card-kicker">DREAM REPLAY</span><h2>{String(r.id||'Replay')}</h2></div><span className="feature-card-status">{String(r.status||'RECORDED')}</span></div><p>{String(r.summary||r.description||'Deterministic replay of preserved intelligence.')}</p><div className="feature-card-meta"><span>EVENT · {String(r.event_id||selected)}</span><span>CANONICAL · nayanet_dream_replays</span></div></article>)}</div>:<div className="feature-empty"><b>DREAM IS READY</b><span>Select preserved intelligence and run a governed Dream replay.</span></div>}</>}
 <div className="feature-foot"><span>GOVERNANCE</span><b>CAPABILITY DOES NOT CREATE AUTHORITY</b><span>•</span><span>PRIVATE BY DEFAULT · SHARED BY CHOICE</span></div></section>;
}
