const ALLOWED=new Set(['cold_restore','restore','retrieve','understand']);
const JSON_HEADERS={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'};
const response=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:JSON_HEADERS});
function bearer(request){const v=request.headers.get('Authorization')||'';return v.startsWith('Bearer ')&&v.length>7?v:null;}
async function canonical(request,env,action,body={}){const token=bearer(request);if(!token)return response({ok:false,error:'AUTHORIZATION_REQUIRED'},401);const base=String(env.SUPABASE_URL||'').replace(/\/$/,'');const anon=String(env.SUPABASE_ANON_KEY||'');if(!base||!anon)return response({ok:false,error:'CANONICAL_RUNTIME_NOT_CONFIGURED'},503);const upstream=await fetch(base+'/functions/v1/nayanet-compound-intelligence',{method:'POST',headers:{Authorization:token,apikey:anon,'Content-Type':'application/json'},body:JSON.stringify({...body,action})});const payload=await upstream.json().catch(()=>({ok:false,error:'INVALID_CANONICAL_RESPONSE'}));return response({ok:upstream.ok,transport:'nayanet-universal-agent-interface',canonical_action:action,result:payload},upstream.status);}
async function canonicalWithMandatoryColdRestore(request,env,action,body={}) {
  const preflight = await canonical(request, env, 'cold_restore', {});
  if (!preflight.ok) return preflight;
  const preflightBody = await preflight.clone().json().catch(() => ({}));
  const actionResponse = await canonical(request, env, action, body);
  const actionBody = await actionResponse.json().catch(() => ({}));
  return response({
    ok: actionResponse.ok,
    transport: 'nayanet-universal-agent-interface',
    mandatory_pre_action_restore: preflightBody,
    canonical_action: action,
    result: actionBody
  }, actionResponse.status);
}

const TOOLS=[{name:'nayanet_cold_restore',description:'Mandatory 14-question cold-start Project Intelligence restore before consequential agent action.',inputSchema:{type:'object',properties:{},additionalProperties:false}},{name:'nayanet_restore',description:'Restore authorized Project Intelligence from the canonical NayaPOWER runtime.',inputSchema:{type:'object',properties:{},additionalProperties:false}},{name:'nayanet_retrieve',description:'Retrieve canonical NayaNET intelligence by query.',inputSchema:{type:'object',required:['query'],properties:{query:{type:'string',minLength:1},limit:{type:'integer',minimum:1,maximum:50}}}},{name:'nayanet_understand',description:'Advance understanding through the canonical NayaPOWER runtime.',inputSchema:{type:'object',additionalProperties:true}}];
async function mcp(request,env){const token=bearer(request);if(!token)return response({jsonrpc:'2.0',id:null,error:{code:-32001,message:'AUTHORIZATION_REQUIRED'}},401);let body;try{body=await request.json()}catch{return response({jsonrpc:'2.0',id:null,error:{code:-32700,message:'PARSE_ERROR'}},400)}const id=body.id??null,method=String(body.method||'');if(method==='initialize')return response({jsonrpc:'2.0',id,result:{protocolVersion:String(body.params?.protocolVersion||'2025-06-18'),capabilities:{tools:{}},serverInfo:{name:'nayanet-universal-agent-interface',version:'1.0.0'}}});if(method==='notifications/initialized')return new Response(null,{status:204});if(method==='tools/list')return response({jsonrpc:'2.0',id,result:{tools:TOOLS}});if(method==='tools/call'){const name=String(body.params?.name||''),args=body.params?.arguments||{};const action=name==='nayanet_cold_restore'?'cold_restore':name==='nayanet_restore'?'restore':name==='nayanet_retrieve'?'retrieve':name==='nayanet_understand'?'understand':null;if(!action)return response({jsonrpc:'2.0',id,error:{code:-32602,message:'UNKNOWN_TOOL'}},400);const upstream=action==='cold_restore'||action==='restore'?await canonical(request,env,action,args):await canonicalWithMandatoryColdRestore(request,env,action,args),data=await upstream.json();return response({jsonrpc:'2.0',id,result:{content:[{type:'text',text:JSON.stringify(data.result??data)}],isError:!upstream.ok}},upstream.status)}return response({jsonrpc:'2.0',id,error:{code:-32601,message:'METHOD_NOT_FOUND'}},404);}
export default {async fetch(request,env){if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Authorization,Content-Type','Access-Control-Allow-Methods':'POST,OPTIONS'}});const url=new URL(request.url);if(url.pathname==='/health'){if(request.method!=='GET')return response({ok:false,error:'METHOD_NOT_ALLOWED'},405);return response({ok:true,service:'nayanet-universal-agent-interface',canonical:true,version:'1.0.0'});}if(request.method!=='POST')return response({ok:false,error:'METHOD_NOT_ALLOWED'},405);if(url.pathname==='/mcp')return mcp(request,env);const routes={'/v1/cold-restore':'cold_restore','/v1/restore':'restore','/v1/retrieve':'retrieve','/v1/understand':'understand'};const action=routes[url.pathname];if(action&&ALLOWED.has(action)){let body={};try{body=await request.json()}catch{}return action==='cold_restore'||action==='restore'?canonical(request,env,action,body):canonicalWithMandatoryColdRestore(request,env,action,body)}return response({ok:false,error:'NOT_FOUND'},404)}};