import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
import { createRemoteJWKSet, jwtVerify } from "npm:jose";

const supabase=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
const jwks=createRemoteJWKSet(new URL("https://token.actions.githubusercontent.com/.well-known/jwks"));
const AUDIENCE="nayanet-project-intelligence-bridge",ISSUER="https://token.actions.githubusercontent.com",REPOSITORY="SoulSchoolAcademy/NayaPOWER",REPOSITORY_OWNER="SoulSchoolAcademy";
const fail=(status:number,code:string,detail?:string)=>new Response(JSON.stringify({status:"REJECTED",code,detail}),{status,headers:{"content-type":"application/json"}});
Deno.serve(async req=>{
 if(req.method!=="POST")return fail(405,"METHOD_NOT_ALLOWED");
 const auth=req.headers.get("authorization")||"";if(!auth.startsWith("Bearer "))return fail(401,"UNAUTHORIZED");
 let oidc:any;
 try{const verified=await jwtVerify(auth.slice(7),jwks,{issuer:ISSUER,audience:AUDIENCE});oidc=verified.payload;if(oidc.repository!==REPOSITORY)return fail(403,"REPOSITORY_NOT_AUTHORIZED");if(oidc.ref!=="refs/heads/main")return fail(403,"REF_NOT_AUTHORIZED");if(oidc.repository_visibility!=="public")return fail(403,"VISIBILITY_NOT_AUTHORIZED");if(oidc.repository_owner!==REPOSITORY_OWNER)return fail(403,"REPOSITORY_OWNER_NOT_AUTHORIZED");if(!/^[0-9]+$/.test(String(oidc.repository_owner_id??"")))return fail(403,"REPOSITORY_OWNER_ID_REQUIRED");if(!/^[0-9]+$/.test(String(oidc.actor_id??"")))return fail(403,"OIDC_ACTOR_REQUIRED");if(!/^[0-9a-f]{40}$/i.test(String(oidc.sha??"")))return fail(403,"OIDC_SOURCE_SHA_REQUIRED");if(!String(oidc.sub??"").startsWith(`repo:${REPOSITORY}:`))return fail(403,"OIDC_SUBJECT_NOT_AUTHORIZED");if(!/^SoulSchoolAcademy\/NayaPOWER\/\.github\/workflows\/[^\s]+@refs\/heads\/main$/.test(String(oidc.workflow_ref??"")))return fail(403,"WORKFLOW_REF_NOT_AUTHORIZED");if(!/^SoulSchoolAcademy\/NayaPOWER\/\.github\/workflows\/[^\s]+@refs\/heads\/main$/.test(String(oidc.job_workflow_ref??"")))return fail(403,"JOB_WORKFLOW_REF_NOT_AUTHORIZED");if(!/^[0-9]+$/.test(String(oidc.run_id??""))||!String(oidc.run_attempt??"").trim()||!String(oidc.event_name??"").trim())return fail(403,"OIDC_WORKFLOW_CONTEXT_REQUIRED");const allowedWorkflowRefs=(Deno.env.get("NAYANET_BRIDGE_ALLOWED_WORKFLOW_REFS")||"").split(",").map(x=>x.trim()).filter(Boolean);if(!allowedWorkflowRefs.length||!allowedWorkflowRefs.includes(String(oidc.workflow_ref)))return fail(403,"WORKFLOW_NOT_ALLOWLISTED");const expectedEnvironment=Deno.env.get("NAYANET_BRIDGE_EXPECTED_ENVIRONMENT")||"";if(expectedEnvironment&&oidc.environment!==expectedEnvironment)return fail(403,"OIDC_ENVIRONMENT_NOT_AUTHORIZED");}catch(e){return fail(401,"OIDC_INVALID",String(e))}
 let packet:any;try{packet=await req.json()}catch{return fail(400,"INVALID_JSON")}
 const required=["protocol","packet_id","project_id","source_ref","content_hash","operating_context","intelligence","provenance","privacy","idempotency_key","owner_id"];
 const missing=required.filter(k=>packet?.[k]===undefined||packet?.[k]===null||packet?.[k]==="");if(missing.length)return fail(400,"INVALID_PACKET",missing.join(","));
 if(packet.protocol!=="NAYANET_PROJECT_INTELLIGENCE_BRIDGE_V1")return fail(400,"PROTOCOL_MISMATCH");if(packet.project_id!=="NayaNET")return fail(400,"PROJECT_MISMATCH");
 if(packet.sender?.repository!==REPOSITORY)return fail(403,"SENDER_MISMATCH");if(packet.receiver?.canonical_source!=="NAYANET/HUB/index.html")return fail(403,"RECEIVER_MISMATCH");if(packet.privacy?.default_visibility!=="PRIVATE")return fail(403,"PRIVACY_POLICY_REQUIRED");
  const ownerId=String(packet.owner_id);
  if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(ownerId))return fail(400,"OWNER_ID_INVALID");
  const sourceRef=String(packet.source_ref||"");
  if(/^[0-9a-f]{40}$/i.test(sourceRef)&&sourceRef.toLowerCase()!==String(oidc.sha).toLowerCase())return fail(403,"SOURCE_SHA_NOT_AUTHORIZED");
  if(packet.run_identity&&!String(packet.run_identity).includes(String(oidc.run_id)))return fail(403,"RUN_IDENTITY_NOT_AUTHORIZED");
  const ownerBinding=req.headers.get("x-naya-owner-binding")||"";
  if(!ownerBinding)return fail(401,"OWNER_BINDING_REQUIRED");
  const {data:binding,error:bindingError}=await supabase.rpc("nayanet_consume_bridge_owner_binding",{p_binding_token:ownerBinding,p_owner_id:ownerId,p_repository:REPOSITORY,p_workflow_ref:String(oidc.workflow_ref),p_run_id:String(oidc.run_id),p_packet_id:String(packet.packet_id)});
  if(bindingError||binding?.status!=="VALID"||binding?.owner_id!==ownerId)return fail(403,"OWNER_BINDING_INVALID",bindingError?.message||"OWNER_WORKFLOW_BINDING_NOT_CONSUMED");
  const {data:owner,error:ownerError}=await supabase.auth.admin.getUserById(ownerId);if(ownerError||!owner?.user)return fail(403,"OWNER_NOT_FOUND");
  const {data:existing,error:lookupError}=await supabase.from("nayanet_project_intelligence_bridge").select("packet_id,project_id,source_ref,content_hash,owner_id,receiver_transaction_id,receiver_event_id,receipt_id,persisted,indexed,projected,retrieved,rendered,accepted_at").eq("idempotency_key",packet.idempotency_key).maybeSingle();
  if(lookupError)return fail(500,"LOOKUP_FAILED",lookupError.message);if(existing)return new Response(JSON.stringify({status:"ACCEPTED",replay:true,...existing,owner_binding:binding.status,source_identity:{repository:REPOSITORY,source_sha:String(oidc.sha),workflow_ref:String(oidc.workflow_ref),job_workflow_ref:String(oidc.job_workflow_ref),run_id:String(oidc.run_id),run_attempt:String(oidc.run_attempt),event_name:String(oidc.event_name)}}),{status:200,headers:{"content-type":"application/json"}});
 const transactionId=crypto.randomUUID(),receiverEventId=crypto.randomUUID(),receiptId=crypto.randomUUID();
 const {data:bridge,error}=await supabase.from("nayanet_project_intelligence_bridge").insert({packet_id:packet.packet_id,project_id:packet.project_id,source_ref:packet.source_ref,content_hash:packet.content_hash,idempotency_key:packet.idempotency_key,packet,owner_id:ownerId,receiver_transaction_id:transactionId,receiver_event_id:receiverEventId,receipt_id:receiptId,persisted:true,indexed:false,projected:false}).select("packet_id,project_id,source_ref,content_hash,owner_id,receiver_transaction_id,receiver_event_id,receipt_id,persisted,indexed,projected,retrieved,rendered,accepted_at").single();
 if(error)return fail(500,"PERSIST_FAILED",error.message);
 const title=String(packet.project_intelligence_reconstruction?.current?.mission||packet.operating_context?.current_next_action?.action||"NayaNET Project Intelligence");
 const content=JSON.stringify({protocol:packet.protocol,project_id:packet.project_id,source_ref:packet.source_ref,content_hash:packet.content_hash,operating_context:packet.operating_context,project_intelligence_reconstruction:packet.project_intelligence_reconstruction,intelligence:packet.intelligence,provenance:packet.provenance,privacy:packet.privacy,bridge:{packet_id:packet.packet_id,receiver_transaction_id:transactionId,receiver_event_id:receiverEventId,receipt_id:receiptId}});
 const {data:event,error:eventError}=await supabase.from("nayanet_cognition_events").insert({user_id:ownerId,project_id:"NayaNET",event_id:receiverEventId,type:"project_intelligence_bridge",classification:"project_intelligence",title,content,source:"nayanet-project-intelligence-bridge",status:"active",actor:"machine",confidence:1,tags:["project-intelligence","bridge","github","private"],parent_event_id:null,source_hash:packet.content_hash,schema_version:"1.0.0",receipt_id:receiptId,metadata:{bridge_packet_id:packet.packet_id,receiver_transaction_id:transactionId,receiver_event_id:receiverEventId,receipt_id:receiptId,owner_id:ownerId,privacy:"PRIVATE",source_ref:packet.source_ref,content_hash:packet.content_hash,github_actor_id:String(oidc.actor_id),github_workflow_ref:String(oidc.workflow_ref),github_job_workflow_ref:String(oidc.job_workflow_ref),github_run_id:String(oidc.run_id),github_run_attempt:String(oidc.run_attempt),github_event_name:String(oidc.event_name),github_source_sha:String(oidc.sha),projected_at:new Date().toISOString()}}).select("id,event_id,title,type,status,created_at").single();
 if(eventError){await supabase.from("nayanet_project_intelligence_bridge").delete().eq("packet_id",packet.packet_id);return fail(500,"COGNITION_PROJECTION_FAILED",eventError.message)}
 const {data:index,error:indexError}=await supabase.from("nayanet_intelligence_index").select("id").eq("owner_id",ownerId).eq("source_table","nayanet_cognition_events").eq("source_id",event.id).maybeSingle();
 if(indexError)return fail(500,"INDEX_PROJECTION_FAILED",indexError.message);
 if(!index)return fail(500,"INDEX_PROJECTION_MISSING","cognition event trigger did not create canonical index");
 const {data:updated,error:updateError}=await supabase.from("nayanet_project_intelligence_bridge").update({indexed:true,projected:true}).eq("packet_id",packet.packet_id).select("packet_id,project_id,source_ref,content_hash,owner_id,receiver_transaction_id,receiver_event_id,receipt_id,persisted,indexed,projected,retrieved,rendered,accepted_at").single();
 if(updateError)return fail(500,"PROJECTION_FLAG_UPDATE_FAILED",updateError.message);
  return new Response(JSON.stringify({status:"COMPLETED",replay:false,...updated,owner_binding:binding.status,source_identity:{repository:REPOSITORY,source_sha:String(oidc.sha),workflow_ref:String(oidc.workflow_ref),job_workflow_ref:String(oidc.job_workflow_ref),run_id:String(oidc.run_id),run_attempt:String(oidc.run_attempt),event_name:String(oidc.event_name)},projection:{cognition_event_id:event.id,index_id:index.id}}),{status:200,headers:{"content-type":"application/json"}});
});