"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];

const WORLDS=[
{id:"power",name:"Naya Power",icon:"☀",sub:"Your intelligence system",tone:"#a98cff",title:"Think with more power.",copy:"Naya Power is the intelligence layer for thinking, learning, creating, remembering, organizing, communicating, discovering and accomplishing.",items:[["THINK","Turn questions into clearer thinking and better decisions."],["CREATE","Move from idea to useful work with an intelligent partner."],["GROW","Use every interaction to become more capable."]]},
{id:"brain",name:"Super Brain",icon:"✦",sub:"Private context",tone:"#a98cff",title:"Build intelligence that stays with you.",copy:"Your private intelligence grows from meaningful experience, memory and context — so tomorrow can begin with what you learned today.",items:[["EXPERIENCE","What happens to you can become useful signal."],["MEMORY","Important context does not disappear with a chat."],["COMPOUND","Experience becomes reusable intelligence."]]},
{id:"identity",name:"Smart Identity",icon:"◈",sub:"Name · ID · Link",tone:"#f3d27e",title:"Be known by what you choose.",copy:"Your Smart Identity separates the person you are from the identity you choose to use on the network.",items:[["SMART NAME","Start with the name you choose."],["SMART ID","A deliberate network identity."],["SMART LINK","Connect without exposing everything."]]},
{id:"intelligence",name:"Intelligence",icon:"◇",sub:"Capture · learn · compound",tone:"#6ee6a0",title:"Turn experience into intelligence.",copy:"Breakthroughs, lessons, decisions, questions and discoveries should not vanish into yesterday. Capture the useful part and carry it forward.",items:[["HUMAN NOTE","What you experienced."],["NAYA NOTE","What Naya understood."],["COMPOUND","What carries forward."]]},
{id:"maxess",name:"MAXESS",icon:"◎",sub:"AI capability",tone:"#a98cff",title:"Discover what you're capable of.",copy:"MAXESS makes AI capability visible. See where you are, understand your strengths and discover the next move that can make you dramatically more capable.",items:[["ASSESS","A focused AI mastery assessment."],["UNDERSTAND","See capability clearly."],["ACT","Turn insight into a better way of working."]],action:"score"},
{id:"challenge",name:"5-Day Challenge",icon:"5",sub:"Activate momentum",tone:"#f3d27e",title:"Don't believe it. Try it.",copy:"Work with Naya on something real for five days. Create, learn, capture and compound — then look back and see what changed.",items:[["DAY 1","Meet the system and establish context."],["DAYS 2–4","Create, learn, capture and compound."],["DAY 5","Look back and see what changed."]],action:"challenge"},
{id:"spaces",name:"Intelligent Spaces",icon:"◎",sub:"Humans + AIs",tone:"#69e7ff",title:"Open a room around the work.",copy:"Bring people and intelligences together around one purpose. Private by default. Sharing happens by choice.",items:[["PEOPLE","Invite who belongs."],["AI","Bring Naya or other AIs into the work."],["PURPOSE","The space exists to help something happen."]]},
{id:"network",name:"Your Network",icon:"⊙",sub:"Connect intelligence",tone:"#69e7ff",title:"Let useful intelligence find useful intelligence.",copy:"NayaNET is not about exposing everyone to everyone. It is about meaningful connection, with consent at the boundary.",items:[["DISCOVER","Subjects, interests, questions and capabilities."],["CONNECT","Meet around ideas rather than identity alone."],["SHARE","Choose what wisdom can travel."]]},
{id:"player",name:"Power Player",icon:"▶",sub:"18 Powercasts",tone:"#f3d27e",title:"Listen. Think. Become more capable.",copy:"The Power Player is the heartbeat of NayaNET — a living listening experience built from the real Powercast library.",items:[["LISTEN","Choose a canonical Powercast."],["EXPLORE","Move through the library without losing context."],["RETURN","Come back to the Living Sun naturally." ]],action:"player"}
];

const POS=[[50,7],[76,18],[91,40],[84,67],[68,91],[32,91],[16,67],[9,40],[24,18]];
const DESC={1:"Imagine an AI that remembers what matters.",2:"Meet your compounding Superbrain.",3:"End AI amnesia and keep the useful context.",4:"Why your AI should be a 10.",5:"Drive your AI with intention, not random prompts.",6:"Turn AI into your personal sparring partner.",7:"Build a lifelong intelligence partner.",8:"The AI operational partner changes how work moves.",9:"A closer look at the Naya Power Superbrain.",10:"Working software is not the same thing as an extraordinary system.",11:"What happens when top AIs grade Naya Power?",12:"A founder's letter about ending AI amnesia.",13:"The Human–AI Intelligence Opera.",14:"The Naya Power Operating Model.",15:"A blueprint for collective wisdom.",16:"Welcome to NayaNET. Escape AI exhaustion.",17:"Curing human forgetfulness with Naya AI.",18:"What makes a compounding Super Brain?"};
const state={name:"",view:"frontDoor",world:null,casts:[],track:0,playing:false};

function toast(text){const e=$("#toast");e.textContent=text;e.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.classList.remove("show"),2300)}
function setView(id,push=true){state.view=id;["frontDoor","hub","worldView","playerView"].forEach(x=>{const e=$("#"+x),active=x===id;e.classList.toggle("active",active);e.setAttribute("aria-hidden",String(!active))});if(push)history.pushState({view:id,world:state.world},"",location.pathname+"#"+id+(state.world?"/"+state.world:""))}
function enter(){const input=$("#nameInput"),name=input.value.trim();if(!name){input.focus();return}state.name=name;localStorage.setItem("nayanetName",name);$("#welcomeName").textContent="WELCOME, "+name.toUpperCase();setView("hub");toast("You're in. Naya is ready.")}
function exit(){state.name="";state.world=null;localStorage.removeItem("nayanetName");$("#nameInput").value="";setView("frontDoor",false);history.replaceState({view:"frontDoor"},"",location.pathname)}
function driveId(url){const m=(url||"").match(/\/d\/([^/]+)/);return m?m[1]:null}
function imageFor(c){const id=driveId(c.image);return id?`https://drive.google.com/thumbnail?id=${id}&sz=w1200`:""}
function audioFor(c){const id=driveId(c.audio);return id?`https://drive.google.com/uc?export=download&id=${id}`:c.audio||""}

function renderWorlds(){const root=$("#worlds");root.innerHTML=WORLDS.map((w,i)=>{const [x,y]=POS[i];return `<button class="world" data-world="${w.id}" aria-label="Open ${w.name}" style="left:${x}%;top:${y}%;--tone:${w.tone}"><span class="world-icon">${w.icon}</span><span class="world-copy"><b class="world-name">${w.name}</b><small class="world-sub">${w.sub}</small></span></button>`}).join("");$$('.world').forEach(button=>{button.onclick=()=>openWorld(button.dataset.world)})}
function openWorld(id){const world=WORLDS.find(w=>w.id===id);if(!world)return;state.world=id;if(world.action==="player"){openPlayer();return}renderWorld(world);setView("worldView")}
function renderWorld(w){$("#worldTag").textContent=`NAYANET · ${w.name.toUpperCase()}`;$("#worldContent").innerHTML=`<article class="destination-hero" style="--tone:${w.tone}"><div><div class="destination-kicker">${w.sub.toUpperCase()}</div><h1>${w.title}</h1><p>${w.copy}</p><div class="destination-actions"><button class="destination-primary" id="worldPrimary">${w.action==="score"?"DISCOVER YOUR AI SCORE →":w.action==="challenge"?"START THE FIVE-DAY →":"ASK NAYA →"}</button><button class="destination-secondary" id="worldReturn">RETURN TO NAYA</button></div></div><div class="destination-object"><span>${w.icon}</span></div></article><section class="destination-grid">${w.items.map((item,i)=>`<article class="destination-piece"><b>0${i+1} · ${item[0]}</b><p>${item[1]}</p></article>`).join("")}</section>`;$("#worldPrimary").onclick=()=>worldAction(w);$("#worldReturn").onclick=()=>returnToHub();syncDock()}
function worldAction(w){if(w.action==="score"){location.href="https://aiscore.nayanet.app/";return}if(w.action==="challenge"){toast("The Five-Day Challenge is ready for activation.");return}if(w.id==="player"){openPlayer();return}toast(`${w.name} is a destination — explore the ideas, then return to Naya.`)}
function returnToHub(){state.world=null;setView("hub")}

async function loadCasts(){try{const response=await fetch("/powercasts.json",{cache:"no-store"});if(!response.ok)throw new Error("load");state.casts=await response.json()}catch(error){state.casts=[];toast("The Powercast library could not load.");return}renderCasts();selectTrack(state.track,false)}
function renderCasts(){const root=$("#castGrid");root.innerHTML=state.casts.map((cast,index)=>{const img=imageFor(cast);return `<button class="cast ${index===state.track?"selected":""}" data-track="${index}" aria-label="Powercast ${cast.n}: ${cast.title}"><span class="cast-art" ${img?`style="background-image:url('${img}')"`:""}></span><span class="cast-number">${String(cast.n).padStart(2,"0")}</span><span class="cast-info"><small>POWERCAST ${String(cast.n).padStart(2,"0")}</small><strong>${cast.title}</strong></span></button>`}).join("");$$('.cast').forEach(button=>button.onclick=()=>selectTrack(Number(button.dataset.track),true))}
function selectTrack(index,play){if(!state.casts.length)return;const i=(index+state.casts.length)%state.casts.length,cast=state.casts[i],image=imageFor(cast);state.track=i;state.playing=false;$("#coreArt").style.backgroundImage=image?`url('${image}')`:"none";$("#heroCover").style.backgroundImage=image?`url('${image}')`:"none";$("#dockArt").style.backgroundImage=image?`url('${image}')`:"none";$("#coreNumber").textContent=String(cast.n).padStart(2,"0");$("#heroNumber").textContent=String(cast.n).padStart(2,"0");$("#heroMetaNumber").textContent=String(cast.n).padStart(2,"0");$("#heroTitle").textContent=cast.title;$("#heroDesc").textContent=DESC[cast.n]||"Listen, think and carry the useful part forward.";$("#hubTitle").textContent=cast.title;$("#hubDesc").textContent=DESC[cast.n]||"Listen, think and carry the useful part forward.";$("#dockTitle").textContent=cast.title;$("#audio").src=audioFor(cast);$("#audio").load();$$('.cast').forEach((el,j)=>el.classList.toggle("selected",j===i));syncUI();syncDock();if(play)playAudio()}
function openPlayer(){state.world="player";setView("playerView");syncDock()}
function playAudio(){const audio=$("#audio");if(!audio.src){toast("Choose a Powercast first.");return}audio.play().then(()=>{state.playing=true;syncUI();syncDock()}).catch(()=>toast("Press play to start the Powercast."))}
function pauseAudio(){const audio=$("#audio");audio.pause();state.playing=false;syncUI();syncDock()}
function toggle(){if($("#audio").paused)playAudio();else pauseAudio()}
function fmt(value){return Number.isFinite(value)?Math.floor(value/60)+":"+String(Math.floor(value%60)).padStart(2,"0"):"0:00"}
function syncUI(){const icon=state.playing?"Ⅱ":"▶";$("#hubPlay").textContent=icon;$("#mainPlay").textContent=icon;$("#dockPlay").textContent=icon;$("#waveform").classList.toggle("playing",state.playing);$("#heroStatus").textContent=state.playing?"PLAYING":"READY"}
function syncDock(){const dock=$("#persistentPlayer");if(state.view!=="worldView"){dock.style.display="none";return}dock.style.display="grid"}
function updateProgress(){const audio=$("#audio"),pct=audio.duration?audio.currentTime/audio.duration*100:0;$("#hubProgress").style.width=pct+"%";$("#heroProgress").style.width=pct+"%";$("#dockProgress").style.width=pct+"%";$("#currentTime").textContent=fmt(audio.currentTime);$("#duration").textContent=fmt(audio.duration);$("#hubCurrent").textContent=fmt(audio.currentTime);$("#hubDuration").textContent=fmt(audio.duration)}
function renderWave(){$("#waveform").innerHTML=Array.from({length:46},(_,i)=>`<i style="--h:${18+((i*29)%76)}%"></i>`).join("")}

$("#entryForm").onsubmit=e=>{e.preventDefault();enter()};$("#exitButton").onclick=exit;$("#worldBack").onclick=returnToHub;$("#playerBack").onclick=returnToHub;$("#openPlayer").onclick=openPlayer;$("#coreArt").onclick=openPlayer;$("#hubPlay").onclick=toggle;$("#mainPlay").onclick=toggle;$("#hubPrev").onclick=()=>selectTrack(state.track-1,state.playing);$("#hubNext").onclick=()=>selectTrack(state.track+1,state.playing);$("#prevTrack").onclick=()=>selectTrack(state.track-1,state.playing);$("#nextTrack").onclick=()=>selectTrack(state.track+1,state.playing);$("#dockPlay").onclick=toggle;$("#dockOpen").onclick=openPlayer;$("#dockArt").onclick=openPlayer;
$("#askNaya").onclick=()=>openWorld("power");
$$('[data-preview]').forEach(button=>button.onclick=()=>{const id=button.dataset.preview;if(id==="player")openPlayer();else openWorld(id)});
$$('[data-quick]').forEach(button=>button.onclick=()=>button.dataset.quick==="player"?openPlayer():openWorld(button.dataset.quick));
$("#audio").ontimeupdate=updateProgress;$("#audio").onplay=()=>{state.playing=true;syncUI();syncDock()};$("#audio").onpause=()=>{state.playing=false;syncUI();syncDock()};$("#audio").onended=()=>selectTrack(state.track+1,true);
window.onpopstate=event=>{const view=event.state?.view||"hub";state.world=event.state?.world||null;setView(view,false);if(view==="worldView"&&state.world){const w=WORLDS.find(x=>x.id===state.world);if(w)renderWorld(w)}syncDock()};

document.addEventListener("keydown",event=>{if(event.key!=="Escape")return;if(state.view==="worldView"||state.view==="playerView")returnToHub()});
renderWorlds();renderWave();
const saved=localStorage.getItem("nayanetName");if(saved){state.name=saved;$("#nameInput").value=saved;$("#welcomeName").textContent="WELCOME, "+saved.toUpperCase()}
loadCasts();
