#!/usr/bin/env python3
"""Regenerate the NayaPOWER Brain index layer from git truth.

Regenerates from the committed git tree (never the working tree, never the
ledger's stale per-file names):
    BRAIN/REAL-TREE.json
    BRAIN/REAL-TREE.md
and patches the mechanical fields of:
    BRAIN/NAYAPOWER-BRAIN-INDEX.json

Usage:
    python3 tools/regenerate_brain_index.py [--root PATH] [--check]

--check verifies the three files match what regeneration would produce and
exits 1 on drift (suitable for CI). It compares everything EXCEPT the
provenance stamps (generated_at date, last_reconciled_main /
receipt_basis_commit SHAs), which record the verification event rather than
tree-derived data: generated_at only needs to be a valid date, and the basis
SHAs only need to be well-formed. Any real BRAIN/ change (added, removed, or
edited file) still fails the check.

Reconciliation rules (2026-09-30 brain-reconciliation ledger):
    - Per-domain counts must match the ledger's fixed classification table,
      except the governed INTELLIGENCE-REPORTS and SMART-NOTES subtrees, whose
      committed file counts are added mechanically to the fixed 05-MEMORY
      baseline. Any other drift fails the run instead of silently rewriting
      the table.
    - Pointer integrity: every declared pointer-bearing field in the index
      layer (POINTER_FIELDS) must resolve against the git tree at HEAD. A
      generic backstop scan catches path-like strings in the same files that
      are not declared and not documented non-pointers. Any dangling pointer
      fails the run with exit 2, naming the file, field, and bad target.
    - Never invent or alter semantic/contract claims — counts, file lists,
      pointers and dated banners only.
    - The three index files are self-referential: instead of listing their own
      blob SHAs (which would make the content a moving target — the SHA changes
      every time the file is regenerated), their table entries carry
      "_self_referential": true with no blob SHA. file_count always equals the
      true tree size, so the ledger's count assertions still hold.

Exit codes: 0 = ok (or --check passed); 1 = --check found drift;
           2 = usage/git error, count drift, or dangling pointer.
"""

from __future__ import annotations

import argparse
import datetime
import json
import re
import subprocess
import sys
from pathlib import Path

# Receipt files: regenerated by this script; excluded from their own blob listing
# (fixed-point design — see module docstring).
RECEIPT_PATHS = {
    "BRAIN/REAL-TREE.json",
    "BRAIN/REAL-TREE.md",
    "BRAIN/NAYAPOWER-BRAIN-INDEX.json",
}

# Pointer-bearing fields in the index layer, as (file, dotted field path, kind).
# kind "blob" = must resolve to a file in the git tree at HEAD;
# kind "tree" = must resolve to a directory prefix present in the git tree.
# This is the declared set. A generic path-like string scan of the same files
# runs as a backstop so a newly added pointer field cannot slip through.
POINTER_FIELDS = [
    # BRAIN/NAYAPOWER-BRAIN-INDEX.json (touched/patched by this tool)
    ("BRAIN/NAYAPOWER-BRAIN-INDEX.json", "canonical_root", "blob"),
    ("BRAIN/NAYAPOWER-BRAIN-INDEX.json", "constitutional_root", "blob"),
    ("BRAIN/NAYAPOWER-BRAIN-INDEX.json", "governance_root", "blob"),
    ("BRAIN/NAYAPOWER-BRAIN-INDEX.json", "superbrain_spec", "blob"),
    ("BRAIN/NAYAPOWER-BRAIN-INDEX.json", "brain_map", "blob"),
    ("BRAIN/NAYAPOWER-BRAIN-INDEX.json", "knowledge_synthesis", "blob"),
    ("BRAIN/NAYAPOWER-BRAIN-INDEX.json", "knowledge_ledger", "blob"),
    ("BRAIN/NAYAPOWER-BRAIN-INDEX.json", "kernel_runtime_registry", "blob"),
    ("BRAIN/NAYAPOWER-BRAIN-INDEX.json", "knowledge_population_map", "blob"),
    ("BRAIN/NAYAPOWER-BRAIN-INDEX.json", "representation_contract", "blob"),
    ("BRAIN/NAYAPOWER-BRAIN-INDEX.json", "graph_seed", "blob"),
    ("BRAIN/NAYAPOWER-BRAIN-INDEX.json", "knowledge_node_map", "blob"),
    ("BRAIN/NAYAPOWER-BRAIN-INDEX.json", "node_objects", "tree"),
    ("BRAIN/NAYAPOWER-BRAIN-INDEX.json", "inventory", "blob"),
    ("BRAIN/NAYAPOWER-BRAIN-INDEX.json",
     "proof_boundary.historical_north_star_acceptance.audit", "blob"),
    ("BRAIN/NAYAPOWER-BRAIN-INDEX.json", "smart_node_protocol", "blob"),
    ("BRAIN/NAYAPOWER-BRAIN-INDEX.json", "operations.queue", "blob"),
    ("BRAIN/NAYAPOWER-BRAIN-INDEX.json", "operations.master_plan", "blob"),
    ("BRAIN/NAYAPOWER-BRAIN-INDEX.json", "operations.master_plan_machine_projection", "blob"),
    ("BRAIN/NAYAPOWER-BRAIN-INDEX.json", "operations.issue_944_reconciliation", "blob"),
    ("BRAIN/NAYAPOWER-BRAIN-INDEX.json", "smart_note_human_projection.root", "tree"),
    ("BRAIN/NAYAPOWER-BRAIN-INDEX.json", "smart_note_human_projection.projection_registry", "blob"),
    ("BRAIN/NAYAPOWER-BRAIN-INDEX.json", "nine_node_organism_contract", "blob"),
    ("BRAIN/NAYAPOWER-BRAIN-INDEX.json", "nine_node_organism_map", "blob"),
    ("BRAIN/NAYAPOWER-BRAIN-INDEX.json", "smart_doors.contract", "blob"),
    ("BRAIN/NAYAPOWER-BRAIN-INDEX.json", "smart_doors.registry", "blob"),
    ("BRAIN/NAYAPOWER-BRAIN-INDEX.json", "graph_relationship_contract_v2", "blob"),
    # BRAIN/04-INTELLIGENCE/MASTER-INDEX.json — the defect class that started
    # Battle 1 (object_contract pointed at a nonexistent 0001-...md).
    ("BRAIN/04-INTELLIGENCE/MASTER-INDEX.json", "tree", "blob"),
    ("BRAIN/04-INTELLIGENCE/MASTER-INDEX.json", "graph_contract", "blob"),
    ("BRAIN/04-INTELLIGENCE/MASTER-INDEX.json", "object_contract", "blob"),
]

# Path-looking strings that are NOT pointers (documented exclusions from the
# generic backstop scan).
NON_POINTER_STRINGS = {
    ("BRAIN/NAYAPOWER-BRAIN-INDEX.json",
     "smart_note_human_projection.pattern"): "glob pattern, not a resolvable path",
    ("BRAIN/NAYAPOWER-BRAIN-INDEX.json",
     "reconciliation.ledger"): "workspace-local reference (~/workspace/naya/), not a repo path",
}

# A string value is treated as a repo path pointer if it matches this.
PATH_LIKE_RE = re.compile(r"^(BRAIN/|CONSTITUTION/|GOVERNANCE/|ARCHITECTURE/|\.naya/|0000-)")

# Ledger classification table: fixed domain baselines.
#
# INTELLIGENCE-REPORTS and SMART-NOTES are append-only governed memory subtrees.
# Reports and verified Smart Note projections must be able to accumulate without
# requiring a manual ledger-count edit after every intelligence event. We
# therefore keep the 05-MEMORY baseline fixed at the count that excludes both
# governed append-only subtrees, then add their committed file counts
# mechanically from git truth.
BASE_EXPECTED_DOMAIN_COUNTS = {
    "00-SPEC": 15,
    # 3 -> 6 for #1444: 0003-FULL-AUTO-MERGE-V1 (ai/human/machine) lands under
    # the supreme Scorecard Law (verbal ratification 2026-10-05). Deliberate update.
    # 6 -> 7 for the 10-area system scorecard: 0003-SYSTEM-SCORECARD-V1 lands as
    # standing law (ratified by Shawn Vibert 2026-10-05; weighted total 6.8/10).
    # Deliberate update.
    # 7 -> 10 for the Nonstop Loop V1 operating code: 0004-NONSTOP-LOOP-V1
    # (ai/human/machine) lands as standing law (authored by Shawn Vibert
    # 2026-10-05; report-routing amendment adopted same morning).
    # Deliberate update.
    "01-GOVERNANCE": 10,
    "02-ARCHITECTURE": 5,
    "03-KERNEL": 28,
    "04-INTELLIGENCE": 24,
    "05-MEMORY": 2,  # fixed baseline excluding governed INTELLIGENCE-REPORTS + SMART-NOTES subtrees
    # Current fixed files are 0001-MEMORY-CONTINUITY-CONTRACT-V1.md + README.md.
    # Smart Note projections and intelligence reports are counted mechanically below.
    "06-PROOF": 10,
    "07-LEARNING": 2,
    "08-SUCCESSION": 2,
    "09-EVOLUTION": 2,
    # 2026-10-04: a9e5a505f added 0003-NAYA-VOICE-CHATTERBOX-SPEC-V1.md, the
    # canonical Naya Voice playback architecture spec. A real governed artifact
    # landed, so the baseline moves deliberately rather than being forced.
    # 2026-10-04: naya2/voice-bake-canonical-v1 adds naya-voice-sample-v1.mp3,
    # the first real-model baked voice sample next to the spec. Real artifact
    # landed; baseline moves deliberately.
    "10-INTERFACES": 7,
    "11-KNOWLEDGE": 7,
    "12-ENGINEERING": 24,
    "90-OPERATIONS": 11,  # 2026-10-04 whole-repository alignment report added on current main
    "99-ARCHIVE": 1,
    "ROOT": 5,
}

INTELLIGENCE_REPORT_PREFIX = "BRAIN/05-MEMORY/INTELLIGENCE-REPORTS/"
SMART_NOTE_PREFIX = "BRAIN/05-MEMORY/SMART-NOTES/"
DOMAIN_ORDER = tuple(BASE_EXPECTED_DOMAIN_COUNTS.keys())


def expected_domain_counts(files: list[dict]) -> dict[str, int]:
    """Return expected counts with governed append-only memory subtrees dynamic.

    Every Brain domain remains fixed against the reconciliation ledger except
    the two governed append-only 05-MEMORY subtrees. 05-MEMORY may exceed its
    fixed baseline only by the exact number of committed files beneath
    INTELLIGENCE_REPORT_PREFIX and SMART_NOTE_PREFIX. This preserves the
    count-skew tripwire for every other memory path while letting reports and
    Smart Note projections accumulate without manual baseline edits.
    """
    expected = dict(BASE_EXPECTED_DOMAIN_COUNTS)
    report_files = sum(1 for f in files if f["path"].startswith(INTELLIGENCE_REPORT_PREFIX))
    smart_note_files = sum(1 for f in files if f["path"].startswith(SMART_NOTE_PREFIX))
    expected["05-MEMORY"] += report_files + smart_note_files
    return expected


DOMAIN_TITLES = {
    "00-SPEC": "00-SPEC — Specification",
    "01-GOVERNANCE": "01-GOVERNANCE — Governance",
    "02-ARCHITECTURE": "02-ARCHITECTURE — Architecture",
    "03-KERNEL": "03-KERNEL — Kernel",
    "04-INTELLIGENCE": "04-INTELLIGENCE — Intelligence",
    "05-MEMORY": "05-MEMORY — Memory",
    "06-PROOF": "06-PROOF — Proof",
    "07-LEARNING": "07-LEARNING — Learning",
    "08-SUCCESSION": "08-SUCCESSION — Succession",
    "09-EVOLUTION": "09-EVOLUTION — Evolution",
    "10-INTERFACES": "10-INTERFACES — Interfaces",
    "11-KNOWLEDGE": "11-KNOWLEDGE — Knowledge",
    "12-ENGINEERING": "12-ENGINEERING — Engineering",
    "90-OPERATIONS": "90-OPERATIONS — Operations",
    "99-ARCHIVE": "99-ARCHIVE — Archive",
    "ROOT": "ROOT — Brain root files",
}


def git(args: list[str], root: Path) -> str:
    proc = subprocess.run(["git", *args], capture_output=True, text=True, cwd=root)
    if proc.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)} failed: {proc.stderr.strip()}")
    return proc.stdout


def basis_commit(root: Path) -> str:
    """The main revision this index is reconciled against (provenance stamp).

    Uses the merge-base of HEAD with origin/main when the remote ref is
    available (the last main revision this work was verified against),
    falling back to HEAD on a detached/no-remote checkout.
    """
    try:
        return git(["merge-base", "HEAD", "origin/main"], root).strip()
    except RuntimeError:
        return git(["rev-parse", "HEAD"], root).strip()


def inventory(root: Path) -> list[dict]:
    """Return [{path, sha(blob), size}] for every blob under BRAIN/ at HEAD."""
    out = git(
        ["ls-tree", "-r", "--format=%(objectname) %(objectsize) %(path)", "HEAD", "--", "BRAIN/"],
        root,
    )
    files = []
    for line in out.splitlines():
        sha, size, path = line.split(" ", 2)
        files.append({"path": path, "sha": sha, "size": int(size)})
    files.sort(key=lambda f: f["path"])
    return files


def domain_of(path: str) -> str:
    if path == "BRAIN/REAL-TREE.json" or path == "BRAIN/REAL-TREE.md":
        return "ROOT"
    parts = path.split("/")
    if len(parts) == 2:
        return "ROOT"
    return parts[1]


def domain_counts(files: list[dict]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for f in files:
        d = domain_of(f["path"])
        counts[d] = counts.get(d, 0) + 1
    return counts


def get_field(doc: dict, dotted: str):
    cur = doc
    for part in dotted.split("."):
        if not isinstance(cur, dict) or part not in cur:
            return None
        cur = cur[part]
    return cur


def show_file(root: Path, path: str) -> str:
    """Read a file from the committed git tree at HEAD (never the working tree)."""
    return git(["show", f"HEAD:{path}"], root)


def tree_path_sets(root: Path) -> tuple[set[str], set[str]]:
    """Return (blob_paths, dir_prefixes) for the full git tree at HEAD."""
    out = git(["ls-tree", "-r", "--name-only", "HEAD"], root)
    blobs = set(out.splitlines())
    dirs: set[str] = set()
    for p in blobs:
        parts = p.split("/")[:-1]
        for i in range(1, len(parts) + 1):
            dirs.add("/".join(parts[:i]) + "/")
    return blobs, dirs


def iter_path_like_strings(doc, prefix: str = ""):
    """Yield (dotted_field_path, value) for every path-like string in a JSON doc."""
    if isinstance(doc, dict):
        for k, v in doc.items():
            p = f"{prefix}.{k}" if prefix else k
            if isinstance(v, str) and PATH_LIKE_RE.match(v):
                yield p, v
            else:
                yield from iter_path_like_strings(v, p)
    elif isinstance(doc, list):
        for i, v in enumerate(doc):
            yield from iter_path_like_strings(v, f"{prefix}[{i}]")


def validate_pointers(root: Path) -> list[str]:
    """Assert every declared pointer in the index layer resolves in the git tree.

    Returns a list of error strings (empty = all resolve). Covers the declared
    POINTER_FIELDS plus a generic backstop scan for path-like strings in the
    same files, so a newly added pointer field cannot slip through.
    """
    errors: list[str] = []
    blobs, dirs = tree_path_sets(root)
    declared = {(f, fp) for f, fp, _ in POINTER_FIELDS}

    def check_one(path: str, field: str, target: str, kind: str, declared_field: bool):
        if kind == "blob":
            ok = target in blobs
        else:
            ok = (target.rstrip("/") + "/" in dirs) or (target in blobs)
        if not ok:
            origin = "declared" if declared_field else "backstop scan"
            errors.append(
                f"dangling pointer ({origin}): {path} field '{field}' -> '{target}' "
                f"(not in git tree at HEAD)"
            )

    for path, field, kind in POINTER_FIELDS:
        try:
            doc = json.loads(show_file(root, path))
        except RuntimeError as exc:
            errors.append(f"pointer source unreadable: {path}: {exc}")
            continue
        target = get_field(doc, field)
        if target is None:
            errors.append(f"pointer field missing: {path} field '{field}' not present")
        elif not isinstance(target, str):
            errors.append(f"pointer field not a string: {path} field '{field}'")
        else:
            check_one(path, field, target, kind, True)

    # Backstop: any path-like string in the same files that is neither declared
    # nor a documented non-pointer must resolve.
    for path in {f for f, _, _ in POINTER_FIELDS}:
        try:
            doc = json.loads(show_file(root, path))
        except RuntimeError:
            continue  # already reported above
        for field, target in iter_path_like_strings(doc):
            if (path, field) in declared or (path, field) in NON_POINTER_STRINGS:
                continue
            kind = "tree" if target.endswith("/") else "blob"
            check_one(path, field, target, kind, False)

    return errors


def build_real_tree_json(basis: str, files: list[dict], counts: dict[str, int], today: str) -> str:
    entries = []
    for f in files:
        if f["path"] in RECEIPT_PATHS:
            entries.append({"path": f["path"], "_self_referential": True,
                            "note": "regenerated by tools/regenerate_brain_index.py; blob SHA omitted (fixed-point design)"})
        else:
            entries.append({"path": f["path"], "blob_sha": f["sha"], "size": f["size"]})
    doc = {
        "schema": "naya.brain.real_tree.v1",
        "generated_at": today,
        "receipt_basis_commit": basis,
        "inventory_file_count": len(files),
        "domain_counts": counts,
        "ledger_assertion": (
            "Per-domain counts asserted against the 2026-09-30 brain-reconciliation "
            "ledger classification table. Any drift fails regeneration instead of "
            "silently rewriting the table."
        ),
        "files": entries,
    }
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


def build_real_tree_md(basis: str, files: list[dict], counts: dict[str, int], today: str) -> str:
    lines = [
        "# NayaPOWER Brain — Real Tree (machine-verified)",
        "",
        f"**Generated:** {today}  ",
        f"**Receipt basis commit:** `{basis}`  ",
        f"**Inventory file count:** {len(files)}  ",
        "",
        "> Regenerated from the committed git tree by `tools/regenerate_brain_index.py`. "
        "Per-domain counts are asserted against the 2026-09-30 brain-reconciliation "
        "ledger classification table. "
        "The three index files are self-referential (their blob SHAs are omitted by "
        "design); every other file lists its exact blob SHA at the basis commit.",
        "",
        "## Domain counts",
        "",
        "| Domain | Files |",
        "|---|---|",
    ]
    for domain in DOMAIN_ORDER:
        lines.append(f"| {domain} | {counts.get(domain, 0)} |")
    lines += ["", "## Files", ""]
    current_domain = None
    for f in files:
        d = domain_of(f["path"])
        if d != current_domain:
            current_domain = d
            lines.append(f"### {DOMAIN_TITLES[d]}")
            lines.append("")
        if f["path"] in RECEIPT_PATHS:
            lines.append(f"- `{f['path']}` — _(self-referential index file; blob SHA omitted)_")
        else:
            lines.append(f"- `{f['path']}` — `{f['sha'][:12]}` ({f['size']} bytes)")
    lines.append("")
    return "\n".join(lines)


def patch_brain_index(root: Path, basis: str, counts: dict[str, int], today: str) -> str:
    p = root / "BRAIN" / "NAYAPOWER-BRAIN-INDEX.json"
    doc = json.loads(p.read_text(encoding="utf-8"))
    # Mechanical fields only. Every semantic section (nine_nodes, proof_boundary,
    # operations, ...) is preserved exactly as-is.
    doc["generated_at"] = today
    doc["inventory_file_count"] = sum(counts.values())
    doc["last_reconciled_main"] = basis
    doc["reconciliation"] = {
        "ledger": ".naya/project-intelligence/brain-reconciliation-ledger-f648833b.md",
        "reconciled_at": today,
        "basis_commit": basis,
        "method": "tools/regenerate_brain_index.py from the committed git tree",
        "domain_counts": counts,
        "note": (
            "Counts are machine-verified against the Git tree. Semantic sections "
            "(nine_nodes, proof_boundary, operations, ...) are preserved untouched; "
            "only generated_at, inventory_file_count, last_reconciled_main and this "
            "section are mechanical."
        ),
    }
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


# ---- check mode: normalize provenance stamps before comparing ----

DATE_RE = re.compile(r"\d{4}-\d{2}-\d{2}")
SHA_RE = re.compile(r"\b[0-9a-f]{40}\b")


def normalize_json(text: str) -> str:
    doc = json.loads(text)
    doc["generated_at"] = "DATE"
    for key in ("last_reconciled_main", "receipt_basis_commit"):
        if key in doc:
            doc[key] = "SHA"
    if isinstance(doc.get("reconciliation"), dict):
        doc["reconciliation"]["reconciled_at"] = "DATE"
        doc["reconciliation"]["basis_commit"] = "SHA"
    return json.dumps(doc, indent=2, sort_keys=True, ensure_ascii=False)


def normalize_md(text: str) -> str:
    text = DATE_RE.sub("DATE", text)
    text = SHA_RE.sub("SHA", text)
    return text


def check(root: Path) -> int:
    files = inventory(root)
    counts = domain_counts(files)
    problems = []
    expected = expected_domain_counts(files)
    if counts != expected:
        problems.append(f"domain counts drifted: {counts} != ledger+reports {expected}")
    pointer_errors = validate_pointers(root)
    if pointer_errors:
        print("error: pointer integrity check failed:", file=sys.stderr)
        for e in pointer_errors:
            print(f"  {e}", file=sys.stderr)
        print("A dangling pointer in the index layer fails the run — fix the pointer, do not force.",
              file=sys.stderr)
        return 2
    basis = basis_commit(root)
    today = datetime.date.today().isoformat()
    want = {
        "BRAIN/REAL-TREE.json": normalize_json(build_real_tree_json(basis, files, counts, today)),
        "BRAIN/REAL-TREE.md": normalize_md(build_real_tree_md(basis, files, counts, today)),
        "BRAIN/NAYAPOWER-BRAIN-INDEX.json": normalize_json(
            patch_brain_index(root, basis, counts, today)
        ),
    }
    normalizers = {
        "BRAIN/REAL-TREE.json": normalize_json,
        "BRAIN/REAL-TREE.md": normalize_md,
        "BRAIN/NAYAPOWER-BRAIN-INDEX.json": normalize_json,
    }
    for rel, norm in normalizers.items():
        have = norm((root / rel).read_text(encoding="utf-8"))
        # generated_at must still be a real date even though its value is normalized away
        raw = (root / rel).read_text(encoding="utf-8")
        if '"generated_at"' in raw and not DATE_RE.search(raw):
            problems.append(f"{rel}: generated_at is not a valid date")
        if have != want[rel]:
            problems.append(f"{rel} does not match regenerated output")
    # basis SHAs must be well-formed even though their values are normalized away
    for rel in ("BRAIN/REAL-TREE.json", "BRAIN/NAYAPOWER-BRAIN-INDEX.json"):
        raw = (root / rel).read_text(encoding="utf-8")
        if not SHA_RE.search(raw):
            problems.append(f"{rel}: no well-formed basis SHA found")
    if problems:
        print("DRIFT:")
        for p in problems:
            print(" -", p)
        return 1
    print(f"OK: index layer matches git tree ({len(files)} files)")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--root", default=None, help="repo root (default: grandparent of tools/)")
    ap.add_argument("--check", action="store_true", help="verify only; do not write")
    args = ap.parse_args()

    root = Path(args.root) if args.root else Path(__file__).resolve().parents[1]
    if not (root / "BRAIN").is_dir() or not (root / ".git").exists():
        print(f"error: {root} does not look like the NayaPOWER repo root", file=sys.stderr)
        return 2
    try:
        files = inventory(root)
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    counts = domain_counts(files)
    expected = expected_domain_counts(files)
    if counts != expected:
        print("error: domain counts do not match the reconciliation ledger + governed append-only memory subtrees:", file=sys.stderr)
        print(f"  git:      {counts}", file=sys.stderr)
        print(f"  expected: {expected}", file=sys.stderr)
        print("A real non-governed BRAIN/ count change landed — update BASE_EXPECTED_DOMAIN_COUNTS deliberately, do not force.", file=sys.stderr)
        return 2

    pointer_errors = validate_pointers(root)
    if pointer_errors:
        print("error: pointer integrity check failed:", file=sys.stderr)
        for e in pointer_errors:
            print(f"  {e}", file=sys.stderr)
        print("A dangling pointer in the index layer fails the run — fix the pointer, do not force.",
              file=sys.stderr)
        return 2

    if args.check:
        return check(root)

    basis = basis_commit(root)
    today = datetime.date.today().isoformat()
    (root / "BRAIN" / "REAL-TREE.json").write_text(
        build_real_tree_json(basis, files, counts, today), encoding="utf-8"
    )
    (root / "BRAIN" / "REAL-TREE.md").write_text(
        build_real_tree_md(basis, files, counts, today), encoding="utf-8"
    )
    (root / "BRAIN" / "NAYAPOWER-BRAIN-INDEX.json").write_text(
        patch_brain_index(root, basis, counts, today), encoding="utf-8"
    )
    print(f"regenerated index layer from basis {basis[:8]}: {len(files)} files, "
          f"{len(counts)-1} domains + ROOT")
    return 0


if __name__ == "__main__":
    sys.exit(main())
