#!/usr/bin/env python3
"""Regenerate the NayaPOWER Brain index layer from git truth.

Regenerates from the committed git tree (never the working tree, never the
ledger's stale per-file names):
    BRAIN/REAL-TREE.json
    BRAIN/REAL-TREE.md
and patches the mechanical fields of:
    BRAIN/NAYAPOWER-BRAIN-INDEX.json

Usage:
    python3 tools/regenerate_brain_index.py [--root PATH] [--check]

--check verifies the three files match what regeneration would produce and
exits 1 on drift (suitable for CI). It compares everything EXCEPT the
provenance stamps (generated_at date, last_reconciled_main /
receipt_basis_commit SHAs), which record the verification event rather than
tree-derived data: generated_at only needs to be a valid date, and the basis
SHAs only need to be well-formed. Any real BRAIN/ change (added, removed, or
edited file) still fails the check.

Reconciliation rules (2026-09-30 brain-reconciliation ledger):
    - Per-domain counts must match the ledger's classification table (asserted;
      any drift fails the run instead of silently rewriting the table).
    - Never invent or alter semantic/contract claims — counts, file lists,
      pointers and dated banners only.
    - The three index files are self-referential: instead of listing their own
      blob SHAs (which would make the content a moving target — the SHA changes
      every time the file is regenerated), their table entries carry
      "_self_referential": true with no blob SHA. file_count always equals the
      true tree size (157), so the ledger's count assertions still hold.

Exit codes: 0 = ok (or --check passed); 1 = --check found drift; 2 = usage/git error.
"""

from __future__ import annotations

import argparse
import datetime
import json
import re
import subprocess
import sys
from pathlib import Path

# Receipt files: regenerated by this script; excluded from their own blob listing
# (fixed-point design — see module docstring).
RECEIPT_PATHS = {
    "BRAIN/REAL-TREE.json",
    "BRAIN/REAL-TREE.md",
    "BRAIN/NAYAPOWER-BRAIN-INDEX.json",
}

# Ledger classification table: domain -> file count (includes each domain's README).
EXPECTED_DOMAIN_COUNTS = {
    "00-SPEC": 15,
    "01-GOVERNANCE": 3,
    "02-ARCHITECTURE": 5,
    "03-KERNEL": 27,
    "04-INTELLIGENCE": 23,
    "05-MEMORY": 18,
    "06-PROOF": 10,
    "07-LEARNING": 2,
    "08-SUCCESSION": 2,
    "09-EVOLUTION": 2,
    "10-INTERFACES": 5,
    "11-KNOWLEDGE": 7,
    "12-ENGINEERING": 23,
    "90-OPERATIONS": 9,
    "99-ARCHIVE": 1,
    "ROOT": 5,
}

DOMAIN_TITLES = {
    "00-SPEC": "00-SPEC — Specification",
    "01-GOVERNANCE": "01-GOVERNANCE — Governance",
    "02-ARCHITECTURE": "02-ARCHITECTURE — Architecture",
    "03-KERNEL": "03-KERNEL — Kernel",
    "04-INTELLIGENCE": "04-INTELLIGENCE — Intelligence",
    "05-MEMORY": "05-MEMORY — Memory",
    "06-PROOF": "06-PROOF — Proof",
    "07-LEARNING": "07-LEARNING — Learning",
    "08-SUCCESSION": "08-SUCCESSION — Succession",
    "09-EVOLUTION": "09-EVOLUTION — Evolution",
    "10-INTERFACES": "10-INTERFACES — Interfaces",
    "11-KNOWLEDGE": "11-KNOWLEDGE — Knowledge",
    "12-ENGINEERING": "12-ENGINEERING — Engineering",
    "90-OPERATIONS": "90-OPERATIONS — Operations",
    "99-ARCHIVE": "99-ARCHIVE — Archive",
    "ROOT": "ROOT — Brain root files",
}


def git(args: list[str], root: Path) -> str:
    proc = subprocess.run(["git", *args], capture_output=True, text=True, cwd=root)
    if proc.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)} failed: {proc.stderr.strip()}")
    return proc.stdout


def basis_commit(root: Path) -> str:
    """The main revision this index is reconciled against (provenance stamp).

    Uses the merge-base of HEAD with origin/main when the remote ref is
    available (the last main revision this work was verified against),
    falling back to HEAD on a detached/no-remote checkout.
    """
    try:
        return git(["merge-base", "HEAD", "origin/main"], root).strip()
    except RuntimeError:
        return git(["rev-parse", "HEAD"], root).strip()


def inventory(root: Path) -> list[dict]:
    """Return [{path, sha(blob), size}] for every blob under BRAIN/ at HEAD."""
    out = git(
        ["ls-tree", "-r", "--format=%(objectname) %(objectsize) %(path)", "HEAD", "--", "BRAIN/"],
        root,
    )
    files = []
    for line in out.splitlines():
        sha, size, path = line.split(" ", 2)
        files.append({"path": path, "sha": sha, "size": int(size)})
    files.sort(key=lambda f: f["path"])
    return files


def domain_of(path: str) -> str:
    if path == "BRAIN/REAL-TREE.json" or path == "BRAIN/REAL-TREE.md":
        return "ROOT"
    parts = path.split("/")
    if len(parts) == 2:
        return "ROOT"
    return parts[1]


def domain_counts(files: list[dict]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for f in files:
        d = domain_of(f["path"])
        counts[d] = counts.get(d, 0) + 1
    return counts


def build_real_tree_json(basis: str, files: list[dict], counts: dict[str, int], today: str) -> str:
    entries = []
    for f in files:
        if f["path"] in RECEIPT_PATHS:
            entries.append({"path": f["path"], "_self_referential": True,
                            "note": "regenerated by tools/regenerate_brain_index.py; blob SHA omitted (fixed-point design)"})
        else:
            entries.append({"path": f["path"], "blob_sha": f["sha"], "size": f["size"]})
    doc = {
        "schema": "naya.brain.real_tree.v1",
        "generated_at": today,
        "receipt_basis_commit": basis,
        "inventory_file_count": len(files),
        "domain_counts": counts,
        "ledger_assertion": (
            "Per-domain counts asserted against the 2026-09-30 brain-reconciliation "
            "ledger classification table. Any drift fails regeneration instead of "
            "silently rewriting the table."
        ),
        "files": entries,
    }
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


def build_real_tree_md(basis: str, files: list[dict], counts: dict[str, int], today: str) -> str:
    lines = [
        "# NayaPOWER Brain — Real Tree (machine-verified)",
        "",
        f"**Generated:** {today}  ",
        f"**Receipt basis commit:** `{basis}`  ",
        f"**Inventory file count:** {len(files)}  ",
        "",
        "> Regenerated from the committed git tree by `tools/regenerate_brain_index.py`. "
        "Per-domain counts are asserted against the 2026-09-30 brain-reconciliation "
        "ledger classification table. "
        "The three index files are self-referential (their blob SHAs are omitted by "
        "design); every other file lists its exact blob SHA at the basis commit.",
        "",
        "## Domain counts",
        "",
        "| Domain | Files |",
        "|---|---|",
    ]
    for domain in EXPECTED_DOMAIN_COUNTS:
        lines.append(f"| {domain} | {counts.get(domain, 0)} |")
    lines += ["", "## Files", ""]
    current_domain = None
    for f in files:
        d = domain_of(f["path"])
        if d != current_domain:
            current_domain = d
            lines.append(f"### {DOMAIN_TITLES[d]}")
            lines.append("")
        if f["path"] in RECEIPT_PATHS:
            lines.append(f"- `{f['path']}` — _(self-referential index file; blob SHA omitted)_")
        else:
            lines.append(f"- `{f['path']}` — `{f['sha'][:12]}` ({f['size']} bytes)")
    lines.append("")
    return "\n".join(lines)


def patch_brain_index(root: Path, basis: str, counts: dict[str, int], today: str) -> str:
    p = root / "BRAIN" / "NAYAPOWER-BRAIN-INDEX.json"
    doc = json.loads(p.read_text(encoding="utf-8"))
    # Mechanical fields only. Every semantic section (nine_nodes, proof_boundary,
    # operations, ...) is preserved exactly as-is.
    doc["generated_at"] = today
    doc["inventory_file_count"] = sum(counts.values())
    doc["last_reconciled_main"] = basis
    doc["reconciliation"] = {
        "ledger": "brain-reconciliation-ledger-f648833b.md",
        "reconciled_at": today,
        "basis_commit": basis,
        "method": "tools/regenerate_brain_index.py from the committed git tree",
        "domain_counts": counts,
        "note": (
            "Counts are machine-verified against the Git tree. Semantic sections "
            "(nine_nodes, proof_boundary, operations, ...) are preserved untouched; "
            "only generated_at, inventory_file_count, last_reconciled_main and this "
            "section are mechanical."
        ),
    }
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


# ---- check mode: normalize provenance stamps before comparing ----

DATE_RE = re.compile(r"\d{4}-\d{2}-\d{2}")
SHA_RE = re.compile(r"\b[0-9a-f]{40}\b")


def normalize_json(text: str) -> str:
    doc = json.loads(text)
    doc["generated_at"] = "DATE"
    for key in ("last_reconciled_main", "receipt_basis_commit"):
        if key in doc:
            doc[key] = "SHA"
    if isinstance(doc.get("reconciliation"), dict):
        doc["reconciliation"]["reconciled_at"] = "DATE"
        doc["reconciliation"]["basis_commit"] = "SHA"
    return json.dumps(doc, indent=2, sort_keys=True, ensure_ascii=False)


def normalize_md(text: str) -> str:
    text = DATE_RE.sub("DATE", text)
    text = SHA_RE.sub("SHA", text)
    return text


def check(root: Path) -> int:
    files = inventory(root)
    counts = domain_counts(files)
    problems = []
    if counts != EXPECTED_DOMAIN_COUNTS:
        problems.append(f"domain counts drifted: {counts} != ledger {EXPECTED_DOMAIN_COUNTS}")
    basis = basis_commit(root)
    today = datetime.date.today().isoformat()
    want = {
        "BRAIN/REAL-TREE.json": normalize_json(build_real_tree_json(basis, files, counts, today)),
        "BRAIN/REAL-TREE.md": normalize_md(build_real_tree_md(basis, files, counts, today)),
        "BRAIN/NAYAPOWER-BRAIN-INDEX.json": normalize_json(
            patch_brain_index(root, basis, counts, today)
        ),
    }
    normalizers = {
        "BRAIN/REAL-TREE.json": normalize_json,
        "BRAIN/REAL-TREE.md": normalize_md,
        "BRAIN/NAYAPOWER-BRAIN-INDEX.json": normalize_json,
    }
    for rel, norm in normalizers.items():
        have = norm((root / rel).read_text(encoding="utf-8"))
        # generated_at must still be a real date even though its value is normalized away
        raw = (root / rel).read_text(encoding="utf-8")
        if '"generated_at"' in raw and not DATE_RE.search(raw):
            problems.append(f"{rel}: generated_at is not a valid date")
        if have != want[rel]:
            problems.append(f"{rel} does not match regenerated output")
    # basis SHAs must be well-formed even though their values are normalized away
    for rel in ("BRAIN/REAL-TREE.json", "BRAIN/NAYAPOWER-BRAIN-INDEX.json"):
        raw = (root / rel).read_text(encoding="utf-8")
        if not SHA_RE.search(raw):
            problems.append(f"{rel}: no well-formed basis SHA found")
    if problems:
        print("DRIFT:")
        for p in problems:
            print(" -", p)
        return 1
    print(f"OK: index layer matches git tree ({len(files)} files)")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--root", default=None, help="repo root (default: grandparent of tools/)")
    ap.add_argument("--check", action="store_true", help="verify only; do not write")
    args = ap.parse_args()

    root = Path(args.root) if args.root else Path(__file__).resolve().parents[1]
    if not (root / "BRAIN").is_dir() or not (root / ".git").exists():
        print(f"error: {root} does not look like the NayaPOWER repo root", file=sys.stderr)
        return 2
    try:
        files = inventory(root)
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    counts = domain_counts(files)
    if counts != EXPECTED_DOMAIN_COUNTS:
        print("error: domain counts do not match the reconciliation ledger table:", file=sys.stderr)
        print(f"  git:    {counts}", file=sys.stderr)
        print(f"  ledger: {EXPECTED_DOMAIN_COUNTS}", file=sys.stderr)
        print("A real BRAIN/ change landed — update EXPECTED_DOMAIN_COUNTS deliberately, do not force.", file=sys.stderr)
        return 2

    if args.check:
        return check(root)

    basis = basis_commit(root)
    today = datetime.date.today().isoformat()
    (root / "BRAIN" / "REAL-TREE.json").write_text(
        build_real_tree_json(basis, files, counts, today), encoding="utf-8"
    )
    (root / "BRAIN" / "REAL-TREE.md").write_text(
        build_real_tree_md(basis, files, counts, today), encoding="utf-8"
    )
    (root / "BRAIN" / "NAYAPOWER-BRAIN-INDEX.json").write_text(
        patch_brain_index(root, basis, counts, today), encoding="utf-8"
    )
    print(f"regenerated index layer from basis {basis[:8]}: {len(files)} files, "
          f"{len(counts)-1} domains + ROOT")
    return 0


if __name__ == "__main__":
    sys.exit(main())
