create table if not exists public.v7_intelligence_reports (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, period_type text not null check (period_type in ('DAILY','WEEKLY','MONTHLY','YEARLY')), period_start timestamptz not null, period_end timestamptz not null, report jsonb not null default '{}'::jsonb, status text not null default 'COMPLETED' check (status in ('PROCESSING','COMPLETED','FAILED')), created_at timestamptz not null default now(), unique(user_id, period_type, period_start));
create index if not exists v7_intelligence_reports_user_period_idx on public.v7_intelligence_reports(user_id, period_type, period_start desc);
alter table public.v7_intelligence_reports enable row level security;
drop policy if exists v7_intelligence_reports_owner on public.v7_intelligence_reports;
create policy v7_intelligence_reports_owner on public.v7_intelligence_reports for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create table if not exists public.v7_reminders (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null, instruction text, remind_at timestamptz, trigger_type text not null default 'TIME' check (trigger_type in ('TIME','DATE','PREDICTIVE','CONTEXT')), trigger_config jsonb not null default '{}'::jsonb, status text not null default 'ACTIVE' check (status in ('ACTIVE','SENT','DISMISSED','CANCELLED')), source_event_id uuid references public.smart_note_events(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists v7_reminders_user_status_time_idx on public.v7_reminders(user_id, status, remind_at);
alter table public.v7_reminders enable row level security;
drop policy if exists v7_reminders_owner on public.v7_reminders;
create policy v7_reminders_owner on public.v7_reminders for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create or replace function public.v7_reminders_updated_at() returns trigger language plpgsql set search_path=public as $$ begin new.updated_at=now(); return new; end; $$;
drop trigger if exists v7_reminders_updated_at on public.v7_reminders;
create trigger v7_reminders_updated_at before update on public.v7_reminders for each row execute function public.v7_reminders_updated_at();
