
alter table public.nayanet_smart_ledger add column if not exists chain_seq bigint generated by default as identity;
create unique index if not exists nayanet_smart_ledger_owner_chain_seq_uq on public.nayanet_smart_ledger(owner_id,chain_seq);

do $$
declare r record; prev text;
begin
 for r in select ledger_event_id,owner_id,event_type,event_at,source_table,source_id,parent_ledger_event_id,chain_seq,evidence_refs,metadata
           from public.nayanet_smart_ledger order by owner_id,chain_seq
 loop
   select l.event_hash into prev from public.nayanet_smart_ledger l
   where l.owner_id=r.owner_id and l.chain_seq<r.chain_seq
   order by l.chain_seq desc limit 1;
   update public.nayanet_smart_ledger l
      set previous_chain_hash=prev,
          event_hash=public.nayanet_smart_ledger_hash(r.owner_id,r.event_type,r.event_at,r.source_table,r.source_id,r.parent_ledger_event_id,prev,r.evidence_refs,r.metadata)
    where l.ledger_event_id=r.ledger_event_id;
 end loop;
end $$;

create or replace function public.nayanet_record_ledger_event(
 p_owner_id uuid,p_event_type text,p_source_table text,p_source_id text,p_event_at timestamptz default now(),
 p_actor_id uuid default null,p_privacy_classification text default 'PRIVATE',p_status text default 'RECORDED',
 p_evidence_refs jsonb default '[]'::jsonb,p_verification jsonb default '{}'::jsonb,p_value jsonb default '{}'::jsonb,
 p_outcome jsonb default '{}'::jsonb,p_learning_refs jsonb default '[]'::jsonb,p_metadata jsonb default '{}'::jsonb,
 p_parent_ledger_event_id uuid default null
) returns public.nayanet_smart_ledger language plpgsql security definer set search_path=public,extensions as $$
declare v_existing public.nayanet_smart_ledger; v_previous text; v_id uuid:=gen_random_uuid(); v_hash text; v_seq bigint;
begin
 if p_owner_id is null or nullif(trim(p_event_type),'') is null or nullif(trim(p_source_table),'') is null or nullif(trim(p_source_id),'') is null then raise exception 'LEDGER_REQUIRED_FIELDS'; end if;
 select * into v_existing from public.nayanet_smart_ledger where owner_id=p_owner_id and source_table=p_source_table and source_id=p_source_id limit 1;
 if found then return v_existing; end if;
 if p_parent_ledger_event_id is not null then
   select event_hash into v_previous from public.nayanet_smart_ledger where ledger_event_id=p_parent_ledger_event_id and owner_id=p_owner_id;
   if not found then raise exception 'LEDGER_PARENT_NOT_FOUND'; end if;
 else
   select event_hash into v_previous from public.nayanet_smart_ledger where owner_id=p_owner_id order by chain_seq desc limit 1;
 end if;
 v_hash:=public.nayanet_smart_ledger_hash(p_owner_id,p_event_type,p_event_at,p_source_table,p_source_id,p_parent_ledger_event_id,v_previous,coalesce(p_evidence_refs,'[]'::jsonb),coalesce(p_metadata,'{}'::jsonb));
 insert into public.nayanet_smart_ledger(ledger_event_id,schema_version,owner_id,actor_id,event_type,event_at,source_table,source_id,parent_ledger_event_id,previous_chain_hash,event_hash,privacy_classification,status,evidence_refs,verification,value,outcome,learning_refs,metadata)
 values(v_id,'1.0.0',p_owner_id,p_actor_id,p_event_type,p_event_at,p_source_table,p_source_id,p_parent_ledger_event_id,v_previous,v_hash,p_privacy_classification,p_status,coalesce(p_evidence_refs,'[]'::jsonb),coalesce(p_verification,'{}'::jsonb),coalesce(p_value,'{}'::jsonb),coalesce(p_outcome,'{}'::jsonb),coalesce(p_learning_refs,'[]'::jsonb),coalesce(p_metadata,'{}'::jsonb))
 returning * into v_existing;
 return v_existing;
exception when unique_violation then
 select * into v_existing from public.nayanet_smart_ledger where owner_id=p_owner_id and source_table=p_source_table and source_id=p_source_id limit 1;
 if found then return v_existing; end if; raise;
end; $$;

create or replace function public.nayanet_smart_ledger_to_index() returns trigger language plpgsql security definer set search_path=public,extensions as $$
begin
 perform public.nayanet_index_intelligence_row();
 return new;
end; $$;
drop trigger if exists nayanet_smart_ledger_to_intelligence_index on public.nayanet_smart_ledger;
create trigger nayanet_smart_ledger_to_intelligence_index after insert on public.nayanet_smart_ledger for each row execute function public.nayanet_index_intelligence_row();

drop trigger if exists nayanet_report_to_intelligence_index on public.v7_intelligence_reports;
create trigger nayanet_report_to_intelligence_index after insert on public.v7_intelligence_reports for each row execute function public.nayanet_index_intelligence_row();
drop trigger if exists nayanet_learning_to_intelligence_index on public.learning_evidence;
create trigger nayanet_learning_to_intelligence_index after insert on public.learning_evidence for each row execute function public.nayanet_index_intelligence_row();
