create table if not exists public.nayanet_profiles (member_id uuid primary key references public.members(id) on delete cascade, smart_id text unique not null, public_alias text, recovery_ready boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.nayanet_notes (id uuid primary key default gen_random_uuid(), member_id uuid not null references public.members(id) on delete cascade, note_type text not null, human_note text not null, naya_note text, source_context jsonb not null default '{}'::jsonb, shared boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.nayanet_challenges (member_id uuid primary key references public.members(id) on delete cascade, goal text not null default '', current_day integer not null default 1 check (current_day between 1 and 5), completed_days integer[] not null default '{}', updated_at timestamptz not null default now());
create table if not exists public.nayanet_spaces (id uuid primary key default gen_random_uuid(), owner_member_id uuid not null references public.members(id) on delete cascade, name text not null, purpose text not null, visibility text not null default 'private' check (visibility in ('private','shared')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.nayanet_consents (id uuid primary key default gen_random_uuid(), member_id uuid not null references public.members(id) on delete cascade, subject_type text not null, subject_id uuid, shared_with text, purpose text not null, granted_at timestamptz not null default now(), revoked_at timestamptz);
create index if not exists nayanet_notes_member_created_idx on public.nayanet_notes(member_id, created_at desc);
create index if not exists nayanet_spaces_owner_created_idx on public.nayanet_spaces(owner_member_id, created_at desc);
create index if not exists nayanet_consents_member_idx on public.nayanet_consents(member_id, granted_at desc);
alter table public.nayanet_profiles enable row level security;
alter table public.nayanet_notes enable row level security;
alter table public.nayanet_challenges enable row level security;
alter table public.nayanet_spaces enable row level security;
alter table public.nayanet_consents enable row level security;
drop policy if exists nayanet_profiles_owner on public.nayanet_profiles;
create policy nayanet_profiles_owner on public.nayanet_profiles for all using (member_id = auth.uid()) with check (member_id = auth.uid());
drop policy if exists nayanet_notes_owner on public.nayanet_notes;
create policy nayanet_notes_owner on public.nayanet_notes for all using (member_id = auth.uid()) with check (member_id = auth.uid());
drop policy if exists nayanet_challenges_owner on public.nayanet_challenges;
create policy nayanet_challenges_owner on public.nayanet_challenges for all using (member_id = auth.uid()) with check (member_id = auth.uid());
drop policy if exists nayanet_spaces_owner on public.nayanet_spaces;
create policy nayanet_spaces_owner on public.nayanet_spaces for all using (owner_member_id = auth.uid()) with check (owner_member_id = auth.uid());
drop policy if exists nayanet_consents_owner on public.nayanet_consents;
create policy nayanet_consents_owner on public.nayanet_consents for all using (member_id = auth.uid()) with check (member_id = auth.uid());
