
create table if not exists public.nayanet_project_intelligence_bridge (
  id bigint generated by default as identity primary key,
  packet_id text not null unique,
  project_id text not null,
  source_ref text not null,
  content_hash text not null,
  idempotency_key text not null unique,
  packet jsonb not null,
  receiver_transaction_id uuid not null default gen_random_uuid(),
  receiver_event_id uuid not null default gen_random_uuid(),
  receipt_id uuid not null default gen_random_uuid(),
  persisted boolean not null default true,
  indexed boolean not null default false,
  projected boolean not null default false,
  created_at timestamptz not null default now(),
  accepted_at timestamptz not null default now()
);
create index if not exists nayanet_project_intelligence_bridge_source_ref_idx
  on public.nayanet_project_intelligence_bridge(source_ref);
alter table public.nayanet_project_intelligence_bridge enable row level security;
