-- Additive restoration of the canonical SmartLedger runtime seam after the 2026-09-27 reset.
alter table public.nayanet_execution_receipts add column if not exists value jsonb not null default '{}'::jsonb;

create table if not exists public.nayanet_smart_ledger (
  ledger_event_id uuid primary key default gen_random_uuid(),
  schema_version text not null default '1.0.0',
  owner_id uuid not null references auth.users(id),
  actor_id uuid null references auth.users(id),
  event_type text not null,
  event_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  source_table text not null,
  source_id text not null,
  parent_ledger_event_id uuid null references public.nayanet_smart_ledger(ledger_event_id),
  previous_chain_hash text null,
  event_hash text not null,
  privacy_classification text not null default 'PRIVATE',
  status text not null default 'RECORDED',
  evidence_refs jsonb not null default '[]'::jsonb,
  verification jsonb not null default '{}'::jsonb,
  value jsonb not null default '{}'::jsonb,
  outcome jsonb not null default '{}'::jsonb,
  learning_refs jsonb not null default '[]'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  supersedes_ledger_event_id uuid null references public.nayanet_smart_ledger(ledger_event_id),
  qualified_by_ledger_event_id uuid null references public.nayanet_smart_ledger(ledger_event_id),
  constraint nayanet_smart_ledger_source_unique unique(owner_id,source_table,source_id),
  constraint nayanet_smart_ledger_privacy_check check (privacy_classification in ('PRIVATE','SHARED','COLLECTIVE','PUBLIC')),
  constraint nayanet_smart_ledger_status_check check (status in ('RECORDED','VERIFIED','QUALIFIED','SUPERSEDED','BLOCKED','FAILED')),
  constraint nayanet_smart_ledger_evidence_array check (jsonb_typeof(evidence_refs)='array'),
  constraint nayanet_smart_ledger_learning_array check (jsonb_typeof(learning_refs)='array')
);
alter table public.nayanet_smart_ledger add column if not exists chain_seq bigint generated by default as identity;
create unique index if not exists nayanet_smart_ledger_owner_chain_seq_uq on public.nayanet_smart_ledger(owner_id,chain_seq);
create index if not exists nayanet_smart_ledger_owner_time_idx on public.nayanet_smart_ledger(owner_id,event_at desc);
create index if not exists nayanet_smart_ledger_source_idx on public.nayanet_smart_ledger(source_table,source_id);
create index if not exists nayanet_smart_ledger_parent_idx on public.nayanet_smart_ledger(parent_ledger_event_id);

alter table public.nayanet_smart_ledger enable row level security;
drop policy if exists nayanet_smart_ledger_select_own on public.nayanet_smart_ledger;
create policy nayanet_smart_ledger_select_own on public.nayanet_smart_ledger for select to authenticated using ((select auth.uid())=owner_id);
revoke select,insert,update,delete on public.nayanet_smart_ledger from anon,authenticated;

create or replace function public.nayanet_smart_ledger_hash(
 p_owner_id uuid,p_event_type text,p_event_at timestamptz,p_source_table text,p_source_id text,
 p_parent_ledger_event_id uuid,p_previous_chain_hash text,p_evidence_refs jsonb,p_metadata jsonb)
returns text language sql immutable set search_path=public,extensions as $$
 select encode(extensions.digest(
  coalesce(p_owner_id::text,'')||'|'||coalesce(p_event_type,'')||'|'||coalesce(p_event_at::text,'')||'|'||
  coalesce(p_source_table,'')||'|'||coalesce(p_source_id,'')||'|'||coalesce(p_parent_ledger_event_id::text,'')||'|'||
  coalesce(p_previous_chain_hash,'')||'|'||coalesce(p_evidence_refs::text,'')||'|'||coalesce(p_metadata::text,''),'sha256'),'hex');
$$;
revoke all on function public.nayanet_smart_ledger_hash(uuid,text,timestamptz,text,text,uuid,text,jsonb,jsonb) from public,anon,authenticated;

create or replace function public.nayanet_validate_v2_1_value_receipt(p_value jsonb)
returns jsonb language plpgsql immutable set search_path=public,extensions as $$
declare t text; v text; a text; keys text[];
begin
 if p_value is null or p_value='{}'::jsonb or p_value->>'receipt_type' is null then
   return jsonb_build_object('valid',true,'assessment_state','UNASSESSED','receipt_type',null);
 end if;
 t:=p_value->>'receipt_type'; a:=coalesce(p_value->>'assessment_state','');
 if a<>'' and a not in ('ASSESSED','UNASSESSED','VERIFIED_VALUE') then raise exception 'VALUE_RECEIPT_ASSESSMENT_STATE_INVALID'; end if;
 if t='ALIGNMENT_DECISION' then
   keys:=array['receipt_type','schema_version','engine_version','decision_id','objective','baseline_id','stakeholders','horizon','evaluation','authority_basis','evidence_refs','observation_window','verification','delta_v_predicted','delta_v_actual','d_verified','calibration_error'];
   if not (p_value ?& keys) then raise exception 'VALUE_RECEIPT_ALIGNMENT_FIELDS_REQUIRED'; end if;
   if p_value->>'schema_version'<>'2.1' or p_value->>'engine_version'<>'DECISION-VALUE-CALCULUS-V2.1' then raise exception 'VALUE_RECEIPT_ALIGNMENT_VERSION_INVALID'; end if;
   v:=p_value->>'verification';
   if v not in ('UNVERIFIED','PASS_PENDING_WINDOW','VERIFIED_PASS','FAIL','ESCALATE') then raise exception 'VALUE_RECEIPT_ALIGNMENT_VERIFICATION_INVALID'; end if;
   if jsonb_typeof(p_value->'stakeholders')<>'array' or jsonb_typeof(p_value->'evidence_refs')<>'array' or jsonb_typeof(p_value->'evaluation')<>'object' or jsonb_typeof(p_value->'observation_window')<>'object' then raise exception 'VALUE_RECEIPT_ALIGNMENT_SHAPE_INVALID'; end if;
   if a='' then a:=case when v='VERIFIED_PASS' and p_value->>'delta_v_actual' is not null then 'VERIFIED_VALUE' when p_value->>'delta_v_predicted' is not null then 'ASSESSED' else 'UNASSESSED' end; end if;
   if a='VERIFIED_VALUE' and (v<>'VERIFIED_PASS' or p_value->>'delta_v_actual' is null) then raise exception 'VALUE_RECEIPT_VERIFIED_VALUE_REQUIRES_VERIFIED_OUTCOME'; end if;
 elsif t='CONTRIBUTION_VALUE' then
   keys:=array['receipt_type','schema_version','engine_version','contribution_id','action_class','verification_state','verified_delta_v','quality','relevance','verification','impact','novelty','points','points_engine_version','points_derivation','provenance'];
   if not (p_value ?& keys) then raise exception 'VALUE_RECEIPT_CONTRIBUTION_FIELDS_REQUIRED'; end if;
   if p_value->>'schema_version'<>'2.1' then raise exception 'VALUE_RECEIPT_CONTRIBUTION_VERSION_INVALID'; end if;
   if jsonb_typeof(p_value->'provenance')<>'object' then raise exception 'VALUE_RECEIPT_CONTRIBUTION_PROVENANCE_INVALID'; end if;
   v:=p_value->>'verification_state';
   if v not in ('UNVERIFIED','PASS_PENDING_WINDOW','VERIFIED_PASS','FAIL','ESCALATE') then raise exception 'VALUE_RECEIPT_CONTRIBUTION_VERIFICATION_INVALID'; end if;
   if a='' then a:=case when v='VERIFIED_PASS' and p_value->>'verified_delta_v' is not null then 'VERIFIED_VALUE' else 'ASSESSED' end; end if;
   if a='VERIFIED_VALUE' and (v<>'VERIFIED_PASS' or p_value->>'verified_delta_v' is null) then raise exception 'VALUE_RECEIPT_VERIFIED_VALUE_REQUIRES_VERIFIED_OUTCOME'; end if;
   if coalesce((p_value->>'points')::numeric,0)>0 and v<>'VERIFIED_PASS' then raise exception 'VALUE_RECEIPT_POSITIVE_POINTS_REQUIRE_VERIFIED_VALUE'; end if;
 else raise exception 'VALUE_RECEIPT_TYPE_UNSUPPORTED';
 end if;
 return jsonb_build_object('valid',true,'assessment_state',a,'receipt_type',t,'schema_version','2.1','engine_version',p_value->>'engine_version');
end; $$;
revoke all on function public.nayanet_validate_v2_1_value_receipt(jsonb) from public,anon,authenticated;

create or replace function public.nayanet_record_ledger_event(
 p_owner_id uuid,p_event_type text,p_source_table text,p_source_id text,p_event_at timestamptz default now(),
 p_actor_id uuid default null,p_privacy_classification text default 'PRIVATE',p_status text default 'RECORDED',
 p_evidence_refs jsonb default '[]'::jsonb,p_verification jsonb default '{}'::jsonb,p_value jsonb default '{}'::jsonb,
 p_outcome jsonb default '{}'::jsonb,p_learning_refs jsonb default '[]'::jsonb,p_metadata jsonb default '{}'::jsonb,
 p_parent_ledger_event_id uuid default null)
returns public.nayanet_smart_ledger language plpgsql security definer set search_path=public,extensions as $$
declare r public.nayanet_smart_ledger; prev text; h text; info jsonb; m jsonb;
begin
 if p_owner_id is null or nullif(trim(p_event_type),'') is null or nullif(trim(p_source_table),'') is null or nullif(trim(p_source_id),'') is null then raise exception 'LEDGER_REQUIRED_FIELDS'; end if;
 if auth.uid() is not null and auth.uid() is distinct from p_owner_id then raise exception 'LEDGER_OWNER_MISMATCH'; end if;
 info:=public.nayanet_validate_v2_1_value_receipt(coalesce(p_value,'{}'::jsonb));
 select * into r from public.nayanet_smart_ledger where owner_id=p_owner_id and source_table=p_source_table and source_id=p_source_id limit 1;
 if found then return r; end if;
 if p_parent_ledger_event_id is not null then
   select event_hash into prev from public.nayanet_smart_ledger where ledger_event_id=p_parent_ledger_event_id and owner_id=p_owner_id;
   if not found then raise exception 'LEDGER_PARENT_NOT_FOUND'; end if;
 else
   select event_hash into prev from public.nayanet_smart_ledger where owner_id=p_owner_id order by chain_seq desc limit 1;
 end if;
 m:=coalesce(p_metadata,'{}'::jsonb)||jsonb_build_object('assessment_state',info->>'assessment_state','value_receipt_type',info->>'receipt_type');
 if p_value->>'value_engine'='NayaNET_V1_STARTING_MODEL' then m:=m||jsonb_build_object('legacy_value_model','NayaNET_V1_STARTING_MODEL','legacy_provenance_preserved',true); end if;
 if p_value is not null and p_value<>'{}'::jsonb then m:=m||jsonb_build_object('value_receipt_hash',encode(extensions.digest(coalesce(p_value::text,''),'sha256'),'hex')); end if;
 h:=public.nayanet_smart_ledger_hash(p_owner_id,p_event_type,p_event_at,p_source_table,p_source_id,p_parent_ledger_event_id,prev,coalesce(p_evidence_refs,'[]'::jsonb),m);
 insert into public.nayanet_smart_ledger(ledger_event_id,schema_version,owner_id,actor_id,event_type,event_at,source_table,source_id,parent_ledger_event_id,previous_chain_hash,event_hash,privacy_classification,status,evidence_refs,verification,value,outcome,learning_refs,metadata)
 values(gen_random_uuid(),'1.0.0',p_owner_id,p_actor_id,p_event_type,p_event_at,p_source_table,p_source_id,p_parent_ledger_event_id,prev,h,p_privacy_classification,p_status,coalesce(p_evidence_refs,'[]'::jsonb),coalesce(p_verification,'{}'::jsonb),coalesce(p_value,'{}'::jsonb),coalesce(p_outcome,'{}'::jsonb),coalesce(p_learning_refs,'[]'::jsonb),m)
 returning * into r; return r;
exception when unique_violation then
 select * into r from public.nayanet_smart_ledger where owner_id=p_owner_id and source_table=p_source_table and source_id=p_source_id limit 1;
 if found then return r; end if; raise;
end; $$;
revoke all on function public.nayanet_record_ledger_event(uuid,text,text,text,timestamptz,uuid,text,text,jsonb,jsonb,jsonb,jsonb,jsonb,jsonb,uuid) from public,anon,authenticated;

create or replace function public.nayanet_execution_receipt_to_smart_ledger()
returns trigger language plpgsql security definer set search_path=public,extensions as $$
declare e jsonb; v jsonb; info jsonb;
begin
 e:=case when jsonb_typeof(coalesce(new.evidence,'{}'::jsonb))='array' then coalesce(new.evidence,'[]'::jsonb) else jsonb_build_array(coalesce(new.evidence,'{}'::jsonb)) end;
 v:=coalesce(new.value,'{}'::jsonb); info:=public.nayanet_validate_v2_1_value_receipt(v);
 perform public.nayanet_record_ledger_event(new.user_id,case when v->>'receipt_type' is not null then v->>'receipt_type' else 'EXECUTION_RECEIPT' end,'nayanet_execution_receipts',new.id::text,new.created_at,null,'PRIVATE',case when new.status='SUCCESS' then 'VERIFIED' when new.status='BLOCKED' then 'BLOCKED' when new.status='FAILED' then 'FAILED' else 'RECORDED' end,e,jsonb_build_object('receipt_status',new.status,'assessment_state',info->>'assessment_state'),v,jsonb_build_object('observed_result',new.observed_result),case when jsonb_typeof(coalesce(new.learning,'[]'::jsonb))='array' then coalesce(new.learning,'[]'::jsonb) else jsonb_build_array(new.learning) end,jsonb_build_object('action',new.action,'project_id',new.project_id,'revision',new.revision,'source_writer','nayanet_execution_receipts'));
 return new;
end; $$;
drop trigger if exists nayanet_execution_receipt_to_smart_ledger on public.nayanet_execution_receipts;
create trigger nayanet_execution_receipt_to_smart_ledger after insert on public.nayanet_execution_receipts for each row execute function public.nayanet_execution_receipt_to_smart_ledger();
comment on table public.nayanet_smart_ledger is 'Canonical Smart Ledger evidence/integrity layer. No second brain, event, receipt, value, authority, or learning store.';