export const NAV_ITEMS=[{id:'feed',name:'Smart Feed',theme:'emerald',hex:'#55e39a'},{id:'today',name:'Your Intelligence Today',theme:'magenta',hex:'#d86cff'},{id:'reports',name:'Your Reports',theme:'indigo',hex:'#6675ff'},{id:'library',name:'Intelligent Library',theme:'sapphire',hex:'#55b9ee'},{id:'connect',name:'Smart Connect',theme:'emerald',hex:'#55e39a'},{id:'ledger',name:'Smart Ledger',theme:'yellow',hex:'#f1d75a'},{id:'connections',name:'Your Connections',theme:'orange',hex:'#ff9a5a'},{id:'lists',name:'Smart Lists',theme:'purple',hex:'#9d75ff'},{id:'mail',name:'Smart Mail',theme:'sapphire',hex:'#55b9ee'},{id:'spaces',name:'Smart Spaces',theme:'lime',hex:'#b8ee57'},{id:'settings',name:'Settings',theme:'gray',hex:'#aaa4b1'}];
export const MODES={collective:{label:'Collective',description:'Shared intelligence intentionally published through governed consent.'},personal:{label:'Personal',description:'Your private-by-default intelligence environment.'},activity:{label:'Activity',description:'Observed changes and events—not a popularity feed or substitute for truth.'}};
const c={source:'NayaNET design knowledge',boundary:'DESIGN CONTRACT · NOT LIVE RUNTIME',state:'READY'};
export const BOARDS=[
{id:'naya-power',theme:'magenta',hex:'#d86cff',kicker:'FOUNDATION',title:'WHAT IS NAYA POWER?',essence:'The governed intelligence substrate behind the human-facing network.',human:'Memory, learning, governance and proof belong to one coherent system.',naya:'NayaPOWER is the substrate; the Hub is its human-facing projection.',value:'You should not have to manage the brain to benefit from it.',...c},
{id:'naya',theme:'purple',hex:'#9d75ff',kicker:'IDENTITY',title:'WHAT IS NAYA?',essence:'A governed operating partner designed to carry context forward.',human:'A thinking partner that can continue tomorrow without rebuilding the world.',naya:'Naya interprets intelligence through purpose, authority, evidence and continuity.',value:'Less reconstruction. More useful thought.',...c},
{id:'smart-notes',theme:'indigo',hex:'#6675ff',kicker:'CAPTURE',title:'WHAT ARE SMART NOTES?',essence:'A bridge from experience into durable intelligence.',human:'Capture what matters once so it can become useful later.',naya:'A Smart Note is valuable when structured, connected, governed and retrievable.',value:'Important thinking stops disappearing into old conversations.',...c},
{id:'intelligence-today',theme:'sapphire',hex:'#55b9ee',kicker:'DAILY COCKPIT',title:'YOUR INTELLIGENCE TODAY',essence:'The daily surface for what changed, what matters and what deserves attention.',human:'A calmer place to see important things without searching the whole system.',naya:'Today should distill, not overwhelm.',value:'Know the next useful thing without rebuilding context.',...c},
{id:'reports',theme:'emerald',hex:'#55e39a',kicker:'SYNTHESIS',title:'INTELLIGENCE REPORTS',essence:'Cross-time synthesis of decisions, lessons, patterns and outcomes.',human:'See what your intelligence has been teaching you over time.',naya:'Reports should drill back to underlying intelligence and evidence.',value:'Notice progress and patterns that disappear day to day.',...c},
{id:'library',theme:'lime',hex:'#b8ee57',kicker:'RETRIEVAL',title:'WHAT IS THE INTELLIGENT LIBRARY?',essence:'A retrieval door into canonical intelligence and related context.',human:'Find meaning, not merely files.',naya:'The library navigates intelligence; it does not become a competing brain.',value:'Get back to useful knowledge without hunting for documents.',...c},
{id:'lists',theme:'yellow',hex:'#f1d75a',kicker:'ORGANIZE',title:'SMART LISTS',essence:'Intentional organization without copying intelligence itself.',human:'Put the same intelligence into useful views without duplicates.',naya:'Lists organize canonical objects instead of manufacturing new truth.',value:'Create personal structure without fragmenting memory.',...c},
{id:'feed',theme:'orange',hex:'#ff9a5a',kicker:'STREAM',title:'INTELLIGENT FEED / SMART FEED',essence:'A living stream separating collective, personal and observed activity.',human:'A current window into what is happening.',naya:'Engagement is never a substitute for verification.',value:'See what changed without confusing noise for intelligence.',...c},
{id:'smart-tabs',theme:'red',hex:'#ff5a6e',kicker:'NAVIGATION',title:'SMART TABS',essence:'Purpose-built navigation into different expressions of one intelligence.',human:'Different doors into the same environment.',naya:'Navigation changes representation, not the source of truth.',value:'Move through complexity without losing your place.',...c}];
export const ROOM_CONTENT={
feed:{headline:'See what is happening without confusing noise for intelligence.'},
today:{headline:'Make the next useful thing obvious.'},
reports:{headline:'See what your intelligence has been teaching you over time.',copy:'Reports synthesize changes across time. Live synthesis remains NOT VERIFIED until the governed runtime is connected.'},
library:{headline:'Find meaning, not merely files.',copy:'The Intelligent Library is a retrieval door into canonical intelligence and related context.'},
connect:{headline:'Choose the door, then verify authority.'},
ledger:{headline:'Show what can be substantiated.',copy:'Receipts, actions and outcomes belong here only when the governed substrate can support them.'},
connections:{headline:'See the relationships that actually matter.',copy:'Connections require governed identity, context and permission. This standalone build does not invent live relationships.'},
lists:{headline:'Organize intelligence without duplicating it.',copy:'Lists are views over canonical intelligence. They do not create another brain.'},
mail:{headline:'Communication with intelligence context.',copy:'Smart Mail is ready for a governed communication adapter; no mailbox contents are fabricated here.'},
spaces:{headline:'Give related intelligence a place to work.',copy:'Spaces gather relevant intelligence while preserving the underlying ownership and permission boundaries.'},
settings:{headline:'Control your environment.',copy:'Identity, privacy, interface preferences and connected capability belong here.'},
};
export const DOORS=[{id:'mcp',name:'MCP',theme:'purple',hex:'#9d75ff',kind:'AI AGENTS',audience:'Agent → NayaPOWER',status:'REGISTERED',description:'Tools and context for governed agents.'},{id:'rest',name:'REST / OpenAPI',theme:'sapphire',hex:'#55b9ee',kind:'PROGRAMMATIC',audience:'Apps / Agents',status:'REGISTERED',description:'Programmatic access to governed operations.'},{id:'github',name:'GitHub App',theme:'indigo',hex:'#6675ff',kind:'CODING',audience:'Repository agents',status:'REGISTERED',description:'Governed repository operations.'},{id:'webhooks',name:'Webhooks',theme:'teal',hex:'#4fe0c3',kind:'EVENTS',audience:'External systems',status:'BOUNDARY',description:'System-to-NayaPOWER event intake.'},{id:'sdk',name:'SDK',theme:'emerald',hex:'#55e39a',kind:'DEVELOPERS',audience:'Product builders',status:'BOUNDARY',description:'Embed governed intelligence in products.'},{id:'a2a',name:'A2A',theme:'lime',hex:'#b8ee57',kind:'AGENTS',audience:'Agent ↔ agent',status:'BOUNDARY',description:'Governed agent collaboration.'},{id:'browser',name:'Browser / Web Hub',theme:'magenta',hex:'#d86cff',kind:'HUMANS',audience:'People',status:'AVAILABLE',description:'The human cockpit itself is a door.'},{id:'messaging',name:'Email / Messaging',theme:'orange',hex:'#ff9a5a',kind:'COMMUNICATION',audience:'Humans / networks',status:'BOUNDARY',description:'Communication adapters with intelligence context.'},{id:'enterprise',name:'Enterprise Identity',theme:'gold',hex:'#e8b64c',kind:'ORGANIZATIONS',audience:'Organizations',status:'LATER',description:'Organization-level authorization boundary.'},{id:'private-mcp',name:'Private MCP Tunnel',theme:'red',hex:'#ff5a6e',kind:'PRIVATE',audience:'On-prem agents',status:'LATER',description:'Specialized private access.'}];
export function roomFor(id){return NAV_ITEMS.find(x=>x.id===id)||NAV_ITEMS[1]}
export function roomContent(id){return ROOM_CONTENT[id]||ROOM_CONTENT.today}
export function roomFromHash(hash){const id=(hash||'').replace(/^#\/?/,'').trim();return NAV_ITEMS.some(x=>x.id===id)?id:null}
export function initialState(){return{room:'today',mode:'personal',favorites:[],saved:[]}}
export function reduce(s,a){switch(a.type){case'ROOM':return{...s,room:roomFor(a.room).id};case'MODE':return MODES[a.mode]?{...s,mode:a.mode}:s;case'TOGGLE_FAVORITE':return{...s,favorites:s.favorites.includes(a.id)?s.favorites.filter(x=>x!==a.id):[...s.favorites,a.id]};case'TOGGLE_SAVE':return{...s,saved:s.saved.includes(a.id)?s.saved.filter(x=>x!==a.id):[...s.saved,a.id]};default:return s}}
export function searchAll(q,bs=BOARDS){const v=q.trim().toLowerCase();return v?bs.filter(b=>[b.title,b.essence,b.human,b.naya,b.value,b.kicker].some(x=>x.toLowerCase().includes(v))):bs}
