import {NAV_ITEMS,BOARDS,DOORS,MODES,roomFor,searchAll,initialState,reduce} from './app-core.mjs';
const KEY='nayanet.hub.local.v1',q=s=>document.querySelector(s),qq=s=>[...document.querySelectorAll(s)];
let state=read(),query='';
function read(){try{return {...initialState(),...JSON.parse(localStorage.getItem(KEY)||'null')}}catch{return initialState()}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function go(a){state=reduce(state,a);save();render()}
const time=()=>{const h=new Date().getHours();return h<12?'GOOD MORNING':h<18?'GOOD AFTERNOON':'GOOD EVENING'};
const date=()=>new Intl.DateTimeFormat(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'}).format(new Date());
function icon(id){const p={feed:'M4 14 12 6l8 8M7 13v6h10v-6M10 19v-4h4',today:'M12 3l2 6 6 2-6 2-2 6-2-6-6-2 6-2z',reports:'M5 4h14v16H5zM8 8h8M8 12h5M8 16h8',library:'m12 4 7 4v8l-7 4-7-4V8zM8 10l4 2 4-2M12 12v6',connect:'M8 12a4 4 0 0 0 0 8 4 4 0 0 0 0-8m8 0a4 4 0 0 0 0 8 4 4 0 0 0 0-8M11 16h2',ledger:'M6 6h12M6 10h12M6 14h7M6 18h9',connections:'M7 9a3 3 0 1 0 0 6 3 3 0 0 0 0-6m10 0a3 3 0 1 0 0 6 3 3 0 0 0 0-6m-7 6 2-3m2 0 2 3',lists:'M6 7h12M6 12h12M6 17h8M4 7h.1M4 12h.1M4 17h.1',mail:'M4 6h16v12H4zM5 8l7 5 7-5',spaces:'m12 4 6 4v8l-6 4-6-4V8zM9 10l3-2 3 2v4l-3 2-3-2z',settings:'M12 9a3 3 0 1 0 0 6 3 3 0 0 0 0-6m0-6v3m0 12v3m-9-9h3m12 0h3'};return '<svg viewBox="0 0 24 24"><path d="'+(p[id]||p.today)+'"/></svg>'}
function jewel(theme){return '<span class="jewel" style="--accent:var(--'+theme+')"></span>'}
function status(s){return '<span class="status '+(s==='READY'?'ready':'not')+'">'+s.replace('_',' ')+'</span>'}
function nav(){q('#nav').innerHTML=NAV_ITEMS.map(n=>'<button class="'+(state.room===n.id?'active':'')+'" style="--nav:'+n.hex+'" data-room="'+n.id+'">'+icon(n.id)+'<label>'+n.name+'</label></button>').join('')}
function board(b){const fav=state.favorites.includes(b.id),saved=state.saved.includes(b.id);return '<article class="board" style="--accent:'+b.hex+'"><div class="boardhead"><div class="boardid">'+jewel(b.theme)+'<div><div class="kicker">'+b.kicker+'</div><h3>'+b.title+'</h3></div></div>'+status(b.state)+'</div><p class="essence">'+b.essence+'</p><div class="truthline"><span>'+b.source+'</span><span>·</span><span>'+b.boundary+'</span></div><div class="layers"><div class="layer"><span>HUMAN</span><p>'+b.human+'</p></div><div class="layer"><span>NAYA</span><p>'+b.naya+'</p></div><div class="layer"><span>VALUE</span><p>'+b.value+'</p></div></div><div class="actions"><button class="primo '+(fav?'selected':'')+'" data-fav="'+b.id+'">◆ '+(fav?'FAVORITED':'FAVORITE')+'</button><button class="primo '+(saved?'selected':'')+'" data-save="'+b.id+'">◇ '+(saved?'SAVED':'SAVE')+'</button><button class="primo" data-naya="'+b.id+'">✦ ASK NAYA</button></div></article>'}
function today(){const bs=query?searchAll(query,BOARDS):BOARDS;return '<div class="room-head"><div><span class="kicker">YOUR INTELLIGENCE TODAY</span><h2>Make the next useful thing obvious.</h2><p>'+(query?bs.length+' design-known intelligence surfaces match “'+esc(query)+'”.':'The design model is available. Live personal intelligence remains NOT VERIFIED until the governed runtime is connected.')+'</p></div><button class="primo primary" data-naya="today">✦ ASK NAYA WHAT MATTERS</button></div><div class="boards">'+bs.map(board).join('')+'</div>'}
function feed(){const m=MODES[state.mode];return '<div class="room-head"><div><span class="kicker">SMART FEED · '+m.label.toUpperCase()+'</span><h2>'+m.label+' intelligence.</h2><p>'+m.description+'</p></div>'+status('NOT_VERIFIED')+'</div><div class="empty"><div>'+jewel('purple')+'</div><h3>No live feed connected</h3><p>This build never invents activity. Connect the governed runtime to populate real intelligence.</p><button class="primo primary" data-room="today">✦ RETURN TO TODAY</button></div>'}
function room(room,copy,st='NOT_VERIFIED',title=room.name){return '<div class="room-head"><div><span class="kicker">'+room.name.toUpperCase()+'</span><h2>'+title+'</h2><p>'+copy+'</p></div>'+status(st)+'</div><div class="panel"><div>'+jewel(room.theme)+'</div><div><h3>'+room.panelTitle+'</h3><p>'+room.panelCopy+'</p><div class="truth"><strong>RUNTIME '+(st==='READY'?'BOUNDARY':'NOT CONNECTED')+'</strong><span>No remote result is simulated in this standalone build.</span></div></div></div>'}
function connect(){return '<div class="room-head"><div><span class="kicker">SMART CONNECT · SMART DOORS</span><h2>Choose the door, then verify authority.</h2><p>Connection provides a path into intelligence. Connection does not grant authority.</p></div>'+status('NOT_VERIFIED')+'</div><div class="doorgrid">'+DOORS.map(d=>'<article class="door" style="--accent:'+d.hex+'"><div class="doortop">'+jewel(d.theme)+'<span class="kicker">'+d.kind+'</span></div><h3>'+d.name+'</h3><p>'+d.description+'</p><div class="doormeta"><span>'+d.audience+'</span><span>'+d.status+'</span></div><button class="primo" data-door="'+d.id+'">↗ '+(d.status==='AVAILABLE'?'CONNECT':'VIEW BOUNDARY')+'</button></article>').join('')+'</div>'}
function ledger(){return '<div class="room-head"><div><span class="kicker">SMART LEDGER</span><h2>Show what can be substantiated.</h2><p>Receipts and outcomes belong here only when the governed substrate can support them.</p></div>'+status('NOT_VERIFIED')+'</div><div class="metricgrid"><div class="metric"><span class="kicker">CURRENT RUNTIME</span><strong>NOT CONNECTED</strong><p>No economic value is fabricated.</p></div><div class="metric"><span class="kicker">LOCAL ACTION MEMORY</span><strong>'+(state.saved.length+state.favorites.length)+'</strong><p>Local favorites and saves in this browser.</p></div></div>'}
function mail(){return room(NAV_ITEMS.find(x=>x.id==='mail'),'Communication with intelligence context.','NOT_VERIFIED','Communication with intelligence context.')}
function settings(){return '<div class="room-head"><div><span class="kicker">SETTINGS</span><h2>Control your environment.</h2><p>Only local interface preferences are stored by this standalone build.</p></div>'+status('READY')+'</div><div class="settings">'+[['Large text','Keep generous type as the default visual preference.'],['Reduced motion','Honour the system setting while preserving depth.'],['Local memory','Remember favorites and saved surfaces in this browser.']].map((x,i)=>'<div class="setting"><div><h3>'+x[0]+'</h3><p>'+x[1]+'</p></div><button class="toggle '+(i===0?'on':'')+'" aria-pressed="'+(i===0)+'"><span></span></button></div>').join('')+'</div>'}
function render(){const r=roomFor(state.room);nav();q('#title').textContent=r.name;q('#view').textContent=state.room==='feed'?MODES[state.mode].label:r.name;q('#workspace').innerHTML=state.room==='today'?today():state.room==='feed'?feed():state.room==='connect'?connect():state.room==='ledger'?ledger():state.room==='settings'?settings():state.room==='mail'?mail():room(r,r.id==='lists'?'Organize intelligence without creating another copy of the intelligence.':'A canonical room surface waiting for its governed runtime connection.',r.id==='lists'?'READY':'NOT_VERIFIED');qq('.modes button').forEach(b=>{const a=b.dataset.mode===state.mode;b.classList.toggle('active',a);b.setAttribute('aria-selected',a)});q('#time').textContent=time();q('#greeting').textContent=state.room==='today'?'Your intelligence environment is ready.':'You are in '+r.name+'.';q('#meta').innerHTML='<span>TIME '+new Intl.DateTimeFormat(undefined,{hour:'2-digit',minute:'2-digit'}).format(new Date())+'</span><span>DATE '+date()+'</span><span>MODE '+MODES[state.mode].label.toUpperCase()+'</span>';bind()}
function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ask(text){q('#dialogText').textContent='Context: '+text+'. Naya can interpret this surface, but this build will not claim live remote intelligence without a verified runtime.';q('#dialog').showModal()}
function bind(){qq('[data-room]').forEach(b=>b.onclick=()=>go({type:'ROOM',room:b.dataset.room}));qq('[data-fav]').forEach(b=>b.onclick=()=>go({type:'TOGGLE_FAVORITE',id:b.dataset.fav}));qq('[data-save]').forEach(b=>b.onclick=()=>go({type:'TOGGLE_SAVE',id:b.dataset.save}));qq('[data-naya]').forEach(b=>b.onclick=()=>ask(b.dataset.naya));qq('[data-door]').forEach(b=>b.onclick=()=>ask('Smart Door '+b.dataset.door));qq('.modes button').forEach(b=>b.onclick=()=>go({type:'MODE',mode:b.dataset.mode}));qq('.toggle').forEach(b=>b.onclick=()=>{b.classList.toggle('on');b.setAttribute('aria-pressed',b.classList.contains('on'))});qq('.ecosystem a').forEach(a=>a.onclick=e=>{e.preventDefault();ask('ecosystem destination '+a.textContent.trim())})}
q('#search').oninput=e=>{query=e.target.value.trim();render();q('#search').focus()};document.onkeydown=e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();q('#search').focus()}};q('#close').onclick=()=>q('#dialog').close();q('#copy').onclick=async()=>{await navigator.clipboard?.writeText('NayaNET context: room='+state.room+' mode='+state.mode+' runtime=NOT_VERIFIED');q('#copy').textContent='Context copied'};q('#reset').onclick=()=>{localStorage.removeItem(KEY);state=initialState();query='';render()};render();