import { useEffect, useState } from 'react';
// Runtime proof checkpoint: navigation contract verified against canonical Hub acceptance.
import type { ReactNode } from 'react';
import { useIdentity } from '../../identity/session';
import { routes } from '../routing/routes';

type ShellProps={children:(path:string)=>ReactNode};
type NavItem={name:string;route:string;icon:string};
const items:NavItem[]=[
 {name:'Intelligence Today',route:routes.home,icon:'✦'},
 {name:'Reports',route:routes.reports,icon:'◫'},
 {name:'Intelligence Library',route:routes.library,icon:'▱'},
 {name:'Smart Share',route:routes.share,icon:'↗'},
 {name:'Smart Lists',route:routes.lists,icon:'☷'},
 {name:'Smart Spaces',route:routes.spaces,icon:'◌'},
 {name:'Your Connections',route:routes.connections,icon:'↔'},
 {name:'Smart Mail',route:routes.mail,icon:'✉'},
 {name:'Smart Ledger',route:routes.ledger,icon:'◇'},
 {name:'Naya Play',route:routes.play,icon:'▶'},
 {name:'Settings',route:routes.settings,icon:'⚙'}
];

const normalize=(p:string)=>p.length>1&&p.endsWith('/')?p.slice(0,-1):p||'/';
function SmartNoteCapture({go}:{go:(p:string)=>void}){
 const [open,setOpen]=useState(false);const [title,setTitle]=useState('');const [content,setContent]=useState('');const [status,setStatus]=useState('');const [busy,setBusy]=useState(false);
 const capture=async()=>{const noteTitle=title.trim(),noteContent=content.trim();if(!noteTitle||!noteContent){setStatus('TITLE AND CONTENT REQUIRED');return}setBusy(true);setStatus('CAPTURING THROUGH CANONICAL RECEIVER…');try{const runtime=(window as any).NayaAssistantRuntime;if(!runtime)throw new Error('ASSISTANT_RUNTIME_UNAVAILABLE');if(!runtime.snapshot?.()?.authenticated)throw new Error('AUTH_REQUIRED');const result=await runtime.captureSmartNote({title:noteTitle,content:noteContent,metadata:{capture_surface:'NayaNET Intelligent Hub',continuity:'conversation-to-compounding-intelligence'}}) as any;const tx=result?.transaction;const eventId=result?.event?.event_id||result?.event_id||tx?.evidence?.event_id||tx?.hub_state?.event_id||'';const receiptId=result?.receipt?.receipt_id||result?.receipt?.id||result?.receipt_id||tx?.evidence?.receipt_id||'';if(!eventId)throw new Error('CANONICAL_EVENT_ID_NOT_RETURNED');const canonicalEventId=eventId;const persistenceDeadline=Date.now()+15000;let persistenceReady=false;while(Date.now()<persistenceDeadline){const rows=await runtime.retrieve(canonicalEventId);if(Array.isArray(rows)&&rows.some((row:any)=>row?.event_id===canonicalEventId)){persistenceReady=true;break}await new Promise(resolve=>setTimeout(resolve,500));}if(!persistenceReady)throw new Error('SMART_NOTE_PERSISTENCE_NOT_OBSERVABLE');setStatus('CAPTURED · PERSISTED · EVENT '+eventId+' · RECEIPT '+(receiptId||'NOT_RETURNED'));setTitle('');setContent('');setOpen(false);go(routes.feed+'?event_id='+encodeURIComponent(canonicalEventId))}catch(error){setStatus('CAPTURE BLOCKED · '+(error instanceof Error?error.message:'SMART_NOTE_CAPTURE_FAILED'))}finally{setBusy(false)}};
 return <><button type="button" className="top-action" data-testid="capture-smart-note" onClick={()=>{setStatus('');setOpen(true)}}>＋ <span>Capture Smart Note</span></button>{open&&<div className="capture-modal" role="dialog" aria-modal="true" aria-label="Capture Smart Note"><div className="capture-dialog"><div className="capture-eyebrow">SMART NOTE · CANONICAL CAPTURE</div><h2>Capture a Smart Note</h2><p>This saves through the authenticated canonical Smart Note receiver and returns its canonical event identity.</p><label>TITLE<input data-testid="smart-note-title" value={title} onChange={e=>setTitle(e.target.value)} placeholder="What should Naya remember?"/></label><label>CONTENT<textarea data-testid="smart-note-content" value={content} onChange={e=>setContent(e.target.value)} placeholder="What should Naya remember, connect, learn, and reuse?"/></label><div className="capture-actions"><button type="button" onClick={()=>setOpen(false)} disabled={busy}>CANCEL</button><button type="button" data-testid="smart-note-capture-submit" onClick={()=>void capture()} disabled={busy||!title.trim()||!content.trim()}>{busy?'CAPTURING…':'CAPTURE & PERSIST'}</button></div><div className="capture-state" role="status">{status}</div></div></div>}</>;
}

export function AppShellV3({children}:ShellProps){
 const id=useIdentity();const[path,setPath]=useState(()=>normalize(window.location.pathname));const[query,setQuery]=useState('');
 const go=(p:string)=>{const next=normalize(p);if(next===path)return;history.pushState({},'',next);setPath(next)};
 useEffect(()=>{const f=()=>setPath(normalize(window.location.pathname));const nav=(e:Event)=>{const p=(e as CustomEvent<{path?:string}>).detail?.path;if(p)go(p)};const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.querySelector<HTMLInputElement>('.universal-search input')?.focus()}};addEventListener('popstate',f);addEventListener('nayanet:navigate',nav);addEventListener('keydown',key);return()=>{removeEventListener('popstate',f);removeEventListener('nayanet:navigate',nav);removeEventListener('keydown',key)}},[path]);
 const submit=()=>{const q=query.trim();if(!q)return;go(routes.feed);dispatchEvent(new CustomEvent('nayanet:search',{detail:{query:q}}))};
 const current=items.find(x=>x.route===path);const label=current?.name||'Your Intelligence Today';
 return <div className="app" data-shell-owner="AppShellV3" data-route={path} data-runtime-marker="NAYANET-HUB-REACT-CANONICAL"><aside className="sidebar"><button className="brand" onClick={()=>go(routes.home)} aria-label="NayaNET Intelligent Hub"><span className="logo"><span>✦</span></span><span className="brand-copy"><b>NayaNET</b><small>INTELLIGENT HUB</small></span></button><div className="side-context"><span className="online-dot"/><span><b>NAYA IS READY</b><small>Private intelligence workspace</small></span><strong>LIVE</strong></div><div className="nav-section"><span>YOUR INTELLIGENCE</span>{items.map(item=><button key={item.name} className={`nav-item ${path===item.route?'active':''}`} onClick={()=>go(item.route)} aria-current={path===item.route?'page':undefined}><span className="nav-icon">{item.icon}</span><span className="nav-name">{item.name}</span>{path===item.route&&<i className="nav-active-dot"/>}</button>)}</div><div className="sidebar-spacer"/><div className="side-trust"><span className="trust-led"/><div><b>INTELLIGENCE MODE</b><small>Evidence-aware · stateful · bounded</small></div></div></aside><main className="main"><header className="topbar"><div className="top-context"><div className="connectionPill"><span className="led good"/><span>NAYANET ONLINE</span></div><div className="route-context"><span>NAYANET</span><i/> <strong>{label}</strong></div></div><div className="universal-search"><span className="search-icon">⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')submit()}} placeholder="Search or talk to Naya…" aria-label="Search or talk to Naya…"/><span className="search-hint">⌘ K</span><button className="talk-button" onClick={submit}>✦ TALK TO NAYA</button></div><div className="top-actions"><SmartNoteCapture go={go}/><button className="top-action" onClick={()=>go(routes.feed)}>＋ <span>Explore Intelligence</span></button><button className="identity-chip" onClick={()=>go(routes.settings)} aria-label="Open settings"><span className="identity-avatar">{(id.smart_name||'N').slice(0,1).toUpperCase()}</span><span className="identity-copy"><b>{id.smart_name}</b><small>@{id.smart_alias}</small></span></button></div></header><nav className="mobile-nav" aria-label="NayaNET Hub navigation">{items.map(item=><button key={item.name} className={path===item.route?'active':''} onClick={()=>go(item.route)} aria-current={path===item.route?'page':undefined}><span>{item.icon}</span><b>{item.name}</b></button>)}</nav><section className="home">{children(path)}</section></main></div>;
}
